// ===================================================================
// DnB-OS · platform/kb/corpus.js — THE TRAINING LEDGER
// Every Flipspaces plan absorbed leaves its evidence HERE, per code:
// observed durations, actual-vs-plan verdicts, sequence confirmations,
// vocabulary mappings, and the calibrations that were applied to the
// library because of it. Norms cite this ledger; confidence upgrades
// only when independent plans agree. Scale = append, never overwrite.
// ===================================================================

;(function () {

const PLANS = [
  { id: "addverb_2020", file: "Pert- Client.pdf", snapshot: "issued 2020-11-21 (COVID era) — EARLIEST plan in corpus",
    city: "Noida", type: "CLIENT-GENRE exemplar: office + DORM (bunk/modular/wooden beds), 42d finishes-tail recovery schedule (FF/SF/TF/Terrace)",
    spanDays: 42, start: "2020-10-19", finish: "2020-11-30", tasks: 421,
    note: "421/421 rows parsed. What a CLIENT PDF strips: logic, resources, status; durations rounded to 2/3/5/7/35 (35d = every furniture supply); LOE bars disguised as installs; single flat handover; 7-day week promised; NO buffer/snag/T&C shown. PROGRESS PARADOX: issued 21-11 with all leaves 0% yet ~half planned to finish BEFORE issue date — stale dates re-shipped to the client. 49% of leaves crush into the final 8 days. Negative exemplar that VALIDATES our clientPlan policy (re-anchor, translate, never ship stale internals). Supply-dominated even in 2020 (supply median 9d vs install 4d). Final-coat-held-late x4 floors = 3RD WITNESS -> LAW. NOT the internal twin of Pivox — Addverb internal tracker requested." },
  { id: "pivox_2022", file: "PERT 21-03-22.pdf", snapshot: "plan-only baseline (printed day 2)",
    city: "(India)", type: "Pivox Labs 40-day blitz — EARLIEST LOGIC-BEARING witness (MSP 2013, Predecessors column), 5 months before LightStorm",
    spanDays: 40, start: "2022-03-21", finish: "2022-04-29", tasks: 252,
    note: "THE MISSING 4TH DELIVERED PROJECT (durations.js already cited Pivox 4d/8d; corpus had no entry). 193 printed rows parsed incl. 66 wrapped hand-recovered; 59 rows COLLAPSED in export (Electrical Secondary 23 rows fully hidden) — source .mpp requested. 152 edges (123FS/29SS, 31 lagged): ZERO logic-vs-dates violations — 2nd MSP plan enforcing its own logic (Excel genre carried 9). LAW ANCESTORS in their logic: g_wall chain frame->skin->glasswool->PLY BACKING->close (plywood_backing EARLIEST witness, now 3rd overall); glass site-measure lifecycle (channel->measure->deliver 7d->fix) identical to LS; g_pipe_test leakage 2d -> BBC; decoratives gated on FINAL COAT (194SS+4). DAY-ZERO ORDER RELEASE: 7 orders tied 4SS to partition-layout START (blitz variant of LS FS+7 hub). FS-1/FS-2 negative-lag compression signature on closes. Blitz supply ladder: carpentry 2d..glass boards 26d. CONTRADICTION: HVAC commissioning SS with installs vs LS FS-after-ODU — 1-1 recorded." },
  { id: "bfil_ho_2023", file: "Site Training _ PERT.xlsx", snapshot: "plan-only TEMPLATE EXEMPLAR (training workbook)",
    city: "(BFIL HO — city QUERY, do not assume)", type: "101d office baseline used to TEACH the Apr-2025 ops cohort (+ trainee curriculum sheet + 4 live Mumbai training sites)",
    spanDays: 101, start: "2023-09-20", finish: "2024-01-02", tasks: 245,
    note: "Evidence = TEMPLATE norms, not site actuals (no status/weightage; W1-W4 grid never used). 48-LINE PROCUREMENT LADDER (7d raceways/DB .. 45d workstations/loose/FR-glazing/UPS .. 48d white goods) — richest supply-lead table yet. INTEGRITY: duration column FICTITIOUS on 73/245 rows (3 conventions in one sheet — dates authoritative, durations decorative; hand-typed text dates, locale-immune); duplicate kick-off rows; 7-day weeks over Diwali/Christmas. THEIR OWN TEMPLATE VIOLATES R19: carpet install 02-12 Dec overlaps wall 2nd&3rd coat 07-14 Dec — the engine's paint-before-carpet law is stricter than the teaching material. g_wall clearance 7d here (band 3-7d). Duct insulation runs CONCURRENT inside the hang window (method-tie evidence). ws_power_data identical text AGAIN. Sheet3: Murata (IIT-B 5000sqft), Dezerv (BKC 6500), Nashermiles (Marine Lines), Simson (Dahisar) — live training sites w/ owners." },
  { id: "tcs_noida_2024", file: "TCS Noida - PERT.pdf + [EXT-WIP] Phase 1.xlsx (SOURCE)", snapshot: "xlsx ~W6 (early Feb) + PDF ~early Mar — TWO snapshots of one project",
    city: "Noida", type: "CAMPUS-GRADE floor (his most complicated site): 24 weighted sections — kitchen + critical rooms + AHU + precision AC + RO plant + solar water heater + security (flap barriers, food & baggage scanners) + gym + sports vinyl + external signage + full ELV suite",
    spanDays: 105, start: "2023-12-22", finish: "2024-04-05", tasks: 411,
    note: "PDF showed ONLY construction (~200 rows); the SOURCE xlsx carries 411 incl. full design (GFC 58d elapsed; layout suite 2-4d; MEP drawings 23d; samples 38d w/ mockup ROOM) + Major Procurement 62d (34 order lines) + S-CURVE sheet: weekly baseline/planned/actual % — REBASELINED AT W7 (11.9->6.8, ~5% pushed right), actual 6.5 vs baseline 9.5 at the cut = earned-value in the wild. Weightage EXACTLY 100.0% over 24 sections (elec 11.1, ELV&FF 9.9, kitchen 7.45). DATA-INTEGRITY CASE STUDY: dd/mm<->mm/dd locale corruption on every ambiguous day <=12 (5 Jan stored as 2024-05-01); Snag Resolution YEAR typo (2023); decor rows start after finish. Excel accepted all of it — a typed calendar cannot be corrupted this way. DELAY PATTERN (4th plan running): supply lines drive slips (kitchen supplies, AHU terminals, networking supplies, chairs 30d WIP); site trades hold. Duct: insulation 18-28 Jan BEFORE install 21-31 Jan = pre-insulate -> 2-2 TIE. DEEP-GRID READ (his 3rd catch): cols 10-42 = PER-TASK WEEKLY EV MATRIX — planned W1..W13 AND actual AW1..AW5 for 220 tasks, the richest actuals dataset in the corpus (raw lives in the uploads xlsx). ANALYSIS: median task velocity 1.00 at W5 (30 on/ahead, 22 behind) — site trades run ON RATE; laggards are supply/specialist lines (kitchen 0.0, copper trays 0.0, passive networking 0.0, core cutting 0.4, waterproofing 0.5); leaders are civil/drywall/chipping/furniture (1.1-1.3). Completed-task slip: median 0w; MARKING tasks finish -1..-4w EARLY (cheap prep pulled forward — 3rd witness of opportunistic pull), GI framing +2w. CORRECTION to the earlier hasty read: CUMULATIVE actual 26.7% vs baseline 27.2% at W6 = essentially ON CURVE (-0.5pp); the W7 rebaseline redistributed the remaining 73% (peak 12.4%/wk flattened to ~9-11) — weekly increments diverged, cumulative held. ENGINE CHANGE SHIPPED FROM THIS FILE: percent-facts grammar ('blockwork 60% done') -> pct pins reschedule the remainder — the engine now speaks Flipspaces' own weekly-% tracking language." },
  { id: "lightstorm_2022", file: "LS_PERT.pdf", snapshot: "plan-only (Aug 5 2022 baseline)",
    city: "(India, metro)", type: "office fit-out 70d — MS PROJECT WITH FULL DEPENDENCY LOGIC (first logic-bearing witness)",
    spanDays: 70, start: "2022-08-05", finish: "2022-10-13", tasks: 318,
    note: "318/318 rows machine-parsed incl. 4 wrapped rows recovered by hand; 356 edges (329 FS / 13 SS / 9 FF, 101 lagged). ZERO logic-vs-dates violations — MSP enforces its own logic (the Excel-genre plans carried 9). SUPPLY-LAG LADDER mined from their lags: commodity 7d · electrical panels/switches 14d · furniture/carpet-special/raised floor 15-16d · chairs/soft/graphics/film/blinds/rug/signage/logo 20d · glass boards 30d (calendar, domestic fast-track). CONTROL POINTS: Civil Work Order cited 29x (their release hub), Flooring Plan 19x (design hub), conduits floor/ceiling/wall 24x combined (the g_wall/g_ceiling law living in their logic), Dado Fixing 9x, Modular Furniture 7x (FF-hub for decoratives). Their ceiling CLOSES only 2d before FA-test END and HVAC commissioning (278FS-2d, 256FS-2d) — services proven before the plane shuts, in their own logic." },
  { id: "malpani_2024", file: "Malpani Group M-Connect 60-Days PERT.pdf", snapshot: "plan-only",
    city: "(India)", type: "60-day blitz on the STANDARD Flipspaces template (Emirates lineage; kitchen-heavy: Kota stone, BBC, Ansul)",
    spanDays: 60, start: "2024-12-16", finish: "2025-02-15", tasks: 244,
    note: "146/244 rows visible (98 collapsed in export). LOGIC RECOVERED on second read (his catch): positional mapping fails (blank-collapse + SS-degeneracy) but daisy rows SELF-IDENTIFY (pred 19SS + succ 21SS => row 20) — 52 rows, 78 EXACT edges, zero guessing; 62 rows need the source .mpp. THE LOGIC PROVED: (1) sample->Order explicit FS x5 (chairs/loose/SPC/skirting/acoustics) — THIRD witness for the stage reorder; (2) HVAC Heat Load -> Copper piping FS = per-discipline drawing release, THIRD witness, in their own logic; (3) design daisy cascade furniture->partition->lighting->RCP->flooring->dims->modular->wall-finish->elevations; lighting-before-RCP vs LS RCP-first = 1-1 recorded; (4) Client 3D Approvals FF detailed views — approval rides design; (5) staggered SS sample sequence; (6) SLD late in elec set (needs loads). Procurement 48d of 60 — the chain IS the project." },
  { id: "firstsource_2024", file: "Firstsource - PERT.pdf", snapshot: "~2024-09-25 (mid-blitz)",
    city: "(India, metro)", type: "BPO office BLITZ — 54 days; Critical Rooms (Hub/UPS/BMS) + workstation/cafeteria blocks",
    spanDays: 54, start: "2024-09-01", finish: "2024-10-25", tasks: 207,
    note: "WEIGHTED tracking PERT, all 207 rows machine-parsed. TWO earned-value systems: Critical Rooms 9 sections = exactly 100%; main block 32 sections = 97% (3% missing — sheet defect or unlisted section). MEP+fire+ELV carry ~39% of main-block value. Status at snapshot: 20 done / 28 in progress / 8 DELAYED / 147 not started. Delayed cluster: civil prep (POP, blockwork, plaster) + HVAC HIGH-SIDE EQUIPMENT ORDER (the odu/ahu package — procurement, not site, was the slip) + on-site joinery. OUT-OF-SEQUENCE work: FA/PA cabling, raised-floor tiles, glass delivery all running while upstream civil delayed — crews jump to open fronts (2nd witness of opportunistic re-sequencing after DHL). NINE internal integrity violations their Excel accepted: 2 tasks end-before-start, 2nd coat scheduled before 1st (twice), 3 duration-vs-span mismatches, 2 tasks finishing AFTER the declared project end (wall finishes to 4 Nov — the sheet itself admits 25-Oct was fiction for that trade). PRACTICE PATTERNS: final coat HELD 15d for end-of-job touch-up; workstation marking done 28d before frames (mark early, install after floors); glass panes 4d after frames (site-measured)." },
  { id: "dhl_chennai_2026", file: "DHL Macro Schedule.pdf", snapshot: "~2026-06-15",
    city: "Chennai", type: "corporate office 7F + critical rooms (ELE/HUB/server/UPS)",
    spanDays: 109, start: "2026-05-08", finish: "2026-08-25", tasks: 150,
    note: "CONTROL-GENRE sheet: Status/%/Actual/Revised/per-task delay columns — the exact shape of the engine's progress model. Delay patterns: site handover pushed demolition +18d; civil ran EARLY (-7); partition chain slipped +6..12; paint base prep pulled -43d opportunistically; HVAC equipment landed -27/-30 EARLY. Their 'Revised' columns = manual replan the engine now does from facts. 'Scope not confirmed' annotation on ACS control-end = their own live query." },
  { id: "emirates_mumbai_2025", file: "Emirates PERT Extended.pdf", snapshot: "2025-09-30",
    city: "Mumbai", type: "corporate office + critical areas (server room, AHU, precision AC)",
    spanDays: 245, start: "2025-06-23", finish: "2026-02-22", tasks: 392,
    note: "planned + actual columns — design phase slipping ~1wk at snapshot; samples & orders ON TIME; statutory (BMC 15d, Fire NOC + Mathadi 86d) met exactly" },
];

// ---- their words -> our codes (grows with every plan) --------------
const VOCABULARY = {
  "self leveling": "self_leveling", "pcc": "self_leveling", "modifoam flooring": "self_leveling",
  "pop punning": "pop_punning", "blockwork/rcc lintel": "blockwork", "plastering": "plaster",
  "line out marking": "lineout_marking", "line out checking & approval": "lineout_marking",
  "gi framing works": "gi_stud_frame", "single side single skinning": "board_one_face",
  "clearance from services": "GATE g_wall (3d window in practice)", "insulation works": "insulation_partition",
  "second side single skinning": "board_close",
  "demountable glass partition": "glazing_partition", "curved glass partition": "glazing_partition",
  "switchable smart glass": "glazing_partition", "sliding folding partition": "glazing_partition",
  "solid flush doors": "door_install", "fire rated metal doors": "fire_door",
  "raised access flooring": "raised_floor", "spc flooring": "vinyl_lvt",
  "vitrified tiling": "tile_vitrified", "marble flooring": "stone_marble", "stone flooring": "stone_marble",
  "carpet installation": "carpet_tile", "epoxy flooring": "epoxy_flooring",
  "engineered concrete flooring": "epoxy_flooring", "wooden raised flooring": "raised_floor",
  "dado installation": "wall_dado", "gypsum boarding & joint finishing": "ceiling_gypsum",
  "gi framing for gypsum ceiling": "ceiling_gypsum", "grid ceiling": "ceiling_grid_tile",
  "technogrid": "ceiling_grid_tile", "stretch ceiling": "stretch_ceiling",
  "metal fabricated ceiling": "metal_ceiling", "designer ceiling": "metal_ceiling",
  "cafeteria decorative ceiling": "metal_ceiling",
  "putty application": "putty_primer", "primer application & sanding": "putty_primer",
  "1st coat paint": "paint_emulsion", "2nd& 3rd coat paint": "paint_emulsion",
  "epoxy paint": "texture_paint", "mettalic paint": "texture_paint", "stucco paint": "texture_paint",
  "wallpaper installation": "wallpaper", "wall paper base preparation": "wallpaper",
  "lacquered glass panelling": "lacquered_glass", "backpainted glass": "lacquered_glass",
  "glass film installation": "blinds_film", "blinds installation": "blinds_film",
  "fluted panel installation": "fluted_panel", "acoustics/fluted panel": "fluted_panel",
  "vertical garden/planters": "graphics_planters", "branding (logo)": "graphics_planters",
  "signages supply and installation": "signage_evac",
  "reception table / ccm cabin table / board room table / service counter / ledge seating / acrylic designer wall / built-in furniture / pelmet": "joinery_panel",
  "lockers": "storage_unit", "corner guard / transition profile / skirting installation": "skirting",
  "conduiting for raw power, ups, lighting, it": "conduit", "back box fixing": "conduit",
  "wiring for light circuits / power circuits": "circuit_wiring",
  "installation of floor raceway for power & data": "floor_raceway",
  "cable tray for it/data/electrical": "cable_pull", "cabling for power / earthing / dressing": "cable_pull",
  "installation of db's / db dressing and termination": "db_panel",
  "lt panels (delivery/installation/t&c)": "db_panel",
  "ups & battery (supply/install/t&c)": "ups_battery",
  "switches, raw power sockets": "wiring_point",
  "recessed / suspended / decorative light fixtures": "light_fixture",
  "marking & support fixing of ducts / installation of ducts": "duct_gi",
  "insulation for ducts": "duct_insulation", "grills, diffusers": "grille_diffuser",
  "installation of vav's": "vav_unit", "fire dampers, actuators, damper control panels": "fire_damper",
  "supply/installation of ahu / ahu dry run / acoustic insulation of ahu room": "ahu_unit",
  "precision air conditioner": "precision_ac",
  "cable trays for copper piping / copper piping works": "refnet_pipe",
  "drain piping works": "condensate_drain", "installation of vrf units": "fcu_unit",
  "modification of existing fire pipes/bulbs / erection of ms sprinkler pipes / enamel painting / flexible pipes": "sprinkler_pipe",
  "pendent, upright sprinkler bulbs": "sprinkler_head",
  "fa cabling ceiling+walls / multi sensor / heat detectors / ri / modules/mcp/strobes": "fa_device",
  "pa cabling / speakers": "pa_system",
  "acs and cctv (conduiting/cabling/devices)": "elv_device",
  "wld system": "wld_system", "rodent repelent system": "rodent_system",
  "gas based supression system": "gas_suppression", "vesda": "gas_suppression",
  "bms integration": "bms_integration", "av systems (cabling/delivery/installation)": "av_system",
  "white goods": "white_goods",
  "passive networking: cable laying / i-o port terminations": "data_drop",
  "active networking: fiber/backbone/racks/server room readiness": "network_rack",
  "modular workstation, meeting room tables: marking/frame/tabletop/alignment": "workstation",
  "routing of power, data cables & socket fixing in workstations": "ws_power_data",
  "modular cubicles (site measurement/delivery/installation)": "toilet_cubicle — AMBIGUOUS, could be WS cubicles; query on next Emirates contact",
  "water supply/drainage pipes+fittings+pumps": "cpvc_pipe", "bbc": "cpvc_pipe",
  "deep cleaning": "final_clean", "protection covering": "protection_covering",
  "fire extinguishers / fire exit signages / evacuation maps": "signage_evac",
  "bmc approvals / fire noc & mathadi": "statutory_liaison",
  // ---- DHL Chennai additions ----------------------------------------
  "site mobilization & barricading": "mobilisation", "aac block work": "blockwork",
  "installation of pelmet & sill": "joinery_panel — window-line joinery",
  "one side skinning": "board_one_face", "double side skinning": "board_close",
  "services containment in partition": "GATE g_wall — their words for in-wall services",
  "installation of plywood supports": "board_close prep — ply backing/noggins (code candidate on 2nd witness)",
  "roockwool placement": "insulation_partition",
  "paint base prepration": "putty_primer", "1st/2nd coat of paint": "paint_emulsion",
  "fire rated glass partition/doors": "glazing_partition + fire_door evidence — fire-rated GLAZING variant",
  "sliding folding frames/panels": "glazing_partition — operable wall, delivery-then-install",
  "installtion pf profiles/trims": "skirting",
  "raceway trenching / trench filling": "floor_raceway — TRENCHED method, two passes",
  "micro concrete": "self_leveling", "marble/granite works": "stone_marble",
  "metal mesh ceiling": "metal_ceiling", "acoustic baffle ceiling": "metal_ceiling — baffle variant",
  "gypsum cove": "ceiling_gypsum — cove detail", "vertical patta": "ceiling_gypsum trim",
  "ply support for lights fixtures": "ceiling_gypsum prep", "light marking / light cutting": "ceiling closure micro-steps",
  "on site carpentery": "joinery_panel", "cabin furnitures / meeting tables": "workstation family",
  "planter storage / low height storage": "storage_unit",
  "chairs delivery / installation": "workstation family — chairs as separate lead (KT: imported)",
  "frosted film": "blinds_film", "brand elements": "graphics_planters", "graphics/wall paper": "wallpaper",
  "db installation / db dressing / panel placement / terminations / panel charging": "db_panel lifecycle",
  "earthing / cable laying / main cable laying": "cable_pull", "tagging": "closeout micro-step",
  "supporting work & copper piping": "refnet_pipe", "chilled water pipe line work": "refnet_pipe — CHILLED WATER variant (not VRF)",
  "installation of idu/csu": "fcu_unit", "installation of odu": "odu_unit",
  "vcd installation / installation of dampers": "fire_damper", "canvas connection": "duct_gi flexible connector",
  "smoke test": "tc_hvac — smoke test granularity",
  "sprinkler headers / branch installation": "sprinkler_pipe — mains vs branch split",
  "flexible sprinkler": "sprinkler_pipe flexis (Emirates match)", "pressure testing": "GATE g_sprk_test",
  "line charging / butterfly value / rosette plate / removal of sprinkler cap": "sprinkler lifecycle tail",
  "fa wiring / fixtures above+below ceiling / panel / integration": "fa_device lifecycle",
  "cable pulling / i-o punching user+rack end / jack panel / patch cord / poe switch / penta scanning": "data_drop + network_rack lifecycle (Pentascanner certification)",
  "critical rooms (ele/hub/server/ups/battery)": "critical-room mini-project — 2nd witness with Emirates",
  "handover to it": "zone-level interim handover MILESTONE (hub room releases IT) — concept candidate",
  "ups and battery bank delivery/placement/installation/terminations": "ups_battery lifecycle",
  "installation of rodent": "rodent_system", "installation of wld/vesda": "wld_system + gas_suppression",
  "waste/fresh/drain pipe laying": "cpvc_pipe", "testing of the plumbing pipes": "GATE g_pipe_test",
  "ponding test": "GATE g_waterproof — EXPLICIT 2d task", "protection plaster": "membrane protection screed",
  "exhaust fan installation": "toilet_exhaust", "vanity counter": "joinery_panel",
  "sanitary fixtures / fittings split": "sanitary_fixture", "test run": "tc_plumbing",
  "deep cleaning": "final_clean", "client walkthrough": "snag_cycle milestone", "sign off on hoto": "handover_file",
  // ---- Firstsource additions ------------------------------------------
  "lineout checking & approval": "lineout gate — explicit 1d approval event (3rd witness)",
  "order closer and supply of metal fire doors": "fire_door — order-to-site 18-24d on a blitz (vs Emirates 10wk)",
  "marking & chipping for conduiting": "conduit — chase cutting pass",
  "chipping for raceways": "floor_raceway — trench/chase pass (DHL match)",
  "installation of industrial switch and sockets": "wiring_point — industrial-grade variant (critical rooms)",
  "low side works / order closer & supply of high side equipment": "duct_gi + hvac_equip package procurement",
  "wooden flooring installation": "vinyl_lvt — engineered wood variant",
  "acoustic installation": "fluted_panel",
  "on-site furniture work (reception table, pelemet, sill)": "joinery_panel (3rd witness for pelmet/sill)",
  "kitchen plumbing supply/installation/t&c": "cpvc_pipe kitchen leg",
  "kitchen exhaust supply/installation/t&c": "kitchen_hood + toilet_exhaust family",
  "kitchen equipment supply/installation/t&c": "kitchen equipment — rides joinery/sanitary proxies until BOQ",
  "kitchen fire suppression system": "gas_suppression — kitchen (Ansul) variant, 2nd suppression witness",
  "fas works cabling / pa works cabling": "fa_device + pa_system",
  "sliding folding parttion": "glazing_partition — operable wall (3rd witness)",
  "weightage": "section progress weights — earned-value structure (concept candidate)",
  // ---- LightStorm + Malpani additions ---------------------------------
  "second quality tiles": "self_leveling — cheap tiles as a leveling layer (LS practice)",
  "grass carpet": "carpet_tile — breakout/cafeteria variant",
  "trap doors / vision panel doors": "door_install variants (server/AHU/pantry rooms)",
  "mcb hooter": "fa_device sounder", "testing and feruling / crimping / input cabling": "data_drop certification steps",
  "kota stone laying": "stone_marble — kitchen flooring variant", "brick bat coba / bbc": "waterproofing protection screed",
  "sofa fabrics": "sample approval — soft furnishing", "corner guard order": "skirting family",
  "glasswool": "insulation_partition", "ply backing": "plywood_backing",
  "channel with silicon strips": "glazing_partition frames", "glass measurement": "glazing site-measure step",
  "second quality tiles for leveling": "self_leveling", "designer panelling (frames/ply/mdf/laminate/finish)": "joinery_panel lifecycle",
  "urinal partition": "toilet_cubicle family", "d.b panel storage / janitor storage / overhead storage": "storage_unit variants",
  "supply of graphics / inst of graphics": "wallpaper + graphics_planters", "rug order/supply/installation": "carpet_tile — rug variant, FF to furniture",
  "glass boards": "lacquered_glass — writing boards, order+30d", "logo": "graphics_planters branding",
  // ---- TCS Noida (campus-grade) ----------------------------------------
  "centralised ro plant": "cpvc_pipe family — water treatment (code candidate on 2nd witness)",
  "solar water heater": "cpvc_pipe family — kitchen hot water (candidate on 2nd witness)",
  "security flap barriers / food scanner / baggage scanner": "elv_device family — campus security, supply+install",
  "gym/games equipments": "white_goods family — FF&E",
  "sports vinyl flooring": "vinyl_lvt — sports variant", "external signage": "graphics_planters — exterior",
  "sample mockup room finishes": "samples_mockups — full MOCKUP ROOM deliverable",
  "curved partition (ivc room)": "glazing_partition — curved (LS match)",
  // ---- BFIL / Pivox / Addverb additions --------------------------------
  "release of loe": "kick-off milestone", "pop plastering": "pop_punning", "gypsum plastering": "plaster",
  "anti-static vinyl": "vinyl_lvt — ESD variant (supplied w/ NO install task in BFIL — query class)",
  "inline fans": "toilet_exhaust", "auto sequential panels": "db_panel — auto-sequence variant (code candidate)",
  "fa loop cards / fapa cables": "fa_device + pa_system", "ahu plenum": "ahu_unit",
  "hdmi & vga / tv units / projector & screen": "av_system", "tds submission": "pkg_submittal",
  "stretch fabric": "AMBIGUOUS — stretch_ceiling vs fabric wall (query)",
  "site conditioning and cleaning": "mobilisation", "carpentary td's": "pkg_design — carpentry shop drawings",
  "puffy seating": "joinery_panel — soft seating", "ply boxing": "plywood_backing",
  "construction day (0d)": "day-zero milestone concept", "material approval list": "samples_mockups",
  "rafters": "joinery_panel — ceiling rafters", "modular beds / bunk bed / wooden bed": "DORM FURNITURE — code candidate (Addverb: office+dorm class)",
  "fabric cladding": "fluted_panel family", "bonding of glass at site": "glazing_partition micro-step",
  "suspenders for modular grid": "ceiling_grid_tile micro-step", "tile chess flooring / chess set / umbrella": "terrace recreation FF&E",
  "curtains": "blinds_film — curtain variant", "phenolic cubicles": "toilet_cubicle material variant",
  "bbc (in plumbing section)": "dual-mapped: waterproofing protection vs cpvc — CONFIRM per project (query)",
};

// ---- per-code duration evidence (elapsed days; qty unknown — bands, not rates)
const EVIDENCE = {
  waterproofing:      [{ plan: "tcs", dur: 8, actual: "Completed; BBC 7d after — 5th witness of membrane->protection" }, { plan: "ls", dur: 4, note: "1st coat <- plaster + plumbing order FS+7" }, { plan: "dhl", dur: 10, actual: "ran -13 EARLY; ponding 2 + protection plaster 2 explicit" }, { plan: "emirates", dur: 4,  actual: "started on time" }],
  pest_control:       [{ plan: "firstsource", dur: 3, actual: "COMPLETED on plan" }, { plan: "dhl", dur: 15, actual: "started -7 early" }, { plan: "emirates", dur: 1,  actual: "done on plan day" }],
  self_leveling:      [{ plan: "tcs", dur: 23, note: "PCC/SL FIRST, before lineout — 2nd witness for slab-first" }, { plan: "dhl", dur: 17, note: "SL 7 + micro concrete 10" }, { plan: "emirates", dur: 7,  note: "+PCC 10d +modifoam 7d as separate passes" }],
  blockwork:          [{ plan: "tcs", dur: 18, actual: "Completed" }, { plan: "ls", dur: 10, note: "material supply FS-1 overlap; lintel SS+2" }, { plan: "firstsource", dur: 6, actual: "DELAYED on blitz", note: "4-7d bands" }, { plan: "dhl", dur: 15, actual: "done in 8 — finished -7 early (AAC)" }, { plan: "emirates", dur: 5 }],
  plaster:            [{ plan: "ls", dur: 7 }, { plan: "firstsource", dur: 6, actual: "DELAYED" }, { plan: "dhl", dur: 18, actual: "started -2 early, on time" }, { plan: "emirates", dur: 5, note: "+POP punning 6d" }],
  gi_stud_frame:      [{ plan: "ls", dur: 5, note: "LOGIC: <- partition layout #5 + civil order FS+7" }, { plan: "firstsource", dur: 7, actual: "COMPLETED" }, { plan: "dhl", dur: 15, actual: "+6d end delay" }, { plan: "emirates", dur: 12 }],
  board_one_face:     [{ plan: "ls", dur: 4 }, { plan: "firstsource", dur: 5, actual: "COMPLETED" }, { plan: "dhl", dur: 11, actual: "+12d end delay — partition chain slipped ~1wk" }, { plan: "emirates", dur: 9 }],
  insulation_partition:[{ plan: "ls", dur: 4, note: "glasswool AFTER first side — their logic" }, { plan: "firstsource", dur: 4, actual: "in progress" }, { plan: "dhl", dur: 7, actual: "rockwool, -1" }, { plan: "emirates", dur: 5 }],
  board_close:        [{ plan: "tcs", dur: 7, note: "clearance 3d + insulation 15d between skins — g_wall 6th witness" }, { plan: "ls", dur: 4, note: "LOGIC: <- ply backing AND <- wall conduits #86 — g_wall 5th witness" }, { plan: "firstsource", dur: 5, note: "after 4d Clearance from Services — g_wall 4th witness" }, { plan: "dhl", dur: 10, actual: "20% WIP, started -2 early" }, { plan: "emirates", dur: 10, note: "g_wall lived as 'Clearance from Services' — a 3-DAY window, not instant" }],
  glazing_partition:  [{ plan: "tcs", dur: 24, actual: "glass delivery 10 + frames 6 + glass 7; CURVED partition (IVC) Delayed; sliding folding Completed" }, { plan: "ls", dur: 13, note: "MEASUREMENT 1d <- both partitions closed -> delivery 7d -> channel+silicon 2d -> fixed glass 3d — site-measure law explicit" }, { plan: "firstsource", dur: 20, note: "glass delivery 7 + frames 6 + glass 7; sliding folding 7" }, { plan: "dhl", dur: 30, note: "frames 7 + glass 5 + doors 6 + fire-rated 5+7 + sliding folding" }, { plan: "emirates", dur: 40, note: "glass DELIVERY 20d + frames 10d + glass 15d + curved 15d — delivery leg explicit" }],
  door_install:       [{ plan: "ls", dur: 17, note: "4 door types; hardware <- dado(160)/putty(241)/ceiling(136) BY TYPE; flush doors supply <- order FS+7" }, { plan: "firstsource", dur: 5 }, { plan: "emirates", dur: 7 }],
  fire_door:          [{ plan: "tcs", dur: 5, actual: "fire-rated metal+glazed DELAYED — supply again" }, { plan: "firstsource", dur: 22, note: "Order closer and Supply 18-24d + install 4-5d — blitz lead ~4-5wk vs Emirates 10wk: lead band 4-10wk" }, { plan: "dhl", dur: 2, note: "critical rooms — 2nd witness" }, { plan: "emirates", dur: 15, note: "order 15 Nov, delivery 1 Jan, install to 22 Jan — ~10wk order-to-done" }],
  raised_floor:       [{ plan: "tcs", dur: 16, actual: "marking/pedestals/tiles Completed, cutouts/alignment Not Started at cut" }, { plan: "ls", dur: 6, note: "studs 3 + tiles 6 <- floor conduits" }, { plan: "firstsource", dur: 21, actual: "marking+pedestals COMPLETED, tiles in progress", note: "critical rooms; lifecycle marking 2/pedestals 4/tiles 4/cutouts 2/alignment 1" }, { plan: "dhl", dur: 5 }, { plan: "emirates", dur: 24, note: "delivery 2d, marking 3, pedestals 5, tiles 7, cutouts 4, alignment 5" }],
  tile_vitrified:     [{ plan: "ls", dur: 5, note: "<- BBC FS+1" }, { plan: "firstsource", dur: 10, note: "vitrified/stone one line" }, { plan: "dhl", dur: 10 }, { plan: "emirates", dur: 25 }],
  stone_marble:       [{ plan: "ls", dur: 6, note: "granite platform: supply -> CUTTING 4d -> install <- dado" }, { plan: "dhl", dur: 10 }, { plan: "emirates", dur: 30, note: "marble 20d + stone 10d" }],
  carpet_tile:        [{ plan: "ls", dur: 6, note: "install <- 2nd-coat ceiling paint + FINAL wall coat — paint fully done before soft floors, their logic" }, { plan: "firstsource", dur: 7 }, { plan: "dhl", dur: 7 }, { plan: "emirates", dur: 15, note: "25 Jan-8 Feb, AFTER paint — dust rule confirmed" }],
  epoxy_flooring:     [{ plan: "emirates", dur: 17, note: "epoxy 7d + engineered concrete 10d, late-stage" }],
  wall_dado:          [{ plan: "tcs", dur: 14, actual: "Delayed — 3rd witness" }, { plan: "ls", dur: 5, note: "dado fixing = hub cited 9x (platform, cubicles, urinals, accessories all reference it)" }, { plan: "emirates", dur: 14 }],
  ceiling_gypsum:     [{ plan: "ls", dur: 42, note: "4 ceiling types; closing <- ceiling conduits + wiring + FA-test FS-2 + HVAC-comm FS-2 — g_ceiling in THEIR logic" }, { plan: "firstsource", dur: 18, note: "framing 7 + clearance 6 + boarding 5" }, { plan: "dhl", dur: 23, note: "framing 10 + closure 13 + cove 10 + ply supports + light marking/cutting" }, { plan: "emirates", dur: 25, note: "GI framing 10 + boarding/jointing 15; ceiling PAINTED after (42d cycle) — ceilPaint confirmed" }],
  ceiling_grid_tile:  [{ plan: "tcs", dur: 24, actual: "delivery 6 + framing 15 + tiles 8, Completed" }, { plan: "firstsource", dur: 32, note: "delivery 5-6 + framing 7-10 + CLEARANCE FROM SERVICES 15-17(!) + tiles 4-6 — the sign-off window dominates a blitz" }, { plan: "dhl", dur: 20, note: "framing 10 + closure 10" }, { plan: "emirates", dur: 28, note: "delivery 4d + framing 10d + tiles 7d; technogrid variant 19d" }],
  stretch_ceiling:    [{ plan: "emirates", dur: 61, note: "ply framing 10d, material delivery lands ~6wk later, install 5d — LONG lead, short install" }],
  metal_ceiling:      [{ plan: "tcs", dur: 7, actual: "cafeteria/metal/designer ALL Delayed — 4th witness of the family" }, { plan: "firstsource", dur: 21, note: "cafeteria decorative 7 + metal fabricated 7 + designer 7 — 3rd witness" }, { plan: "dhl", dur: 30, note: "metal mesh 18 + acoustic baffles 12 — 2nd witness" }, { plan: "emirates", dur: 20, note: "cafeteria decorative 20d / metal fabricated 15d / designer 15d" }],
  putty_primer:       [{ plan: "ls", dur: 6, note: "walls: putty <- wall conduits FS+1 — putty only after in-wall closes" }, { plan: "firstsource", dur: 9, note: "walls 5+5, ceiling 8+5 separate cycles" }, { plan: "dhl", dur: 10, actual: "started -43 EARLY — opportunistic pull-forward" }, { plan: "emirates", dur: 20, note: "putty 10 + primer/sanding 10, per paint system" }],
  paint_emulsion:     [{ plan: "tcs", dur: 32, actual: "walls Completed; ceiling 2nd&3rd WIP; epoxy paint Completed" }, { plan: "ls", dur: 19, note: "WALLS 5-COAT: putty->primer->1st->2nd->FINAL (7d); ceiling 4-coat; flooring waits FINAL coat" }, { plan: "firstsource", dur: 9, note: "walls 1st 4 + 2nd 5; ceiling 6+4; NOTE their sheet has 2nd coat BEFORE 1st (source error)" }, { plan: "dhl", dur: 47, note: "1st coat 17 + 2nd coat 30 (window-style spread)" }, { plan: "emirates", dur: 22, note: "1st coat 12 + 2nd&3rd 10; walls before ceiling tiles — confirmed" }],
  texture_paint:      [{ plan: "emirates", dur: 42, note: "epoxy/metallic/stucco each run a FULL 42d putty->coats cycle" }],
  wallpaper:          [{ plan: "tcs", dur: 5, actual: "base prep WIP — 5th witness" }, { plan: "ls", dur: 6, note: "graphics <- 1st coat paint" }, { plan: "firstsource", dur: 7, note: "base prep 4 + install 3 — 3rd witness" }, { plan: "dhl", dur: 7, note: "2nd witness, branding block" }, { plan: "emirates", dur: 15, note: "base prep 7d weeks earlier, install 26 Jan-9 Feb after paint" }],
  lacquered_glass:    [{ plan: "tcs", dur: 14, actual: "WIP — 4th witness" }, { plan: "firstsource", dur: 7, note: "3rd witness" }, { plan: "emirates", dur: 20 }],
  blinds_film:        [{ plan: "ls", dur: 6, note: "blinds <- 2nd coat; film <- ALL glass installed (114,109,119)" }, { plan: "firstsource", dur: 14, note: "blinds 7 + glass film 7" }, { plan: "dhl", dur: 7, note: "frosted film in the 14-21 Aug branding block" }, { plan: "emirates", dur: 10, note: "blinds 7d + film 10d, both after paint — phase 93 confirmed" }],
  fluted_panel:       [{ plan: "ls", dur: 5, note: "acoustic panelling <- carpentry order FS+7 + partitions closed" }, { plan: "firstsource", dur: 7, note: "Acoustic Installation" }, { plan: "emirates", dur: 14 }],
  skirting:           [{ plan: "ls", dur: 4, note: "modular skirting + transition profile install LAST (Oct 9-12) after ALL floors" }, { plan: "firstsource", dur: 11, note: "skirting 6 + transition profiles 5" }, { plan: "dhl", dur: 15, note: "skirting 5 + profiles/trims 10" }, { plan: "emirates", dur: 10, note: "+corner guards 7d + transition profiles 4d" }],
  joinery_panel:      [{ plan: "ls", dur: 20, note: "on-site: reception table 10, storages 10-12, pelmet 8, shelves 8, branding 20; designer panelling: frames 6 -> ply cladding 4 -> MDF+laminate 4 -> finishing 2" }, { plan: "firstsource", dur: 45, actual: "DELAYED", note: "on-site furniture: reception table + pelmet + sill" }, { plan: "dhl", dur: 60, actual: "on-site carpentry 60d window, 20% at snapshot; + vanity 7 + pelmet/sill 25" }, { plan: "emirates", dur: 30, note: "bespoke tables (reception/CCM/boardroom) 30d EACH; built-in furniture 40d — joinery is a long-lead trade" }],
  conduit:            [{ plan: "tcs", dur: 37, actual: "Completed incl. closed-room marking 6d" }, { plan: "ls", dur: 19, note: "floor 10 -> ceiling 8 SS+5 -> walls 8 SS (walls also <- blockwork + one-side skin)" }, { plan: "firstsource", dur: 17, actual: "marking/chipping + conduiting COMPLETED in critical rooms; main floor in progress", note: "incl. chase chipping" }, { plan: "dhl", dur: 30, actual: "60% at snapshot, on time" }, { plan: "emirates", dur: 10, note: "+back boxes 7d; conduit marking 5d in closed partitions BEFORE close" }],
  circuit_wiring:     [{ plan: "ls", dur: 8, note: "SS with wall conduits" }, { plan: "firstsource", dur: 12, actual: "light+power circuits in progress" }, { plan: "dhl", dur: 20 }, { plan: "emirates", dur: 12 }],
  floor_raceway:      [{ plan: "tcs", dur: 47, actual: "marking 6 + CHIPPING 13 + supports 10 + install 10 + boxes 6, Completed — 3rd trench witness" }, { plan: "firstsource", dur: 21, actual: "marking+chipping+install COMPLETED", note: "chipping pass = DHL trench match" }, { plan: "dhl", dur: 16, note: "TRENCHED method: trenching 8 + filling 8; trenching ran +17 over" }, { plan: "emirates", dur: 23, note: "marking 6 + supports 7 + install 10 — raceway is 3 passes" }],
  cable_pull:         [{ plan: "tcs", dur: 47, actual: "tray marking/supports/install Completed; power+earthing cabling Not Started at cut" }, { plan: "firstsource", dur: 27, note: "tray 10 + power 7 + earthing 4" }, { plan: "dhl", dur: 43, note: "tray 15 + cable 15 + earthing 10 + main cable 3; tray only 10% at snapshot (+3)" }, { plan: "emirates", dur: 32, note: "tray 14d + power cabling 15 + earthing 10 + dressing 7" }],
  db_panel:           [{ plan: "tcs", dur: 17, actual: "DBs Completed, dressing WIP, LT Not Started" }, { plan: "ls", dur: 5, note: "DB+MCB install <- ALL conduits floor/ceiling/wall + wiring" }, { plan: "firstsource", dur: 18, note: "DB 7 + dressing 4 + LT 4 + panel T&C 5" }, { plan: "dhl", dur: 35, note: "DB 12 + dressing 10 + panel placement 4 + terminations 5 + charging 5" }, { plan: "emirates", dur: 45, note: "DBs 7+5; LT panels delivery 25 Dec->T&C 11 Jan — 6wk lead confirmed" }],
  ups_battery:        [{ plan: "tcs", dur: 17, actual: "supply WIP — 5th witness" }, { plan: "firstsource", dur: 15, note: "supply 3 + install 8 + T&C 4 — 3rd witness" }, { plan: "dhl", dur: 17, note: "delivery 7 + battery placement 4 + UPS 2 + terminations 4 — 2nd witness" }, { plan: "emirates", dur: 49, note: "battery supply Dec, UPS supply Jan, install+T&C to 26 Jan" }],
  wiring_point:       [{ plan: "ls", dur: 2, note: "wall switches <- DB; furniture switches <- MODULAR FURNITURE — ws_power_data law again" }, { plan: "firstsource", dur: 3, note: "+ industrial sockets 4d in critical rooms" }, { plan: "dhl", dur: 55, note: "switch sockets spread across 55d window — window, not effort" }, { plan: "emirates", dur: 7, note: "switches/sockets 5-11 Feb — near handover, phase 90 confirmed" }],
  light_fixture:      [{ plan: "tcs", dur: 7, actual: "recessed+suspended WIP, decorative Not Started" }, { plan: "ls", dur: 5, note: "<- ceiling finishing all types + supply <- lights order FS+7" }, { plan: "firstsource", dur: 3 }, { plan: "dhl", dur: 15 }, { plan: "emirates", dur: 10, note: "recessed 10 / suspended 7 / decorative 5 + T&C 3" }],
  duct_gi:            [{ plan: "tcs", dur: 10, note: "insulation 18-28 Jan BEFORE install 21-31 Jan — PRE-INSULATE, re-ties the method 2-2" }, { plan: "firstsource", dur: 11, note: "marking 4 + installation 7 (line 159 typo reads insulation) — WRAP order, tie-break witness" }, { plan: "dhl", dur: 25, actual: "pulled -15 EARLY; canvas connections 10" }, { plan: "emirates", dur: 14, note: "marking+supports 4 + install 10" }],
  duct_insulation:    [{ plan: "firstsource", dur: 5, note: "AFTER duct install -> 2-1 for wrap-after-hang; grilles follow" }, { plan: "dhl", dur: 10, actual: "ran BEFORE hanging (pre-insulated on ground) — see VERDICTS.contradictions" }, { plan: "emirates", dur: 10 }],
  grille_diffuser:    [{ plan: "firstsource", dur: 8 }, { plan: "dhl", dur: 15 }, { plan: "emirates", dur: 7 }],
  vav_unit:           [{ plan: "tcs", dur: 4, actual: "Delayed on AHU — 2nd witness" }, { plan: "emirates", dur: 5 }],
  fire_damper:        [{ plan: "firstsource", dur: 13, note: "dampers 6 + control panels 7" }, { plan: "dhl", dur: 25, note: "VCD 15 + dampers 10" }, { plan: "emirates", dur: 17, note: "dampers+actuators 10 + control panels 7" }],
  ahu_unit:           [{ plan: "tcs", dur: 30, actual: "supply 30d Completed mid-job; install/dampers/acoustic/dry-run Delayed behind it — Emirates match" }, { plan: "firstsource", dur: 4, note: "dry run only — base building AHU" }, { plan: "emirates", dur: 50, note: "supply 30d + install 10 + acoustic room insulation 7 + dry run 3" }],
  precision_ac:       [{ plan: "tcs", dur: 18, actual: "supply Delayed — 3rd witness" }, { plan: "emirates", dur: 25, note: "supply 15 + install 10, server room" }],
  refnet_pipe:        [{ plan: "tcs", dur: 13, actual: "trays 4 + copper 9 Completed — 4th witness" }, { plan: "ls", dur: 4, note: "copper piping & drainage <- supply FS+7 from low-side order" }, { plan: "dhl", dur: 30, note: "copper 10 + CHILLED WATER lines 20 — 2nd witness" }, { plan: "emirates", dur: 17, note: "trays for copper 7 + copper piping 10 — REFNET CONFIRMED as real site work" }],
  condensate_drain:   [{ plan: "tcs", dur: 4, actual: "Delayed — 5th witness" }, { plan: "malpani", dur: 4, note: "drain piping + insulation of copper&drain — 4th witness" }, { plan: "emirates", dur: 7, note: "'Drain Piping works' separate task — panel D5 addition VALIDATED" }],
  fcu_unit:           [{ plan: "ls", dur: 7, note: "IDU <- copper + supply (order+20d)" }, { plan: "dhl", dur: 5, actual: "IDU/CSU pulled -27 EARLY — equipment landed ahead" }, { plan: "emirates", dur: 4, note: "VRF units install" }],
  sprinkler_pipe:     [{ plan: "tcs", dur: 50, actual: "REFURB: mods of existing pipes+bulbs + new MS 10d + enamel 7 + flexis 10, Completed — refurb 2nd witness" }, { plan: "firstsource", dur: 35, note: "marking 6 + MS pipes 15 + enamel 7 + flexis 7 — 3rd witness lifecycle" }, { plan: "dhl", dur: 50, note: "headers 25 ∥ branch 25 + connection 3 + flexis 10 + tail (drain/valve/charging/caps/rosettes) ~13" }, { plan: "emirates", dur: 46, note: "REFURB pattern: modify existing pipes 10 + bulbs 5 + new MS pipes 10 + enamel paint 10 + flexis 7 (Kohler FLSS = same pattern)" }],
  sprinkler_head:     [{ plan: "firstsource", dur: 5 }, { plan: "dhl", dur: 15 }, { plan: "emirates", dur: 7 }],
  fa_device:          [{ plan: "tcs", dur: 45, actual: "cabling Completed; devices Not Started at cut — 5th witness of lifecycle" }, { plan: "ls", dur: 27, note: "conduiting 10 -> cabling 6 -> smoke detectors 5 -> MCB hooter 4 -> panel 4 -> testing 4; ceiling closes FS-2 vs test end" }, { plan: "firstsource", dur: 24, note: "cabling 10 + sensors 7 + heat 2 + RI 3 + MCP 2 — identical lifecycle names to Emirates" }, { plan: "dhl", dur: 62, note: "wiring 20 + above-ceiling 15 + below-ceiling 15 + panel 4 + integration 7; T&C 8" }, { plan: "emirates", dur: 79, note: "cabling 20+9, multi-sensor 14, heat 7, RI 7, MCP/strobes 7, T&C 15d(!) — FA commissioning is LONG on full systems" }],
  pa_system:          [{ plan: "tcs", dur: 45, actual: "cabling+speakers Completed — 4th witness" }, { plan: "firstsource", dur: 26, note: "cabling 15 + speakers 7 + T&C 4 — 3rd witness" }, { plan: "emirates", dur: 31, note: "cabling 20 + speakers 7 + T&C 4" }],
  elv_device:         [{ plan: "tcs", dur: 22, actual: "ACS/CCTV raceway Completed, rest Not Started; + security flap barriers/food scanner/baggage scanner supply->install chains (campus class)" }, { plan: "ls", dur: 6, note: "CCTV cabling SS with conduits" }, { plan: "firstsource", dur: 26, note: "ACS/CCTV: raceway 4 + cabling 7 + devices 10 + T&C 5" }, { plan: "dhl", dur: 55, note: "ACS/CCTV/WIFI full chain; control-end SCOPE NOT CONFIRMED = their live query" }, { plan: "emirates", dur: 31, note: "ACS+CCTV: raceway 10 + cabling 10 + devices 7 + T&C 4" }],
  wld_system:         [{ plan: "tcs", dur: 28, actual: "WIP — 4th witness" }, { plan: "firstsource", dur: 20, note: "3rd witness" }, { plan: "dhl", dur: 7, note: "WLD/VESDA one line — 2nd witness" }, { plan: "emirates", dur: 36 }],
  rodent_system:      [{ plan: "tcs", dur: 23, actual: "Delayed — 4th witness" }, { plan: "firstsource", dur: 22, note: "3rd witness" }, { plan: "dhl", dur: 7, note: "2nd witness" }, { plan: "emirates", dur: 31 }],
  gas_suppression:    [{ plan: "tcs", dur: 13, actual: "kitchen Ansul supply WIP — 3rd witness" }, { plan: "malpani", dur: 12, note: "kitchen Ansul 12d — 2nd kitchen-suppression witness" }, { plan: "firstsource", dur: 6, note: "KITCHEN fire suppression (Ansul) supply 2 + install 5 + T&C 2 — 2nd suppression witness" }, { plan: "emirates", dur: 34, note: "+VESDA parallel — server-room fire class" }],
  bms_integration:    [{ plan: "emirates", dur: 15 }],
  av_system:          [{ plan: "emirates", dur: 20, note: "cabling 10 + delivery 5 + install 5 — LAST system on site (to 20 Feb)" }],
  white_goods:        [{ plan: "tcs", dur: 12, actual: "supply Delayed — 3rd witness" }, { plan: "malpani", dur: 7, note: "2nd witness, final week" }, { plan: "emirates", dur: 9 }],
  data_drop:          [{ plan: "tcs", dur: 44, actual: "cable laying Delayed, I/O Not Started — 3rd witness" }, { plan: "ls", dur: 25, note: "conduiting -> cabling -> testing&FERULING -> crimping -> input cabling -> testing (certification steps)" }, { plan: "dhl", dur: 41, note: "pulling 25 + I/O punching 9+7 (2nd witness) + patch cords 2" }, { plan: "emirates", dur: 40, note: "passive: cable laying 30d + I/O terminations 10d at the end" }],
  network_rack:       [{ plan: "tcs", dur: 28, actual: "fiber/backbone/racks supplies ALL Delayed — supply-driven again" }, { plan: "dhl", dur: 11, note: "jack panels 5 + POE 2+2 + penta scanning 2 — certification step" }, { plan: "emirates", dur: 35, note: "fiber 15 + backbone 10 + racks 10 + server-room readiness 5 + install 7 + T&C 3" }],
  workstation:        [{ plan: "tcs", dur: 44, actual: "marking Completed 2 Feb; frames waited to 9 Mar (floors); ws_power_data routing WIP — 5th witness of his catch" }, { plan: "ls", dur: 6, note: "install <- carpet; chairs FF furniture; supply +15-20d after orders" }, { plan: "firstsource", dur: 17, note: "marking 2 + frames 10 + tabletop 5 + alignment 2" }, { plan: "dhl", dur: 25, note: "modular WS 10 + cabin 7 + meeting tables 8" }, { plan: "emirates", dur: 41, note: "marking 4 + frames 25 + tabletop/panels 10 + alignment 2" }],
  ws_power_data:      [{ plan: "tcs", dur: 5, actual: "WIP — 5th witness, identical task text" }, { plan: "firstsource", dur: 8, note: "IDENTICAL task text to Emirates — 3rd witness of his catch" }, { plan: "emirates", dur: 15, note: "routing power/data INSIDE workstations as own task — HIS CATCH CONFIRMED by Emirates" }],
  toilet_cubicle:     [{ plan: "ls", dur: 5, note: "urinal partition separate 2d" }, { plan: "dhl", dur: 10 }, { plan: "emirates", dur: 26, note: "site measurement 3 + delivery 3 + install 20" }],
  cpvc_pipe:          [{ plan: "tcs", dur: 36, actual: "supply+drainage+testing Completed; RO PLANT + SOLAR HEATER as separate supply->install->T&C chains" }, { plan: "ls", dur: 5, note: "laying <- waterproofing 1st coat; LEAKAGE TESTING 4d -> BBC 5d — g_pipe_test 3rd witness" }, { plan: "firstsource", dur: 12, note: "kitchen plumbing supply 2 + install 8 + T&C 2" }, { plan: "dhl", dur: 27, note: "waste 7 + fresh 10 + drain 10; testing 5 + main connection 3" }, { plan: "emirates", dur: 36, note: "supply 13d + drainage 36d incl pumps 7d + fixtures 10 + T&C 2" }],
  sanitary_fixture:   [{ plan: "tcs", dur: 5, actual: "Delayed (free-issue class risk)" }, { plan: "ls", dur: 5, note: "<- dado fixing + delivery" }, { plan: "firstsource", dur: 10, note: "fittings 6 + fixtures 4" }, { plan: "dhl", dur: 18, note: "fixtures 5 + fittings 13 split" }, { plan: "emirates", dur: 10 }],
  temporary_lighting: [{ plan: "firstsource", dur: 2, actual: "COMPLETED day 1-3" }, { plan: "emirates", dur: 5, actual: "done exactly to plan 30 Sep-4 Oct" }],
  protection_covering:[{ plan: "emirates", dur: 110, note: "umbrella task spanning Oct-Feb — protection is continuous, not an event" }],
  final_clean:        [{ plan: "tcs", dur: 6, actual: "WIP in final week" }, { plan: "ls", dur: 2, note: "deep cleaning <- logo (the last install)" }, { plan: "firstsource", dur: 7, note: "two deep cleans: critical rooms 2d + main 7d" }, { plan: "dhl", dur: 9, note: "deep cleaning before walkthrough" }, { plan: "emirates", dur: 5, note: "'Deep Cleaning' last 5 days" }],
  signage_evac:       [{ plan: "firstsource", dur: 4, note: "extinguishers 1 + exit signage 1 + evac maps 2; their sheet dates END before START (source error x2)" }, { plan: "emirates", dur: 4, note: "extinguishers 3 + exit signage 4 + evac maps 4, final week" }],
  statutory_liaison:  [{ plan: "malpani", dur: 0, note: "NONE on this 60d private blitz — statutory is client-side here" }, { plan: "emirates", dur: 86, actual: "Fire NOC + Mathadi (Mumbai) finished ON DAY 20 Sep; BMC 15d — statutory ran from day 1, PRE-construction" }],
  mobilisation:       [{ plan: "firstsource", dur: 5, note: "blitz — vendor mobilisation" }, { plan: "dhl", dur: 12, actual: "on time — incl. barricading (occupied building)" }, { plan: "emirates", dur: 7 }],
  tc_plumbing:        [{ plan: "dhl", dur: 2, note: "washroom test run" }, { plan: "emirates", dur: 2 }],
  tc_hvac:            [{ plan: "ls", dur: 2, note: "commissioning <- ODU" }, { plan: "dhl", dur: 22, note: "smoke test 15 + dry run 2 + T&C 5" }, { plan: "emirates", dur: 6, note: "HVAC T&C 3 + AHU dry run 3" }],
  tc_electrical:      [{ plan: "dhl", dur: 10, note: "tagging 7 + T&C 3" }, { plan: "emirates", dur: 3 }],
  tc_fire:            [{ plan: "firstsource", dur: 6, note: "sprinkler T&C 3 + FA T&C 3 — small refurb-scale, matches Kohler sizing" }, { plan: "emirates", dur: 18, note: "sprinkler T&C 3 + FA T&C 15 — full-system FA commissioning dominates" }],
  tc_elv:             [{ plan: "emirates", dur: 13, note: "PA 4 + ACS/CCTV 4 + WLD 2 + networking 3" }],
  lineout_marking: [{ plan: "tcs", dur: 6, actual: "marking 5 + approval 1, Completed — 5th witness" }, { plan: "malpani", dur: 5, note: "marking 3 + checking&approval 2 — 4th witness; PCC BEFORE lineout here (site condition)" }, { plan: "firstsource", dur: 3, actual: "marking 2 + approval 1, both COMPLETED on plan — 3rd witness" }, { plan: "dhl", dur: 9, actual: "done in 5 — finished -5 early" }],
  pop_punning: [{ plan: "tcs", dur: 15, actual: "Completed — 4th witness" }, { plan: "ls", dur: 8, note: "<- paint order + blockwork" }, { plan: "firstsource", dur: 7, actual: "DELAYED — 3rd witness" }, { plan: "dhl", dur: 30, actual: "85% at snapshot" }],
  storage_unit: [{ plan: "firstsource", dur: 3, note: "lockers in handover phase" }, { plan: "dhl", dur: 10, note: "planter storage 5 + low-height 5" }],
  graphics_planters: [{ plan: "ls", dur: 12, note: "planters/rug/signage/logo/canvas ALL FF-linked to furniture install — decoratives choreographed to furniture finish" }, { plan: "firstsource", dur: 7, note: "signage supply+install in handover" }, { plan: "dhl", dur: 7, note: "signage + brand elements + planters, one week" }],
  odu_unit: [{ plan: "ls", dur: 6, note: "ODU AFTER IDU in their logic (255<-254); supply order+20d domestic" }, { plan: "dhl", dur: 5, actual: "pulled -30 EARLY; Kohler KT flags ODU lead 8-10wk CRITICAL" }],
  toilet_exhaust: [{ plan: "ls", dur: 4, note: "washroom ventilation <- HVAC material supply — 4th witness" }, { plan: "dhl", dur: 2, note: "2nd witness; + fresh-air ducting 6" }],
  fm_training: [{ plan: "dhl", dur: 5, note: "training & demonstration" }],
  handover_file: [{ plan: "ls", dur: 1, note: "operational handover 1d" }, { plan: "dhl", dur: 1, note: "HOTO sign-off after client walkthrough" }],
  snag_cycle: [{ plan: "tcs", dur: 15, note: "Snag Resolution 15d AFTER primary completion (21 Mar -> 5 Apr) — snag window structure; carries the YEAR TYPO (2023)" }, { plan: "dhl", dur: 1, note: "client walkthrough as the snag trigger" }],
  kitchen_hood: [{ plan: "tcs", dur: 13, actual: "supply Delayed -> install Not Started — 3rd witness, supply-driven" }, { plan: "malpani", dur: 13, note: "kitchen exhaust block on 60d blitz" }, { plan: "firstsource", dur: 12, note: "exhaust supply 2 + install 8 + T&C 2 — 2nd witness" }],
  plywood_backing: [{ plan: "ls", dur: 3, note: "explicit task x2 partitions + 18d carpentry-wide; also DHL ply supports — the 2nd witness that BIRTHED the code" }, { plan: "dhl", dur: 7, note: "ply supports in partitions AND ceiling" }],
  partition_tape: [{ plan: "ls", dur: 3, note: "jointing & taping" }],
  washroom_accessories: [{ plan: "ls", dur: 2, note: "mirror/paper-holder/dispenser/tissue as 4 parallel micro-tasks <- dado FS+3" }],
  vinyl_lvt: [{ plan: "ls", dur: 4, note: "LVT passage <- leveling; grass carpet variant for breakout/cafeteria" }],
  core_cut: [{ plan: "tcs", dur: 7, actual: "Completed — 3rd witness" }, { plan: "malpani", dur: 4, note: "2nd witness" }],
  pkg_design: [{ plan: "tcs", dur: 58, note: "GFC 58d elapsed on a 105d job; layout suite 2-4d each; MEP drawings 23d — template match with Emirates/Malpani" }],
  pkg_submittal: [{ plan: "tcs", dur: 38, note: "samples 38d incl. a full MOCKUP ROOM; 34 order lines over a 62d Major Procurement window" }],
};

// ---- cross-plan verdicts (votes accumulate; 2 agreeing witnesses = confidence upgrade)
const VERDICTS = {
  second_witness_confirmed: [
    "lineout_marking (DHL: 9d planned, done in 5)", "pop_punning (DHL 30d)", "self_leveling (micro concrete)",
    "metal_ceiling (metal mesh 18d + acoustic baffle 12d)", "wallpaper (Graphics/Wall paper)",
    "toilet_exhaust (Exhaust Fan)", "wld_system + rodent_system + VESDA (critical rooms)",
    "fire_door (critical rooms)", "ups_battery (delivery->placement->install->terminations)",
    "refnet_pipe (Supporting & copper piping)", "g_wall chain (Services containment in Partition) — THIRD witness",
    "g_waterproof ponding (explicit 2d Ponding Test)", "g_pipe_test (Testing of the Plumbing Pipes 5d)",
    "g_sprk_test (Pressure Testing 3d)", "delivery-then-install (sliding panels, loose furniture, chairs, UPS) — THIRD witness",
    "critical-room mini-project class (Emirates + DHL)", "branding/graphics/planters/film at phase 93-95 (14-21 Aug block)",
  ],
  contradictions: [
    "HVAC COMMISSIONING: Pivox runs it SS with unit installs; LS runs it FS after ODU — 1-1, recorded, rule stays FS (commissioning after both units).",
    "DUCT METHOD — RE-TIED 2-2 (TCS pre-insulates). Emirates+Firstsource wrap vs DHL+TCS pre-insulate. Site practice, not physics: query restored to med, both topologies selectable per project.",
    "(superseded, audit trail) DUCT METHOD — RESOLVED 2-1 (13 Jul): Firstsource sequences marking/support -> installation -> 'Insulation for ducts' -> grilles = WRAP AFTER HANGING, agreeing with Emirates against DHL's pre-insulated method. (Caveat: FS line 159 reads 'Installation of insulation' — almost certainly a typo for 'of ducts' given line 160 is the insulation.) Rule stands as default with 2 witnesses; DHL's pre-insulation remains a selectable method via Q-DUCT-METHOD / OPTS.ductMethod.",
  ],
  applied_calibrations_from_witnesses: [
    "STAGE ORDER FIXED (LS logic + Emirates dates): sample & material approval PRECEDES the PO — PKG_STAGES reordered design->approval->samples->po->mfg->delivery; pre-order variant keeps samples gating manufacture",
    "plywood_backing BORN (DHL ply supports + LS 'Ply backing' x3): in-wall/ceiling backing code, g_wall.from extended",
    "LAYOUTS-FIRST drawing law (LS #5 feeds all disciplines + Malpani SS-cascade): every discipline set draws off the layout set SS+2",
    "STAGE REORDER now THREE witnesses (Malpani recovered logic: 5 explicit sample->Order FS edges) — settled law",
    "PER-DISCIPLINE DRAWING RELEASE now THREE witnesses (Malpani: HVAC Heat Load -> Copper piping FS)",
    "EARNED-VALUE now 2 witnesses WITH DYNAMICS (Firstsource static weightage + TCS weekly S-curve w/ rebaseline) — graduates to build-candidate: auto-generate % curves from weightage x recorded facts",
    "sprinkler REFURB pattern 2nd witness (TCS mods of existing pipes/bulbs — Emirates match; Kohler FLSS = 3rd live case)",
    "PCC-first-when-slab-poor 2nd witness (TCS 23d + Malpani); supply-driven slippage 4th consecutive plan — procurement is where Flipspaces slips, site trades hold",
  ],
  third_witness: [
    "g_wall 'Clearance from Services' in partitions (4d) — FOURTH witness overall",
    "g_ceiling 'Clearance from Services' before grid tiles (15-17d!!) AND before gypsum boarding (6d) — on a blitz job the services sign-off window IS the bottleneck",
    "lineout marking + EXPLICIT 'Lineout Checking & Approval' 1d task",
    "critical-rooms mini-project (Hub/UPS/BMS as own block, 48d)",
    "delivery-then-install (grid tiles, glazed glass, fire doors 'Order closer and Supply', kitchen equipment, UPS)",
    "ws_power_data (identical task text to Emirates: routing power/data & socket fixing in workstations)",
    "sprinkler lifecycle (MS pipes, enamel painting, flexis, pendent/upright, T&C)",
    "FA lifecycle (cabling, multi-sensor, heat, RI, MCP/strobes, T&C — identical names to Emirates)",
    "paint cycles per surface (walls + ceiling separately, putty->primer->coats)",
    "POP punning, pest control, pelmet/sill on-site joinery, rodent + WLD, UPS supply->install->T&C",
    "g_wall FIFTH witness — LS logic: second-side skinning <- wall conduits (#101<-86); g_ceiling FIFTH — LS: closing <- ceiling conduits+wiring AND FA-test/HVAC-commissioning FS-2d",
    "toilet_exhaust FOURTH (LS washroom ventilation <- HVAC supply); condensate FOURTH (LS copper+drainage; Malpani drain piping + insulation of copper&drain)",
    "furniture-after-carpet FOURTH (LS 227<-208); switches-in-furniture after furniture (LS 269<-227) = ws_power_data law in their logic",
    "glass SITE-MEASURE 2nd witness (LS explicit 'Glass measurement' <- both partition closures; FS glass 4d gap)",
    "final-coat-late 2nd witness (LS 5-coat wall system with separate Final Coat; FLOORING waits for it: tiles <- 245)",
    "core_cut 2nd witness (Malpani); SPC 2nd (Malpani); kitchen Ansul 2nd (Malpani 12d block)",
    "FINAL-COAT-LATE — THIRD WITNESS (Addverb x4 floors + LS explicit task + Firstsource 15d hold) => LAW: the last paint coat is an end-of-job touch-up pass; MODEL CANDIDATE: split final coat from paint_emulsion",
    "glass SITE-MEASURE — THIRD witness (Pivox 2022 ancestor + LS + Firstsource gap) => settled",
    "plywood_backing — THIRD witness (Pivox 2022 EARLIEST + DHL + LS): the code was born correctly",
    "MSP-genre integrity rule — SECOND witness (Pivox 0 violations on 152 edges; LS 0 on 356; Excel genre carries 9+) => tool-enforced logic works, engine adds physics",
    "decoratives-gated-on-final-coat (Pivox 194SS+4 + LS FF-links) — 2nd witness",
    "day-zero order release (Pivox: 7 orders 4SS to layout START; LS: FS+7 hub) — two release patterns recorded",
    "R19 vindicated by the TEACHING TEMPLATE itself: BFIL exemplar overlaps carpet with final coats — our rulebook is stricter than the training material",
  ],
  concept_candidates: [
    "FINAL-COAT-LATE: Firstsource holds 2nd coat 15d for end-of-job touch-up (1 witness; Emirates/DHL run coats contiguous) — candidate rule: final paint coat as a late touch-up task",
    "OPPORTUNISTIC RE-SEQUENCING (2 witnesses: DHL paint -43d pull-forward; FS cabling/glass running while civil delayed): crews jump to open fronts — the takt backfill models this; PR-3 will record it on live projects",
    "DEFAULT SECTION WEIGHTAGES (Firstsource): critical rooms C&I 8/doors 11/elec 12/HVAC 10/ELV 16/ceiling 16/paint 15/raised floor 11/clean 1 = 100; main block MEP+fire+ELV ~39% of value — seed for earned-value progress billing",
    "section WEIGHTAGE % (Firstsource): progress-measurement weights per work section for billing — same family as kt.raGates baskets; candidate: weightage field on categories feeding earned-value style progress",
    "kitchen fire suppression (Ansul-type) witnessed — mapped to gas_suppression kitchen variant",
    "zone-level interim handover milestone (DHL 'Handover to IT' day-0 in hub room; releases client's IT vendor)",
    "plywood backing/supports as a code (DHL ply supports in partitions AND ceilings)",
    "chilled-water piping as distinct from VRF refnet",
    "opportunistic pull-forward: DHL started paint base prep 43d EARLY when crews freed — engine equivalent = backfill, already in takt",
  ],
};

// ---- what Emirates CONFIRMED in the rulebook (sequence votes) -------
const CONFIRMATIONS = [
  "g_wall gate = their 'Clearance from Services' (3d) between one-side skin + insulation and second-side close",
  "paint (all coats) BEFORE ceiling tiles / carpet / blinds / wallpaper — dust rule (R19) holds",
  "ceiling painted AFTER gypsum boarding — the ceilPaint quantity fix was right",
  "sprinkler + copper/refnet + drains + FA cabling all BEFORE ceiling closes — g_ceiling family",
  "ws_power_data: power/data routed INSIDE workstations after frames — his catch, their task",
  "wiring_point (switches/sockets) phase ~90, near handover",
  "delivery-then-install per package everywhere — the enabling chain shape",
  "sample approvals 5-7d planned AND met on actuals — pkg_submittal=5wd CONFIRMED with actuals",
  "statutory/liaison runs from day 1 pre-construction (Mumbai: BMC+Mathadi+NOC 86d, met)",
  "design slips first: 8 MEP layouts planned 24-26 Sep all still open at 30 Sep snapshot",
];

// ---- calibrations applied to the library because of this plan -------
const CALIBRATIONS = [
  "PKG_WD.po 3 -> 5 (their Order tasks run 6-7d elapsed incl. commercial close)",
  "pkg_delivery 1 -> 2 (their delivery lines 2-4d for staged receipt)",
  "pkg_submittal conf med -> high (planned 5-7d, ACHIEVED on actuals)",
  "tc_fire norm src note: full-system FA T&C runs to 15d (Emirates) — size qty per system scope",
  "new codes: self_leveling pop_punning lineout_marking wallpaper lacquered_glass fluted_panel stretch_ceiling metal_ceiling epoxy_flooring wall_dado fire_door vav_unit fire_damper ahu_unit precision_ac ups_battery pa_system wld_system rodent_system gas_suppression bms_integration av_system white_goods statutory_liaison",
  "new PACKAGES: fire_door ahu precision_ac ups_battery av_system stretch_ceiling metal_ceiling white_goods critical_elv",
];

const CORPUS = { PLANS, VOCABULARY, EVIDENCE, CONFIRMATIONS, CALIBRATIONS, VERDICTS };
(function (g) { g.KB_CORPUS = CORPUS; })(typeof window !== "undefined" ? window : globalThis);
if (typeof module !== "undefined" && module.exports) module.exports = CORPUS;

})();
