// AUTO-GENERATED by scripts/read_boq.py — the engine's read of the real priced BOQ.
// Do not hand-edit. Re-run the reader when the BOQ file changes.
;(function(){
const BOQ = {
 "source": "Kohler_Pune_7F_Detailed_BOQ_Priced.xlsx",
 "readAt": "2026-07-10",
 "header": [
  "KOHLER PUNE \u2014 7TH FLOOR (A-WING)  \u00b7  BILL OF QUANTITIES (PRICED)",
  "Carpet area 15,000 sqft \u00b7 rates = our base cost (BCS), \u20b9 \u00b7 derived from rate-analysis (C&I validated against Kohler priced run; MEP derived). Client price = BCS \u00d7 (1+GM)."
 ],
 "lines": [
  {
   "id": "CI.01",
   "pkg": "Civil & Interiors",
   "desc": "Dismantling existing false ceiling of all types (mineral fibre grid / gypsum incl. suspension systems, framing, trims) without damage to retained services; stacking reusable light fittings & grilles for MEP salvage; lowering, removal of debris from premises incl. all lifts/leads and disposal at approved municipal location. Rate to include making good of soffit and protection of live services.",
   "unit": "sqft",
   "qty": 14400.0,
   "rate": 25.0,
   "amount": 360000.0
  },
  {
   "id": "CI.02",
   "pkg": "Civil & Interiors",
   "desc": "Taking out existing floor finishes (carpet tile / vitrified / stone) incl. grinding off adhesive residue, removal of skirting & transition strips, stacking salvageable material as directed, and carting away debris incl. all leads & lifts. Rate to include surface preparation to receive new finishes.",
   "unit": "sqft",
   "qty": 14400.0,
   "rate": 30.0,
   "amount": 432000.0
  },
  {
   "id": "CI.03",
   "pkg": "Civil & Interiors",
   "desc": "Careful dismantling of existing partitions (gypsum/glazed/solid), doors with frames, fixed joinery and wall panelling incl. supports & fasteners; salvage of client-retained items as listed; removal of debris from site with all leads & lifts. Rate to include temporary supports & protection of structure and retained MEP.",
   "unit": "sqft",
   "qty": 6480.0,
   "rate": 35.0,
   "amount": 226800.0
  },
  {
   "id": "CI.04",
   "pkg": "Civil & Interiors",
   "desc": "Attendance and builder's work in connection with MEP make-safe: assistance to MEP agencies isolating power/data/HVAC/sprinkler/fire-alarm drops within work zones, incl. access, marking, protection and coordination. Measured as lump sum.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "CI.05",
   "pkg": "Civil & Interiors",
   "desc": "Lowering, loading and carting away of all demolition debris incl. municipal royalty, via service lift in permitted hours; complete.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 200000.0,
   "amount": 200000.0
  },
  {
   "id": "CI.06",
   "pkg": "Civil & Interiors",
   "desc": "Providing and laying self-levelling cementitious underlayment (Ardex/Laticrete/eq.) over prepared existing screed incl. primer, laid to achieve flatness FF25 / \u00b13 mm over 3 m, cured as per manufacturer's specification, to receive stone/carpet/vitrified finishes. Rate to include surface preparation, vacuuming and priming.",
   "unit": "sqft",
   "qty": 9802.0,
   "rate": 85.0,
   "amount": 833170.0
  },
  {
   "id": "CI.07",
   "pkg": "Civil & Interiors",
   "desc": "Making good of walls/soffit/screed after strip-out incl. patch plaster, crack-stitching and priming, complete.",
   "unit": "sqft",
   "qty": 4320.0,
   "rate": 45.0,
   "amount": 194400.0
  },
  {
   "id": "CI.08",
   "pkg": "Civil & Interiors",
   "desc": "Providing and erecting GI stud partition 100 mm thick up to structural slab comprising 70 mm GI studs (0.55 BMT) at 610 c/c within GI floor & ceiling channels, ONE layer 12.5 mm tapered-edge gypsum plasterboard (Gyproc/USG-Boral/eq.) screw-fixed to EACH face, joints taped & finished with jointing compound to Level 4; incl. 50 mm / 48 kg-m3 mineral-wool acoustic infill, slotted deflection-head track at slab, intumescent acoustic sealant at head/base/abutments both faces, openings, additional studs at door frames & fixture back-blocking. Measured net area one side, to-slab height.",
   "unit": "sqft",
   "qty": 2553.0,
   "rate": 140.0,
   "amount": 357420.0
  },
  {
   "id": "CI.09",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing frameless toughened glass partition 12 mm thk (Saint-Gobain/AIS/eq.) incl. polished edges, SS-316 patch fittings, top & bottom U-channels in anodised aluminium, EPDM gaskets, structural silicone joints, cutouts and frosted-film manifestation band 100 mm at 1500 AFL per NBC. Rate to include templates, hoisting and protection till handover.",
   "unit": "sqft",
   "qty": 1207.0,
   "rate": 320.0,
   "amount": 386240.0
  },
  {
   "id": "CI.10",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing single-leaf frameless toughened glass door 12 mm thk approx. 1000 x 2400 incl. SS patch set, floor spring (Dorma BTS-80/eq.) with cover plate, patch lock with euro cylinder, 600 mm SS-316 D-pull handle pair, door stopper and manifestation band; incl. all cutting, drilling & templates.",
   "unit": "no",
   "qty": 12.0,
   "rate": 42000.0,
   "amount": 504000.0
  },
  {
   "id": "CI.11",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing solid-core flush door shutter 35 mm thk with 4 mm AAA-grade natural wood veneer both faces, PU matt finish, in seasoned hardwood/laminated frame with required architraves; incl. SS-304 hardware set (3 nos ball-bearing hinges, mortice lock with lever handle, door closer, stopper, buffer) and fire/acoustic seals where specified.",
   "unit": "no",
   "qty": 6.0,
   "rate": 28000.0,
   "amount": 168000.0
  },
  {
   "id": "CI.12",
   "pkg": "Civil & Interiors",
   "desc": "Providing and laying heavy-contract loop-pile carpet TILES 500x500 (Interface/Shaw/Milliken/eq., 550-600 gsm solution-dyed nylon, fire-rated bitumen backing to BS 4790) laid in approved pattern over prepared sub-floor with manufacturer-recommended releasable adhesive; incl. cutting, wastage, edge trims at abutments and protection till handover. Measured net laid area.",
   "unit": "sqft",
   "qty": 5290.0,
   "rate": 220.0,
   "amount": 1163800.0
  },
  {
   "id": "CI.13",
   "pkg": "Civil & Interiors",
   "desc": "Providing and laying Italian silver travertine flooring 18 mm thk, vein-cut, honed & filled, in slabs of approved sizes laid to radial/coursed pattern as per architect's drawing, over 4-6 mm Laticrete/Ardex tile adhesive on prepared underlayment; joints filled with matching epoxy grout; incl. machine edge-chamfer, diamond-polish & penetrating sealer (2 coats), brass inlay grooves where shown, curing, acid-free wash and rigid protection (Ramboard/POP) till handover.",
   "unit": "sqft",
   "qty": 1329.0,
   "rate": 480.0,
   "amount": 637920.0
  },
  {
   "id": "CI.14",
   "pkg": "Civil & Interiors",
   "desc": "Providing and laying 1st-quality double-charged vitrified tiles 800x1600 / 600x600 (Kajaria/RAK/Nitco/eq.) with 3 mm spacers over Laticrete tile adhesive 4-6 mm thk; joints filled with approved epoxy grout (Laticrete SP-100/eq.) of approved shade per manufacturer's specification. Rate to include laying to approved pattern as directed by Architect, cutting, curing, acid wash and protection till handover.",
   "unit": "sqft",
   "qty": 6976.0,
   "rate": 150.0,
   "amount": 1046400.0
  },
  {
   "id": "CI.15",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing skirting 100 mm high in material matching adjoining floor finish (carpet capped-PVC / stone / vitrified as applicable) incl. adhesive, epoxy grout, edge polish and junction trims, complete per drawing.",
   "unit": "RM",
   "qty": 520.0,
   "rate": 100.0,
   "amount": 52000.0
  },
  {
   "id": "CI.16",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing brushed-brass flush inlay strips / transition profiles set in stone-carpet-vitrified junctions incl. epoxy bedding and polish; measured per running metre.",
   "unit": "RM",
   "qty": 49.6,
   "rate": 650.0,
   "amount": 32240.0
  },
  {
   "id": "CI.17",
   "pkg": "Civil & Interiors",
   "desc": "Providing and applying plastic emulsion paint of approved premium brand (Asian Royale/Dulux Velvet/eq.) in approved shade \u2014 2 coats over 1 coat primer and 2 coats putty (total system) on new/prepared gypsum & masonry surfaces incl. surface preparation, sanding, masking of adjoining finishes, scaffolding and touch-up till handover. Measured net developed area; openings deducted per IS 1200.",
   "unit": "sqft",
   "qty": 28800.0,
   "rate": 55.0,
   "amount": 1584000.0
  },
  {
   "id": "CI.18",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing wall panelling in 4 mm AAA-grade natural veneer (walnut/ash per palette) on 12 mm MR-grade MDF/ply backing over GI/aluminium framing incl. melamine-matched PU matt finish 20-30% sheen, fluted profiles 12 mm at 50 c/c where shown, grooves, edge lipping, concealed fixing clips, cutouts for services and final polish, complete per elevations.",
   "unit": "sqft",
   "qty": 1200.0,
   "rate": 520.0,
   "amount": 624000.0
  },
  {
   "id": "CI.19",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing fabric-wrapped acoustic wall panels 25 mm thk (NRC >= 0.80), FR-grade fabric of approved shade over resin-bonded fibreglass core on concealed aluminium sub-frame; incl. fire-retardant treatment, edge details, cutouts and brand-wall integration, complete.",
   "unit": "sqft",
   "qty": 500.0,
   "rate": 450.0,
   "amount": 225000.0
  },
  {
   "id": "CI.20",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing stone cladding (travertine/marble per palette) 18 mm thk on walls over MS/GI framework with SS pins/adhesive (dry-clad system), incl. FR-ply backing where specified, edge-chamfers, recessed niches with concealed LED grooves, brass trims at junctions, sealing and protection, complete per elevations.",
   "unit": "sqft",
   "qty": 730.0,
   "rate": 600.0,
   "amount": 438000.0
  },
  {
   "id": "CI.21",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing ceramic/vitrified wall dado tiles up to 1200 high at wet-service backsplash zones over adhesive incl. epoxy grout & SS edge trims.",
   "unit": "sqft",
   "qty": 260.0,
   "rate": 160.0,
   "amount": 41600.0
  },
  {
   "id": "CI.22",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing suspended gypsum board false ceiling \u2014 12.5 mm tapered-edge board (Gyproc/eq.) on GI grid comprising perimeter channels 20x30x0.55, intermediate channels at 1220 c/c and ceiling sections at 457 c/c suspended by GI rods/strap hangers at 1220 c/c from soffit; joints taped & jointed to Level 4 finish; incl. ALL cutouts & profiles for light fixtures, speakers, detectors, sprinklers, AC grilles & trap doors, coves/steps/bulkheads & curved profiles where shown, shadow-gap/perimeter D-mould, and access frames. Measured net per IS 1200.",
   "unit": "sqft",
   "qty": 6548.0,
   "rate": 160.0,
   "amount": 1047680.0
  },
  {
   "id": "CI.23",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing mineral-fibre acoustic ceiling 595x595x15/16 (Armstrong Dune Max/AMF/eq., NRC >= 0.5) on 24/15 mm powder-coated hot-dipped GI T-grid suspension at 600x600 module incl. perimeter wall angles, hanger rods at 1200 c/c, hold-down clips, and coordination cutouts for services; complete per RCP.",
   "unit": "sqft",
   "qty": 2799.0,
   "rate": 120.0,
   "amount": 335880.0
  },
  {
   "id": "CI.24",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing suspended timber slat ceiling raft \u2014 solid/veneered slats 60x30 at 90 c/c, PU matt finish, mechanically fixed to concealed black-finished GI/aluminium carriers with black acoustic backer board above, suspended on threaded rods with acoustic mounts; incl. integrated linear-light slots, edge trims and access provisions, complete per RCP & detail.",
   "unit": "sqft",
   "qty": 1019.0,
   "rate": 450.0,
   "amount": 458550.0
  },
  {
   "id": "CI.25",
   "pkg": "Civil & Interiors",
   "desc": "Surface preparation and 2-coat black/deep-tone soffit paint to exposed services zones incl. service dressing.",
   "unit": "sqft",
   "qty": 1754.0,
   "rate": 45.0,
   "amount": 78930.0
  },
  {
   "id": "CI.26",
   "pkg": "Civil & Interiors",
   "desc": "Supplying and installing concealed LED strip lighting 14.4 W/m, 3000 K, CRI >= 90 (Osram/Philips/eq.) in continuous aluminium extrusion profile with opal diffuser within ceiling coves/grooves incl. 24 V drivers at accessible locations, looping, dimmable feed wiring to controller, and balancing for uniform wash; measured per running metre installed.",
   "unit": "RM",
   "qty": 356.0,
   "rate": 650.0,
   "amount": 231400.0
  },
  {
   "id": "CI.27",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing gypsum pelmet/curtain box in ceiling at facade incl. additional framing, board encasing, finishing to Level 4 and integration of motorised track; measured per running metre.",
   "unit": "RM",
   "qty": 46.0,
   "rate": 450.0,
   "amount": 20700.0
  },
  {
   "id": "CI.28",
   "pkg": "Civil & Interiors",
   "desc": "Designing, fabricating and installing curved reception desk approx. 4.2 m developed length comprising marine-ply carcass, travertine-clad external faces & top per stone specification, solid-surface (Corian/eq.) internal worktop, brass reveal with concealed LED underglow, integrated cable management, grommets, lockable drawer unit & footrest; complete with all hardware, polish and protection, per detail drawing.",
   "unit": "no",
   "qty": 1.0,
   "rate": 1000000.0,
   "amount": 1000000.0
  },
  {
   "id": "CI.29",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing upholstered window-ledge banquette seating: marine-ply carcass with veneer-finished facing & integrated storage (push-open), seat & back in FR-grade upholstery fabric over high-resilience foam (density 40/32), incl. SS legs/cleats, piping and all hardware, per detail; measured per running metre.",
   "unit": "RM",
   "qty": 17.5,
   "rate": 12000.0,
   "amount": 210000.0
  },
  {
   "id": "CI.30",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing storage credenza units in AAA veneer w/ PU finish, charcoal-marble/stone top 18 mm, push-to-open & soft-close hardware (Hettich/Blum), internal laminate carcass, levelers and wall-fixing cleats, complete per detail; measured per running metre.",
   "unit": "RM",
   "qty": 14.0,
   "rate": 18000.0,
   "amount": 252000.0
  },
  {
   "id": "CI.31",
   "pkg": "Civil & Interiors",
   "desc": "Fabricating and installing cafeteria service counters comprising SS-304 substructure, stone/solid-surface tops, veneer/laminate-clad fronts with bump rails, undercounter storage, cutouts for equipment & sinks, food-grade sealed joints; complete per detail drawings; measured per running metre.",
   "unit": "RM",
   "qty": 22.0,
   "rate": 22000.0,
   "amount": 484000.0
  },
  {
   "id": "CI.32",
   "pkg": "Civil & Interiors",
   "desc": "Fabricating and installing product-display plinths, backlit display wall with niches, integrated water-feature trough cladding per design; complete per details.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 800000.0,
   "amount": 800000.0
  },
  {
   "id": "CI.33",
   "pkg": "Civil & Interiors",
   "desc": "Supplying loose furniture (FF&E) per approved schedule incl. delivery, assembly, levelling, placement per layout and removal of packing: workstation desks 1500x750 with modesty & cable tray; ergonomic task chairs; meeting/boardroom tables with flip-up power-data modules; lounge seating; cafe tables & chairs. Per item rates as scheduled.",
   "unit": "no",
   "qty": 42.0,
   "rate": 18000.0,
   "amount": 756000.0
  },
  {
   "id": "CI.34",
   "pkg": "Civil & Interiors",
   "desc": "Ergonomic high-back task chairs, synchro-tilt, 4D arms, per approved sample.",
   "unit": "no",
   "qty": 54.0,
   "rate": 12000.0,
   "amount": 648000.0
  },
  {
   "id": "CI.35",
   "pkg": "Civil & Interiors",
   "desc": "Boardroom table 5.4 m walnut w/ flip-up power-data + 18 executive chairs.",
   "unit": "set",
   "qty": 1.0,
   "rate": 450000.0,
   "amount": 450000.0
  },
  {
   "id": "CI.36",
   "pkg": "Civil & Interiors",
   "desc": "MR tables with power modules + chairs per room schedule (6-pax x1, 4-pax x2, HR/Fin/HRC sets).",
   "unit": "set",
   "qty": 6.0,
   "rate": 85000.0,
   "amount": 510000.0
  },
  {
   "id": "CI.37",
   "pkg": "Civil & Interiors",
   "desc": "Cafe tables (4/6-seat mix), chairs/benches, high tables w/ stools per layout.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 1500000.0,
   "amount": 1500000.0
  },
  {
   "id": "CI.38",
   "pkg": "Civil & Interiors",
   "desc": "Foyer settees, lounge chairs, coffee tables, planters per layout blocks.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 800000.0,
   "amount": 800000.0
  },
  {
   "id": "CI.39",
   "pkg": "Civil & Interiors",
   "desc": "Providing and fixing motorised/manual roller blinds with FR-grade fabric (3-5% openness solar screen / dim-out as scheduled) incl. anodised aluminium headrail, side guides where required, motors with grouped control at facade zones, and commissioning; measured per sqm of covered glazing.",
   "unit": "sqft",
   "qty": 2600.0,
   "rate": 350.0,
   "amount": 910000.0
  },
  {
   "id": "CI.40",
   "pkg": "Civil & Interiors",
   "desc": "Designing, fabricating and installing internal brand signage: brushed-brass channel letters (KOHLER wordmark) halo-lit with concealed LED & remote driver, pinned off finished wall/panelling; incl. room-name plates in brass/acrylic per schedule, templates, and final alignment; per set/number as scheduled.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 1200000.0,
   "amount": 1200000.0
  },
  {
   "id": "CI.41",
   "pkg": "Civil & Interiors",
   "desc": "Preparing samples & mock-ups for approval: 1 sqm stone floor panel, veneer & PU samples, fabric/carpet swatches, brass finish chips, paint draw-downs, 1 full workstation set; incl. resubmissions till approval and maintaining approved control samples on site.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "CI.42",
   "pkg": "Civil & Interiors",
   "desc": "Providing protection to completed/retained works: Ramboard/POP+polythene to stone floors, corrugated sheet to joinery edges, adhesive film to glass & metal finishes, ply barricades to lift lobby and retained toilets; maintained till handover incl. removal & disposal.",
   "unit": "sqft",
   "qty": 3200.0,
   "rate": 25.0,
   "amount": 80000.0
  },
  {
   "id": "CI.43",
   "pkg": "Civil & Interiors",
   "desc": "Final builder's clean on completion: machine-scrub & dress floors, glass & frame cleaning both sides, fitting & fixture wipe-down, vacuum of carpets, removal of all protection/stickers/debris, ready-for-business handover.",
   "unit": "sqft",
   "qty": 14400.0,
   "rate": 12.0,
   "amount": 172800.0
  },
  {
   "id": "CI.44",
   "pkg": "Civil & Interiors",
   "desc": "Defect-liability attendance for 12 months from virtual completion per SOW: monthly inspection visits, snag rectification within agreed SLA, touch-up materials & labour; priced as lump-sum provision.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 250000.0,
   "amount": 250000.0
  },
  {
   "id": "HV.01",
   "pkg": "HVAC / Mechanical",
   "desc": "Supplying, installing, testing & commissioning VRF ODUs of scheduled capacity at approved location incl. MS stands w/ anti-vibration mounts, manufacturer Y-joints/headers, power & control terminations, commissioning at full/part load per ISHRAE.",
   "unit": "TR",
   "qty": 48.0,
   "rate": 40000.0,
   "amount": 1920000.0
  },
  {
   "id": "HV.02",
   "pkg": "HVAC / Mechanical",
   "desc": "Hard-drawn copper liquid+suction pair, brazed under nitrogen, sized per selection s/w; 19/25 mm Class-O nitrile insulation; MS supports @1.2 m; pressure test 38 bar; vacuum to 500 micron.",
   "unit": "RM",
   "qty": 134.4,
   "rate": 650.0,
   "amount": 87360.0
  },
  {
   "id": "HV.03",
   "pkg": "HVAC / Mechanical",
   "desc": "Hard-drawn copper liquid+suction pair, brazed under nitrogen, sized per selection s/w; 19/25 mm Class-O nitrile insulation; MS supports @1.2 m; pressure test 38 bar; vacuum to 500 micron.",
   "unit": "RM",
   "qty": 115.2,
   "rate": 900.0,
   "amount": 103680.0
  },
  {
   "id": "HV.04",
   "pkg": "HVAC / Mechanical",
   "desc": "Hard-drawn copper liquid+suction pair, brazed under nitrogen, sized per selection s/w; 19/25 mm Class-O nitrile insulation; MS supports @1.2 m; pressure test 38 bar; vacuum to 500 micron.",
   "unit": "RM",
   "qty": 76.8,
   "rate": 1100.0,
   "amount": 84480.0
  },
  {
   "id": "HV.05",
   "pkg": "HVAC / Mechanical",
   "desc": "Hard-drawn copper liquid+suction pair, brazed under nitrogen, sized per selection s/w; 19/25 mm Class-O nitrile insulation; MS supports @1.2 m; pressure test 38 bar; vacuum to 500 micron.",
   "unit": "RM",
   "qty": 57.6,
   "rate": 1300.0,
   "amount": 74880.0
  },
  {
   "id": "HV.06",
   "pkg": "HVAC / Mechanical",
   "desc": "Supplying & charging additional refrigerant beyond factory charge, per OEM chart for installed pipe lengths, incl. weighing record.",
   "unit": "kg",
   "qty": 21.0,
   "rate": 2500.0,
   "amount": 52500.0
  },
  {
   "id": "HV.07",
   "pkg": "HVAC / Mechanical",
   "desc": "OEM refnet joints/headers per circuit design incl. insulation kits.",
   "unit": "no",
   "qty": 18.0,
   "rate": 3500.0,
   "amount": 63000.0
  },
  {
   "id": "HV.08",
   "pkg": "HVAC / Mechanical",
   "desc": "3C\u00d74 / 3C\u00d72.5 Cu cabling from AC DB to ODUs + 2C\u00d71.5 shielded control bus daisy-chain, in conduit/tray.",
   "unit": "RM",
   "qty": 180.0,
   "rate": 350.0,
   "amount": 63000.0
  },
  {
   "id": "HV.09",
   "pkg": "HVAC / Mechanical",
   "desc": "Vacuum/charge records, controller addressing, trial run reports, handover docs.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "HV.10",
   "pkg": "HVAC / Mechanical",
   "desc": "SITC ceiling cassettes of scheduled capacities incl. decorative panel, in-built drain pump, wired controller, hangers w/ vibration isolators.",
   "unit": "no",
   "qty": 16.0,
   "rate": 45000.0,
   "amount": 720000.0
  },
  {
   "id": "HV.11",
   "pkg": "HVAC / Mechanical",
   "desc": "SITC concealed ductable units incl. plenum, canvas connection, filter access, controller.",
   "unit": "no",
   "qty": 8.0,
   "rate": 65000.0,
   "amount": 520000.0
  },
  {
   "id": "HV.12",
   "pkg": "HVAC / Mechanical",
   "desc": "Fabricated GI ducting incl. flanges, gaskets, vanes, supports; pressure class per SMACNA.",
   "unit": "sqm",
   "qty": 448.0,
   "rate": 950.0,
   "amount": 425600.0
  },
  {
   "id": "HV.13",
   "pkg": "HVAC / Mechanical",
   "desc": "Fabricated GI ducting incl. flanges, gaskets, vanes, supports; pressure class per SMACNA.",
   "unit": "sqm",
   "qty": 192.0,
   "rate": 1100.0,
   "amount": 211200.0
  },
  {
   "id": "HV.14",
   "pkg": "HVAC / Mechanical",
   "desc": "Closed-cell nitrile on supply ducts incl. adhesive + vapour seal; first 5 m acoustically lined.",
   "unit": "sqm",
   "qty": 540.0,
   "rate": 220.0,
   "amount": 118800.0
  },
  {
   "id": "HV.15",
   "pkg": "HVAC / Mechanical",
   "desc": "GI plenum boxes w/ side/top spigot, internally lined, for linear slot diffusers.",
   "unit": "no",
   "qty": 64.0,
   "rate": 3500.0,
   "amount": 224000.0
  },
  {
   "id": "HV.16",
   "pkg": "HVAC / Mechanical",
   "desc": "Extruded-aluminium continuous slot diffusers w/ pattern controllers, matt black/white per RCP.",
   "unit": "RM",
   "qty": 96.0,
   "rate": 2200.0,
   "amount": 211200.0
  },
  {
   "id": "HV.17",
   "pkg": "HVAC / Mechanical",
   "desc": "4-way square diffusers + egg-crate/louvred return grilles w/ removable cores.",
   "unit": "no",
   "qty": 58.0,
   "rate": 2800.0,
   "amount": 162400.0
  },
  {
   "id": "HV.18",
   "pkg": "HVAC / Mechanical",
   "desc": "Opposed-blade GI VCDs at branch take-offs, with locking quadrant.",
   "unit": "no",
   "qty": 26.0,
   "rate": 3500.0,
   "amount": 91000.0
  },
  {
   "id": "HV.19",
   "pkg": "HVAC / Mechanical",
   "desc": "Fire dampers at rated-wall crossings incl. access doors + actuators where motorised.",
   "unit": "no",
   "qty": 8.0,
   "rate": 8500.0,
   "amount": 68000.0
  },
  {
   "id": "HV.20",
   "pkg": "HVAC / Mechanical",
   "desc": "Aluminium flexible ducts max 1.5 m, double-skin insulated, with clamps.",
   "unit": "no",
   "qty": 58.0,
   "rate": 1800.0,
   "amount": 104400.0
  },
  {
   "id": "HV.21",
   "pkg": "HVAC / Mechanical",
   "desc": "uPVC drain w/ 9 mm nitrile insulation laid @1:100, U-traps at IDUs, cleanouts; to shaft.",
   "unit": "RM",
   "qty": 158.4,
   "rate": 180.0,
   "amount": 28512.0
  },
  {
   "id": "HV.22",
   "pkg": "HVAC / Mechanical",
   "desc": "uPVC drain w/ 9 mm nitrile insulation laid @1:100, U-traps at IDUs, cleanouts; to shaft.",
   "unit": "RM",
   "qty": 105.6,
   "rate": 220.0,
   "amount": 23232.0
  },
  {
   "id": "HV.23",
   "pkg": "HVAC / Mechanical",
   "desc": "SITC TFA w/ MERV-13 filtration, fan section, cooling coil tie-in per design, vibration isolators.",
   "unit": "no",
   "qty": 1.0,
   "rate": 650000.0,
   "amount": 650000.0
  },
  {
   "id": "HV.24",
   "pkg": "HVAC / Mechanical",
   "desc": "Inline exhaust fans for dishwash/handwash w/ backdraft dampers, speed control.",
   "unit": "no",
   "qty": 3.0,
   "rate": 18000.0,
   "amount": 54000.0
  },
  {
   "id": "HV.25",
   "pkg": "HVAC / Mechanical",
   "desc": "Group remote controllers, central 10\" touch controller, VRF-BMS gateway, addressing.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 250000.0,
   "amount": 250000.0
  },
  {
   "id": "HV.26",
   "pkg": "HVAC / Mechanical",
   "desc": "Threaded rods, GI channels, duct hangers, foam tapes, sealants, identification labels.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 120000.0,
   "amount": 120000.0
  },
  {
   "id": "HV.27",
   "pkg": "HVAC / Mechanical",
   "desc": "Fire-retardant canvas connections at ductable unit discharge/return.",
   "unit": "no",
   "qty": 16.0,
   "rate": 1500.0,
   "amount": 24000.0
  },
  {
   "id": "HV.28",
   "pkg": "HVAC / Mechanical",
   "desc": "Threaded rod + channel trapeze @2.4 m c/c incl. anchors.",
   "unit": "set",
   "qty": 89.0,
   "rate": 2500.0,
   "amount": 222500.0
  },
  {
   "id": "HV.29",
   "pkg": "HVAC / Mechanical",
   "desc": "Nitrogen hold test on piping; duct light/smoke leakage test class-C.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 40000.0,
   "amount": 40000.0
  },
  {
   "id": "HV.30",
   "pkg": "HVAC / Mechanical",
   "desc": "ISMC-100 frames, anti-vibration pads, foundation bolts at ODU deck.",
   "unit": "set",
   "qty": 6.0,
   "rate": 12000.0,
   "amount": 72000.0
  },
  {
   "id": "EL.01",
   "pkg": "Electrical",
   "desc": "Wall-mount powder-coated floor panel: 125A 4P MCCB incomer w/ earth-leakage relay, ammeter/voltmeter w/ selector, indicating lamps, bus 200A, per approved SLD; IS 8623.",
   "unit": "no",
   "qty": 1.0,
   "rate": 85000.0,
   "amount": 85000.0
  },
  {
   "id": "EL.02",
   "pkg": "Electrical",
   "desc": "SITC VTPN DB double-door IP-42 w/ 63A 4P isolator incomer; circuits per schedule, engraved labels, circuit chart.",
   "unit": "no",
   "qty": 2.0,
   "rate": 28000.0,
   "amount": 56000.0
  },
  {
   "id": "EL.03",
   "pkg": "Electrical",
   "desc": "TPN DB for cassette/ductable/ODU feeders w/ 63A 4P RCCB 100 mA incomer.",
   "unit": "no",
   "qty": 1.0,
   "rate": 18000.0,
   "amount": 18000.0
  },
  {
   "id": "EL.04",
   "pkg": "Electrical",
   "desc": "SPN DBs at cafe/pantry w/ 40A DP RCCB 30 mA incomer.",
   "unit": "no",
   "qty": 2.0,
   "rate": 12000.0,
   "amount": 24000.0
  },
  {
   "id": "EL.05",
   "pkg": "Electrical",
   "desc": "UPS distribution board w/ 63A DP MCB incomer + status lamps.",
   "unit": "no",
   "qty": 1.0,
   "rate": 15000.0,
   "amount": 15000.0
  },
  {
   "id": "EL.06",
   "pkg": "Electrical",
   "desc": "Miniature circuit breakers SP, 10 kA, C-curve, assorted 6/10/16/20/32A.",
   "unit": "no",
   "qty": 25.6,
   "rate": 350.0,
   "amount": 8960.0
  },
  {
   "id": "EL.07",
   "pkg": "Electrical",
   "desc": "Miniature circuit breakers SP, 10 kA, C-curve, assorted 6/10/16/20/32A.",
   "unit": "no",
   "qty": 32.0,
   "rate": 350.0,
   "amount": 11200.0
  },
  {
   "id": "EL.08",
   "pkg": "Electrical",
   "desc": "Miniature circuit breakers SP, 10 kA, C-curve, assorted 6/10/16/20/32A.",
   "unit": "no",
   "qty": 38.4,
   "rate": 350.0,
   "amount": 13440.0
  },
  {
   "id": "EL.09",
   "pkg": "Electrical",
   "desc": "Miniature circuit breakers SP, 10 kA, C-curve, assorted 6/10/16/20/32A.",
   "unit": "no",
   "qty": 19.2,
   "rate": 350.0,
   "amount": 6720.0
  },
  {
   "id": "EL.10",
   "pkg": "Electrical",
   "desc": "Miniature circuit breakers SP, 10 kA, C-curve, assorted 6/10/16/20/32A.",
   "unit": "no",
   "qty": 12.8,
   "rate": 350.0,
   "amount": 4480.0
  },
  {
   "id": "EL.11",
   "pkg": "Electrical",
   "desc": "RCBOs for socket circuits (raw & UPS) per IS 732 protection philosophy.",
   "unit": "no",
   "qty": 38.0,
   "rate": 2200.0,
   "amount": 83600.0
  },
  {
   "id": "EL.12",
   "pkg": "Electrical",
   "desc": "Incomer RCCBs where scheduled.",
   "unit": "no",
   "qty": 4.0,
   "rate": 3500.0,
   "amount": 14000.0
  },
  {
   "id": "EL.13",
   "pkg": "Electrical",
   "desc": "Isolators for DB incomers & AC outdoor feeders.",
   "unit": "no",
   "qty": 10.0,
   "rate": 1800.0,
   "amount": 18000.0
  },
  {
   "id": "EL.14",
   "pkg": "Electrical",
   "desc": "Concealed point wiring in FR PVC conduit w/ 3\u00d71.5 sqmm FRLS Cu (Ph/N/E) avg 9 m per point from switchboard incl. modular switch 6A, GI box & plate share; tested. CPWD pattern.",
   "unit": "pts",
   "qty": 540.0,
   "rate": 450.0,
   "amount": 243000.0
  },
  {
   "id": "EL.15",
   "pkg": "Electrical",
   "desc": "Looping of switched groups incl. ceiling rose/connector at fixture tails, flexible 3C\u00d70.75 to fixtures.",
   "unit": "pts",
   "qty": 540.0,
   "rate": 250.0,
   "amount": 135000.0
  },
  {
   "id": "EL.16",
   "pkg": "Electrical",
   "desc": "3\u00d72.5 sqmm FRLS in conduit avg 9 m + 6A modular switch+socket on shared plate; circuits \u22646 sockets.",
   "unit": "pts",
   "qty": 84.0,
   "rate": 550.0,
   "amount": 46200.0
  },
  {
   "id": "EL.17",
   "pkg": "Electrical",
   "desc": "3\u00d72.5 sqmm FRLS from UPS DB, red-identified modular socket; circuits \u22644 sockets; segregated conduit.",
   "unit": "pts",
   "qty": 115.0,
   "rate": 650.0,
   "amount": 74750.0
  },
  {
   "id": "EL.18",
   "pkg": "Electrical",
   "desc": "3\u00d74 sqmm FRLS avg 14 m + 16A switch-socket; dedicated/2-per-circuit.",
   "unit": "pts",
   "qty": 28.0,
   "rate": 750.0,
   "amount": 21000.0
  },
  {
   "id": "EL.19",
   "pkg": "Electrical",
   "desc": "3\u00d74 sqmm + 20A DP switch + industrial socket w/ plug top \u2014 cafe heavy equipment.",
   "unit": "pts",
   "qty": 4.0,
   "rate": 1200.0,
   "amount": 4800.0
  },
  {
   "id": "EL.20",
   "pkg": "Electrical",
   "desc": "3\u00d76 sqmm + 25A DP switch; for geysers per PHE.",
   "unit": "pts",
   "qty": 2.0,
   "rate": 1500.0,
   "amount": 3000.0
  },
  {
   "id": "EL.21",
   "pkg": "Electrical",
   "desc": "Circuit mains from DB to first point per circuit, avg 18 m, in conduit.",
   "unit": "RM",
   "qty": 1836.0,
   "rate": 85.0,
   "amount": 156060.0
  },
  {
   "id": "EL.22",
   "pkg": "Electrical",
   "desc": "Submains panel\u2192DBs in tray/conduit incl. terminations.",
   "unit": "RM",
   "qty": 250.0,
   "rate": 420.0,
   "amount": 105000.0
  },
  {
   "id": "EL.23",
   "pkg": "Electrical",
   "desc": "DB\u2192DB / heavy feeders.",
   "unit": "RM",
   "qty": 105.0,
   "rate": 520.0,
   "amount": 54600.0
  },
  {
   "id": "EL.24",
   "pkg": "Electrical",
   "desc": "ISI GI conduit concealed/surface incl. bends, couplers, saddles, deep/fan/junction boxes, fish wire, bushes.",
   "unit": "RM",
   "qty": 2296.2,
   "rate": 120.0,
   "amount": 275544.0
  },
  {
   "id": "EL.25",
   "pkg": "Electrical",
   "desc": "ISI GI conduit concealed/surface incl. bends, couplers, saddles, deep/fan/junction boxes, fish wire, bushes.",
   "unit": "RM",
   "qty": 1148.1,
   "rate": 160.0,
   "amount": 183696.0
  },
  {
   "id": "EL.26",
   "pkg": "Electrical",
   "desc": "ISI GI conduit concealed/surface incl. bends, couplers, saddles, deep/fan/junction boxes, fish wire, bushes.",
   "unit": "RM",
   "qty": 382.7,
   "rate": 210.0,
   "amount": 80367.0
  },
  {
   "id": "EL.27",
   "pkg": "Electrical",
   "desc": "Hot-dipped tray w/ cover on spine incl. bends/tees/reducers/couplers, supports @1.2 m, earth straps.",
   "unit": "RM",
   "qty": 130.0,
   "rate": 420.0,
   "amount": 54600.0
  },
  {
   "id": "EL.28",
   "pkg": "Electrical",
   "desc": "Branch trays to zones.",
   "unit": "RM",
   "qty": 80.0,
   "rate": 280.0,
   "amount": 22400.0
  },
  {
   "id": "EL.29",
   "pkg": "Electrical",
   "desc": "At fixture/equipment terminations.",
   "unit": "RM",
   "qty": 160.0,
   "rate": 140.0,
   "amount": 22400.0
  },
  {
   "id": "EL.30",
   "pkg": "Electrical",
   "desc": "Intumescent sealant/pillows where containment crosses rated walls.",
   "unit": "no",
   "qty": 12.0,
   "rate": 1200.0,
   "amount": 14400.0
  },
  {
   "id": "EL.31",
   "pkg": "Electrical",
   "desc": "Brass cable glands for submains/feeders incl. earthing tags & shrouds.",
   "unit": "no",
   "qty": 56.8,
   "rate": 120.0,
   "amount": 6816.0
  },
  {
   "id": "EL.32",
   "pkg": "Electrical",
   "desc": "Brass cable glands for submains/feeders incl. earthing tags & shrouds.",
   "unit": "no",
   "qty": 42.6,
   "rate": 180.0,
   "amount": 7668.0
  },
  {
   "id": "EL.33",
   "pkg": "Electrical",
   "desc": "Brass cable glands for submains/feeders incl. earthing tags & shrouds.",
   "unit": "no",
   "qty": 28.4,
   "rate": 280.0,
   "amount": 7952.0
  },
  {
   "id": "EL.34",
   "pkg": "Electrical",
   "desc": "Brass cable glands for submains/feeders incl. earthing tags & shrouds.",
   "unit": "no",
   "qty": 14.2,
   "rate": 450.0,
   "amount": 6390.0
  },
  {
   "id": "EL.35",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 327.6,
   "rate": 45.0,
   "amount": 14742.0
  },
  {
   "id": "EL.36",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 234.0,
   "rate": 55.0,
   "amount": 12870.0
  },
  {
   "id": "EL.37",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 140.4,
   "rate": 70.0,
   "amount": 9828.0
  },
  {
   "id": "EL.38",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 93.6,
   "rate": 90.0,
   "amount": 8424.0
  },
  {
   "id": "EL.39",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 93.6,
   "rate": 110.0,
   "amount": 10296.0
  },
  {
   "id": "EL.40",
   "pkg": "Electrical",
   "desc": "Crimping lugs for all terminations incl. ferrule identification both ends.",
   "unit": "no",
   "qty": 46.8,
   "rate": 140.0,
   "amount": 6552.0
  },
  {
   "id": "EL.41",
   "pkg": "Electrical",
   "desc": "Modular cover plates + metal back boxes for all switch/socket assemblies (count beyond point-wiring share).",
   "unit": "no",
   "qty": 91.0,
   "rate": 450.0,
   "amount": 40950.0
  },
  {
   "id": "EL.42",
   "pkg": "Electrical",
   "desc": "65W PD USB-C modular outlets at lounge/reception/boardroom.",
   "unit": "no",
   "qty": 12.0,
   "rate": 1800.0,
   "amount": 21600.0
  },
  {
   "id": "EL.43",
   "pkg": "Electrical",
   "desc": "PVC tape, cable ties, GI wire, ferrules, danger boards, ckt charts.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 25000.0,
   "amount": 25000.0
  },
  {
   "id": "EL.44",
   "pkg": "Electrical",
   "desc": "SITC recessed panels CRI\u226590, 4000K/3000K per zone, incl. drivers + flex connection.",
   "unit": "no",
   "qty": 140.0,
   "rate": 1400.0,
   "amount": 196000.0
  },
  {
   "id": "EL.45",
   "pkg": "Electrical",
   "desc": "Recessed downlights w/ deep baffle, dim-to-warm at hospitality zones.",
   "unit": "no",
   "qty": 260.0,
   "rate": 700.0,
   "amount": 182000.0
  },
  {
   "id": "EL.46",
   "pkg": "Electrical",
   "desc": "Aluminium profile w/ opal diffuser, 14.4 W/m, incl. drivers & end caps (general lighting share; cove strips in C&I).",
   "unit": "RM",
   "qty": 310.0,
   "rate": 1200.0,
   "amount": 372000.0
  },
  {
   "id": "EL.47",
   "pkg": "Electrical",
   "desc": "Per interior selection at reception/cafe/boardroom \u2014 provisional sum count.",
   "unit": "no",
   "qty": 36.0,
   "rate": 8000.0,
   "amount": 288000.0
  },
  {
   "id": "EL.48",
   "pkg": "Electrical",
   "desc": "Li-ion emergency packs on 10% fixtures per DBR.",
   "unit": "no",
   "qty": 40.0,
   "rate": 2500.0,
   "amount": 100000.0
  },
  {
   "id": "EL.49",
   "pkg": "Electrical",
   "desc": "3-circuit track w/ 12W spots at display spine + brand walls.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "EL.50",
   "pkg": "Electrical",
   "desc": "SITC modular online UPS w/ SMF battery bank, racks, input/output/bypass switchgear, SNMP.",
   "unit": "set",
   "qty": 1.0,
   "rate": 650000.0,
   "amount": 650000.0
  },
  {
   "id": "EL.51",
   "pkg": "Electrical",
   "desc": "Maintenance-free earth electrodes w/ chemical compound, test pits, interconnection.",
   "unit": "no",
   "qty": 2.0,
   "rate": 18000.0,
   "amount": 36000.0
  },
  {
   "id": "EL.52",
   "pkg": "Electrical",
   "desc": "Earth grid from pits to panel/DBs/tray/UPS incl. clamps.",
   "unit": "RM",
   "qty": 220.0,
   "rate": 220.0,
   "amount": 48400.0
  },
  {
   "id": "EL.53",
   "pkg": "Electrical",
   "desc": "Bonding of trays, duct flanges, metallic fa\u00e7ade elements per IS 732.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 40000.0,
   "amount": 40000.0
  },
  {
   "id": "EL.54",
   "pkg": "Electrical",
   "desc": "GI junction & pull boxes w/ covers at conduit runs >9 m & bends >2.",
   "unit": "no",
   "qty": 154.0,
   "rate": 450.0,
   "amount": 69300.0
  },
  {
   "id": "EL.55",
   "pkg": "Electrical",
   "desc": "Fabricated MS supports for trays/DB/panel incl. red-oxide + enamel.",
   "unit": "kg",
   "qty": 180.0,
   "rate": 95.0,
   "amount": 17100.0
  },
  {
   "id": "EL.56",
   "pkg": "Electrical",
   "desc": "Acrylic engraving for DBs/panel, ISI danger plates, 1 m electric-grade rubber mat at panel, shock chart.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 35000.0,
   "amount": 35000.0
  },
  {
   "id": "EL.57",
   "pkg": "Electrical",
   "desc": "Complete installation testing w/ calibrated instruments, recorded results, remediation.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 50000.0,
   "amount": 50000.0
  },
  {
   "id": "EL.58",
   "pkg": "Electrical",
   "desc": "Final as-builts, laminated DB circuit charts, O&M file.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 40000.0,
   "amount": 40000.0
  },
  {
   "id": "EL.59",
   "pkg": "Electrical",
   "desc": "FRLS flexible from connector to luminaires.",
   "unit": "RM",
   "qty": 600.0,
   "rate": 55.0,
   "amount": 33000.0
  },
  {
   "id": "EL.60",
   "pkg": "Electrical",
   "desc": "Dedicated combo plate: 16A switched socket + RJ45 at printer locations.",
   "unit": "pts",
   "qty": 3.0,
   "rate": 1200.0,
   "amount": 3600.0
  },
  {
   "id": "PL.01",
   "pkg": "Plumbing & PHE",
   "desc": "Concealed/surface CPVC incl. elbows/tees/unions (fittings @40% of pipe), clamps @1 m, testing 1.5\u00d7 working pressure.",
   "unit": "RM",
   "qty": 39.0,
   "rate": 180.0,
   "amount": 7020.0
  },
  {
   "id": "PL.02",
   "pkg": "Plumbing & PHE",
   "desc": "Concealed/surface CPVC incl. elbows/tees/unions (fittings @40% of pipe), clamps @1 m, testing 1.5\u00d7 working pressure.",
   "unit": "RM",
   "qty": 39.0,
   "rate": 220.0,
   "amount": 8580.0
  },
  {
   "id": "PL.03",
   "pkg": "Plumbing & PHE",
   "desc": "Concealed/surface CPVC incl. elbows/tees/unions (fittings @40% of pipe), clamps @1 m, testing 1.5\u00d7 working pressure.",
   "unit": "RM",
   "qty": 32.5,
   "rate": 280.0,
   "amount": 9100.0
  },
  {
   "id": "PL.04",
   "pkg": "Plumbing & PHE",
   "desc": "Concealed/surface CPVC incl. elbows/tees/unions (fittings @40% of pipe), clamps @1 m, testing 1.5\u00d7 working pressure.",
   "unit": "RM",
   "qty": 19.5,
   "rate": 350.0,
   "amount": 6825.0
  },
  {
   "id": "PL.05",
   "pkg": "Plumbing & PHE",
   "desc": "Brass/CPVC full-bore ball valves at branches & equipment.",
   "unit": "no",
   "qty": 14.0,
   "rate": 850.0,
   "amount": 11900.0
  },
  {
   "id": "PL.06",
   "pkg": "Plumbing & PHE",
   "desc": "Storage geysers w/ pressure relief, isolation, flexible connections.",
   "unit": "no",
   "qty": 2.0,
   "rate": 12000.0,
   "amount": 24000.0
  },
  {
   "id": "PL.07",
   "pkg": "Plumbing & PHE",
   "desc": "SITC RO+UV+chiller unit w/ inlet/drain piping & power tie-in.",
   "unit": "no",
   "qty": 2.0,
   "rate": 45000.0,
   "amount": 90000.0
  },
  {
   "id": "PL.08",
   "pkg": "Plumbing & PHE",
   "desc": "Drainage to existing stack incl. door tees/cleanouts, gradient \u22651:60, smoke/water test.",
   "unit": "RM",
   "qty": 95.0,
   "rate": 280.0,
   "amount": 26600.0
  },
  {
   "id": "PL.09",
   "pkg": "Plumbing & PHE",
   "desc": "Cockroach-trap floor drains w/ SS grating at wet service zones.",
   "unit": "no",
   "qty": 8.0,
   "rate": 2200.0,
   "amount": 17600.0
  },
  {
   "id": "PL.10",
   "pkg": "Plumbing & PHE",
   "desc": "SS grease interceptor at dishwash incl. connections.",
   "unit": "no",
   "qty": 1.0,
   "rate": 35000.0,
   "amount": 35000.0
  },
  {
   "id": "PL.11",
   "pkg": "Plumbing & PHE",
   "desc": "Core cuts through slab/walls w/ GI sleeves + fire sealant, making good.",
   "unit": "no",
   "qty": 10.0,
   "rate": 1200.0,
   "amount": 12000.0
  },
  {
   "id": "PL.12",
   "pkg": "Plumbing & PHE",
   "desc": "SITC SS-304 sinks (sound-deadened) w/ bottle traps, angle valves, mixers (KOHLER free-issue if directed).",
   "unit": "set",
   "qty": 4.0,
   "rate": 18000.0,
   "amount": 72000.0
  },
  {
   "id": "PL.13",
   "pkg": "Plumbing & PHE",
   "desc": "GI clamps @1 m, wall sleeves, flow-direction & line ID tags.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 40000.0,
   "amount": 40000.0
  },
  {
   "id": "FI.01",
   "pkg": "Fire Fighting & Detection",
   "desc": "SITC heads w/ chrome cover plates on new drops.",
   "unit": "no",
   "qty": 44.0,
   "rate": 1800.0,
   "amount": 79200.0
  },
  {
   "id": "FI.02",
   "pkg": "Fire Fighting & Detection",
   "desc": "Drain-down, relocate heads to new ceiling, re-charge & test affected zones.",
   "unit": "no",
   "qty": 62.0,
   "rate": 1200.0,
   "amount": 74400.0
  },
  {
   "id": "FI.03",
   "pkg": "Fire Fighting & Detection",
   "desc": "New ranges/drops grooved/threaded incl. fittings @45%, supports per IS, red-oxide + 2-coat PO red paint bands.",
   "unit": "RM",
   "qty": 189.0,
   "rate": 420.0,
   "amount": 79380.0
  },
  {
   "id": "FI.04",
   "pkg": "Fire Fighting & Detection",
   "desc": "New ranges/drops grooved/threaded incl. fittings @45%, supports per IS, red-oxide + 2-coat PO red paint bands.",
   "unit": "RM",
   "qty": 105.0,
   "rate": 520.0,
   "amount": 54600.0
  },
  {
   "id": "FI.05",
   "pkg": "Fire Fighting & Detection",
   "desc": "New ranges/drops grooved/threaded incl. fittings @45%, supports per IS, red-oxide + 2-coat PO red paint bands.",
   "unit": "RM",
   "qty": 63.0,
   "rate": 650.0,
   "amount": 40950.0
  },
  {
   "id": "FI.06",
   "pkg": "Fire Fighting & Detection",
   "desc": "New ranges/drops grooved/threaded incl. fittings @45%, supports per IS, red-oxide + 2-coat PO red paint bands.",
   "unit": "RM",
   "qty": 63.0,
   "rate": 850.0,
   "amount": 53550.0
  },
  {
   "id": "FI.07",
   "pkg": "Fire Fighting & Detection",
   "desc": "Tie-in at zone control: supervised butterfly valve, flow switch wired to FAS, pressure gauge, test-drain assembly.",
   "unit": "set",
   "qty": 2.0,
   "rate": 12000.0,
   "amount": 24000.0
  },
  {
   "id": "FI.08",
   "pkg": "Fire Fighting & Detection",
   "desc": "Sectional pressure test 10.5 bar, flushing, as-built marking, NOC-assist documentation.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 60000.0,
   "amount": 60000.0
  },
  {
   "id": "FI.09",
   "pkg": "Fire Fighting & Detection",
   "desc": "SITC detectors w/ bases (ceiling + above-FC void >800 mm), loop-matched to existing panel make.",
   "unit": "no",
   "qty": 74.0,
   "rate": 3500.0,
   "amount": 259000.0
  },
  {
   "id": "FI.10",
   "pkg": "Fire Fighting & Detection",
   "desc": "Addressable MCPs at exits; wall hooter-strobes per audibility.",
   "unit": "no",
   "qty": 12.0,
   "rate": 4500.0,
   "amount": 54000.0
  },
  {
   "id": "FI.11",
   "pkg": "Fire Fighting & Detection",
   "desc": "Loop wiring incl. conduit, isolator modules per zone.",
   "unit": "RM",
   "qty": 520.0,
   "rate": 120.0,
   "amount": 62400.0
  },
  {
   "id": "FI.12",
   "pkg": "Fire Fighting & Detection",
   "desc": "Loop integration to existing panel, device addressing, C&E matrix update, test certificate.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 80000.0,
   "amount": 80000.0
  },
  {
   "id": "FI.13",
   "pkg": "Fire Fighting & Detection",
   "desc": "Wall-mounted w/ SS brackets + photoluminescent signage per IS 2190.",
   "unit": "no",
   "qty": 12.0,
   "rate": 2200.0,
   "amount": 26400.0
  },
  {
   "id": "FI.14",
   "pkg": "Fire Fighting & Detection",
   "desc": "Design+SITC clean-agent flooding: cylinders, nozzles, cross-zoned detection, release panel, abort, PRD, integrity test.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 450000.0,
   "amount": 450000.0
  },
  {
   "id": "FI.15",
   "pkg": "Fire Fighting & Detection",
   "desc": "Elbows/tees/reducers/couplings as % of pipe length per IS practice.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "FI.16",
   "pkg": "Fire Fighting & Detection",
   "desc": "Supports @3 m, U-bolts, red band painting at 6 m intervals.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 80000.0,
   "amount": 80000.0
  },
  {
   "id": "NV.01",
   "pkg": "ELV / Networking / AV",
   "desc": "Supply & lay in dedicated containment, avg run 35 m per point.",
   "unit": "box",
   "qty": 17.0,
   "rate": 9000.0,
   "amount": 153000.0
  },
  {
   "id": "NV.02",
   "pkg": "ELV / Networking / AV",
   "desc": "Keystone jacks, shuttered faceplates 1/2-port, GI boxes; labelled both ends.",
   "unit": "no",
   "qty": 146.0,
   "rate": 850.0,
   "amount": 124100.0
  },
  {
   "id": "NV.03",
   "pkg": "ELV / Networking / AV",
   "desc": "Loaded panels in rack, rear managed, labelled.",
   "unit": "no",
   "qty": 7.0,
   "rate": 6500.0,
   "amount": 45500.0
  },
  {
   "id": "NV.04",
   "pkg": "ELV / Networking / AV",
   "desc": "Factory-made CAT-6A cords, both ends.",
   "unit": "no",
   "qty": 292.0,
   "rate": 350.0,
   "amount": 102200.0
  },
  {
   "id": "NV.05",
   "pkg": "ELV / Networking / AV",
   "desc": "Class-EA channel test per link, schedule + labels handover.",
   "unit": "pts",
   "qty": 146.0,
   "rate": 250.0,
   "amount": 36500.0
  },
  {
   "id": "NV.06",
   "pkg": "ELV / Networking / AV",
   "desc": "Wall/floor rack at hub w/ PDUs, fan tray, shelf, earthing.",
   "unit": "no",
   "qty": 1.0,
   "rate": 35000.0,
   "amount": 35000.0
  },
  {
   "id": "NV.07",
   "pkg": "ELV / Networking / AV",
   "desc": "Riser uplink to building MDF incl. splicing & OTDR test.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 85000.0,
   "amount": 85000.0
  },
  {
   "id": "NV.08",
   "pkg": "ELV / Networking / AV",
   "desc": "SITC ceiling APs w/ mounts, PoE feed, controller licences, RF heat-map report.",
   "unit": "no",
   "qty": 9.0,
   "rate": 28000.0,
   "amount": 252000.0
  },
  {
   "id": "NV.09",
   "pkg": "ELV / Networking / AV",
   "desc": "SITC w/ mounts; entries/reception/corridors/cafe per privacy SOP.",
   "unit": "no",
   "qty": 14.0,
   "rate": 12000.0,
   "amount": 168000.0
  },
  {
   "id": "NV.10",
   "pkg": "ELV / Networking / AV",
   "desc": "30-day @15 fps retention, VMS licences, security-desk monitor.",
   "unit": "set",
   "qty": 1.0,
   "rate": 150000.0,
   "amount": 150000.0
  },
  {
   "id": "NV.11",
   "pkg": "ELV / Networking / AV",
   "desc": "Complete ACS kit per door, fail-safe wiring to FAS, integration to client platform.",
   "unit": "door",
   "qty": 7.0,
   "rate": 35000.0,
   "amount": 245000.0
  },
  {
   "id": "NV.12",
   "pkg": "ELV / Networking / AV",
   "desc": "100 V line speakers, FRLS speaker cable, zone integration with building EVAC + BGM source at cafe.",
   "unit": "no",
   "qty": 46.0,
   "rate": 3500.0,
   "amount": 161000.0
  },
  {
   "id": "NV.13",
   "pkg": "ELV / Networking / AV",
   "desc": "~120 points: VRF gateway, TFA control, energy meters, FAS/ACS soft integration, graphics.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 250000.0,
   "amount": 250000.0
  },
  {
   "id": "NV.14",
   "pkg": "ELV / Networking / AV",
   "desc": "Looped sense cable at pantry/TFA/shafts w/ locating controller, BMS output.",
   "unit": "RM",
   "qty": 80.0,
   "rate": 1800.0,
   "amount": 144000.0
  },
  {
   "id": "NV.15",
   "pkg": "ELV / Networking / AV",
   "desc": "Ultrasonic units at cafe/store/voids, timer programmed.",
   "unit": "no",
   "qty": 8.0,
   "rate": 8000.0,
   "amount": 64000.0
  },
  {
   "id": "NV.16",
   "pkg": "ELV / Networking / AV",
   "desc": "SITC display in stone niche, camera bar, 2 mic pods in raft, DSP+amp, cabling, programming.",
   "unit": "set",
   "qty": 1.0,
   "rate": 1200000.0,
   "amount": 1200000.0
  },
  {
   "id": "NV.17",
   "pkg": "ELV / Networking / AV",
   "desc": "Wall displays w/ mounts + HDMI/USB-C plates at 4 MRs.",
   "unit": "no",
   "qty": 4.0,
   "rate": 120000.0,
   "amount": 480000.0
  },
  {
   "id": "NV.18",
   "pkg": "ELV / Networking / AV",
   "desc": "2 menu displays + BGM speaker zoning tie-in.",
   "unit": "lot",
   "qty": 1.0,
   "rate": 300000.0,
   "amount": 300000.0
  },
  {
   "id": "NV.19",
   "pkg": "ELV / Networking / AV",
   "desc": "Dedicated ELV conduit where tray not present incl. accessories (segregation from power \u2265300 mm).",
   "unit": "RM",
   "qty": 300.0,
   "rate": 120.0,
   "amount": 36000.0
  },
  {
   "id": "NV.20",
   "pkg": "ELV / Networking / AV",
   "desc": "12V SMPS units + 2C\u00d71.5 power runs where PoE not used; RG-59 nil (IP).",
   "unit": "lot",
   "qty": 1.0,
   "rate": 40000.0,
   "amount": 40000.0
  },
  {
   "id": "NV.21",
   "pkg": "ELV / Networking / AV",
   "desc": "Zone speaker cabling in conduit.",
   "unit": "RM",
   "qty": 400.0,
   "rate": 85.0,
   "amount": 34000.0
  }
 ],
 "totalAmount": 39381184.0,
 "packages": {
  "Civil & Interiors": 22002930.0,
  "HVAC / Mechanical": 6939744.0,
  "Electrical": 4344705.0,
  "Plumbing & PHE": 360625.0,
  "Fire Fighting & Detection": 1627880.0,
  "ELV / Networking / AV": 4105300.0
 }
};
(function(g){g.PROJ_BOQ=BOQ;})(typeof window!=="undefined"?window:globalThis);
if(typeof module!=="undefined"&&module.exports)module.exports=BOQ;
})();
