// ===================================================================
// DnB-OS . platform/track/project/skf_po.js . THE PO REGISTER PACK
// SKF Pune . the 30 canonical purchase orders, one object each.
// GENERATED by data/skf/po/gen_po_module.py from the PO extracts in
// data/skf/po/. Never hand edit: fix the generator or a PO file and
// re-run. value is the PO total incl GST, taxable is ex GST. The
// report totals recompute from this list at render, never hard coded.
//
// The Vizdom export prints the latest revision date as the Order Date,
// so all 30 read 14 Jul 2026 and a real placement date cannot be read.
// newlyPlaced marks the six the weekly flags as the 14 Jul batch.
// head maps each PO to a BOQ letter head for the committed vs BOQ view;
// PRE is site preliminaries and carries no BOQ budget.
// ===================================================================

;(function (root) {

var PO = {
  project: "SKF Pune",
  asOf: "2026-07-20",
  stampNote: "Vizdom prints the latest revision date as the Order Date, so all 30 POs read 14 Jul 2026. The real placement dates are unknown and release slip cannot be computed.",
  committed: 61993631.2,           // sum of all 30 PO totals, incl GST
  committedTaxable: 52795629.9,   // sum ex GST, for the vs BOQ view
  batch: ["FSL2026272014", "FSL2026272068", "FSL2026272161", "FSL2026272187", "FSL2026272195", "FSL2026272212"],
  batchValue: 15435427.0,

  boqHeads: [
    { head: "A", name: "Architectural and interiors", bcs: 16128074 },
    { head: "B", name: "Furniture and furnishing", bcs: 10649815 },
    { head: "C", name: "Electrical works", bcs: 13474596 },
    { head: "D", name: "HVAC", bcs: 9532727 },
    { head: "E", name: "Data network", bcs: 4237402 },
    { head: "F", name: "PHE works", bcs: 334339 },
    { head: "G", name: "FLSS works", bcs: 5181286 },
    { head: "PRE", name: "Site preliminaries", bcs: null },
  ],

  pos: [
    { po: "FSL2026272008", rev: 8, vendor: "RAZA ENTERPRISES", head: "A", headSub: "A2 Interior works",
      scope: "Gypsum partitions 735 sqm and ceiling", value: 3969890.0, taxable: 3364313.0, delivery: "2026-06-30", deliveryRaw: "June 30, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Interior gypsum works: 735 sqm full height gypsum partitions with Rockwool insulation, 550 sqm plain gypsum ceiling, acoustic wooden grid, fire rated and designer laminate ceilings, column cladding, ply backing and ceiling trap doors" },
    { po: "FSL2026272011", rev: 3, vendor: "PCI Pest Control Pvt Ltd", head: "A", headSub: "A1 Civil works",
      scope: "Anti termite and pest control, 10 yr warranty", value: 64900.0, taxable: 55000.0, delivery: "2026-06-10", deliveryRaw: "June 10, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Pest control and anti-termite treatment for 22000 sqft (PCI, 2 service rounds, 10 year warranty on stamp paper)" },
    { po: "FSL2026272014", rev: 6, vendor: "HINDUSTAN ASSOCIATES", head: "A", headSub: "A2 Interior works",
      scope: "Kajaria vitrified tiles, 4,495 sqft", value: 443208.0, taxable: 359600.0, delivery: "2026-06-11", deliveryRaw: "June 11, 2026",
      purchaser: "Krishna Gupta", newlyPlaced: true, deliveryStatus: "on site per DPR", fullScope: "Tiles Kajaria 1200x600 matt, 4495 sqft" },
    { po: "FSL2026272024", rev: 3, vendor: "M.N.Electricals", head: "G", headSub: "G1 Fire sprinklers",
      scope: "Fire sprinkler and drencher system", value: 1817757.0, taxable: 1540472.0, delivery: "2026-06-16", deliveryRaw: "June 16, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Fire sprinkler and drencher system: GI 'C' class piping 25-150 NB (~782 mtrs) plus 210 mtrs drencher header, ~325 sprinklers (concealed/pendant/upright), flexible and hard drops, butterfly/gate/ball/NRV valves, flow switches, deluge valve set, drencher nozzles, pressure testing and commissioning" },
    { po: "FSL2026272027", rev: 3, vendor: "NATIONAL INFRA SOLUTIONS", head: "A", headSub: "A1 Civil works",
      scope: "Civil works package, plaster and screed", value: 1872944.0, taxable: 1587240.0, delivery: "2026-06-16", deliveryRaw: "June 16, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Civil works package: cement plastering (~429 sqm), POP punning (400 sqm), gypsum plaster (475 sqm), 150mm AAC block walls (272 sqm), and vitrified tile flooring with epoxy grouting (800 sqm)" },
    { po: "FSL2026272058", rev: 2, vendor: "Nikhil Balu Khamkar", head: "PRE", headSub: "Site preliminaries",
      scope: "Material shifting and transport", value: 35000.0, taxable: 35000.0, delivery: "2026-06-21", deliveryRaw: "June 21, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Material shifting charges, 1 transportation trip (no tax)" },
    { po: "FSL2026272062", rev: 3, vendor: "METRO AIR CONDITIONER", head: "D", headSub: "D HVAC",
      scope: "Complete HVAC package, SITC", value: 11209561.0, taxable: 9499627.7, delivery: "2026-06-22", deliveryRaw: "June 22, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Complete HVAC package (SITC as per attached BoQ, lumpsum lines): HVAC low side works, VAV units, and VRF air-conditioning system incl. outdoor units, piping, BMS-compatible controls and commissioning" },
    { po: "FSL2026272067", rev: 3, vendor: "S.S. Furniture & Interior", head: "PRE", headSub: "Site preliminaries",
      scope: "Site team chairs and tables", value: 12242.5, taxable: 10375.0, delivery: "2026-06-22", deliveryRaw: "June 22, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Site imprest furniture: 7 plastic chairs and 5 plastic tables" },
    { po: "FSL2026272068", rev: 5, vendor: "Arselex Engineering Private Limited", head: "C", headSub: "C1 Electrical works",
      scope: "Complete electrical work, SITC per BOQ", value: 11800000.0, taxable: 10000000.0, delivery: "2026-06-22", deliveryRaw: "June 22, 2026",
      purchaser: "Rahul Singh", newlyPlaced: true, deliveryStatus: "per schedule", fullScope: "Complete electrical work SITC per annexure BOQ, line-item billing" },
    { po: "FSL2026272072", rev: 8, vendor: "POWER ZONE", head: "C", headSub: "C2 Light fixtures",
      scope: "Philips light fixtures", value: 1216238.0, taxable: 1030710.0, delivery: "2026-06-23", deliveryRaw: "June 23, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Philips light fixtures: 145 hanging cylindrical 15W lights, 296 downlights 15W, 190 linear 5ft lights, 12 panel lights 2x2 30W (all 4000K white)" },
    { po: "FSL2026272074", rev: 1, vendor: "CHETTAK INTEGRATED SECURITY PRIVATE LIMITED", head: "PRE", headSub: "Site preliminaries",
      scope: "Security, 2 guards, 2 months", value: 129800.0, taxable: 110000.0, delivery: "2026-06-23", deliveryRaw: "June 23, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Security guard deployment at site: 2 guards (1 day, 1 night) for 2 months at 25000 per person per month, plus 5% maintenance charges" },
    { po: "FSL2026272076", rev: 0, vendor: "BHARATH FIRE PROTECTORS", head: "A", headSub: "A2 Interior works",
      scope: "Metal fire doors, 3 nos", value: 93998.0, taxable: 79659.0, delivery: "2026-06-23", deliveryRaw: "June 23, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Supply and installation of metal fire doors 1000x2100mm single leaf with D handle (Shakti Horman, 3 nos) plus transport/loading/unloading to site (1 trip)" },
    { po: "FSL2026272077", rev: 0, vendor: "A.R Khan", head: "F", headSub: "F1 Plumbing works",
      scope: "Internal plumbing, 16 toilets", value: 600000.0, taxable: 600000.0, delivery: "2026-06-23", deliveryRaw: "June 23, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Complete internal plumbing work for toilets: concealed/exposed water supply and waste piping plus supply and fixing of sanitary fixtures for 16 toilets, 8 urinals, 13 wash basins, 2 bathrooms, all pantry sinks with RO and geyser points, incl. testing and commissioning (lumpsum 1 LMSM)" },
    { po: "FSL2026272078", rev: 0, vendor: "SAFEX FIRE SERVICES LTD", head: "G", headSub: "G4 Fire extinguishers",
      scope: "Fire extinguishers with stands", value: 317302.0, taxable: 268900.0, delivery: "2026-06-23", deliveryRaw: "June 23, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Safex fire extinguishers: 4.5kg CO2 (5 nos), 6kg ABC stored pressure (19 nos), ceiling mounted clean agent HFC 15kg (1 no) and 10kg (6 nos), floor stands (24 nos)" },
    { po: "FSL2026272102", rev: 2, vendor: "SD ENTERPRISES", head: "PRE", headSub: "Site preliminaries",
      scope: "Mathadi labour", value: 1298000.0, taxable: 1100000.0, delivery: "2026-06-26", deliveryRaw: "June 26, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Mathadi labour charges as per attached annexure (lump sum)" },
    { po: "FSL2026272121", rev: 2, vendor: "SUSTAINABLE CLEANING SOLUTIONS", head: "PRE", headSub: "Site preliminaries",
      scope: "Housekeeping, 2 months", value: 63720.0, taxable: 54000.0, delivery: "2026-06-30", deliveryRaw: "June 30, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Housekeeping service at site: 2 persons for 30 days (10:00 AM to 6:00 PM), Rs 1800 per day" },
    { po: "FSL2026272122", rev: 2, vendor: "Jyoti Enterprises", head: "A", headSub: "A2 Interior works",
      scope: "Painting, acrylic emulsion", value: 964060.0, taxable: 817000.0, delivery: "2026-06-30", deliveryRaw: "June 30, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Painting works: acrylic emulsion paint on true ceiling/bulkheads (2100 sqm) and premium low-VOC acrylic emulsion paint with putty and primer on walls/partitions/columns (2200 sqm)" },
    { po: "FSL2026272123", rev: 2, vendor: "Impact Enterprises", head: "PRE", headSub: "Site preliminaries",
      scope: "Site safety and fire consumables", value: 29827.3, taxable: 25685.0, delivery: "2026-07-01", deliveryRaw: "July 1, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Site safety and fire fighting consumables: Karam helmets (7), 4kg ABC fire extinguishers (5), fire bucket stands (3) and buckets (6), roto cones (20), chain link (100 rmt), hand gloves (60), safety goggles (15), safety jackets (5), APS shoes (1)" },
    { po: "FSL2026272128", rev: 6, vendor: "Triangular Infosolutions Private Limited", head: "C", headSub: "C3 UPS",
      scope: "UPS 80, 20 and 6 KVA", value: 2124000.0, taxable: 1800000.0, delivery: "2026-07-01", deliveryRaw: "July 1, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "UPS package: 80 KVA, 20 KVA and 6 KVA IGBT modular UPS (N+1), VRLA SMF battery sets with racks, copper DC/AC cabling with glands and lugs, battery room ventilation (pre-filter, GI duct)" },
    { po: "FSL2026272129", rev: 11, vendor: "Featherlite Office Systems (P) Limited", head: "B", headSub: "B Furniture",
      scope: "Modular furniture, 305 workstations, 414 chairs", value: 9148057.4, taxable: 7752591.0, delivery: "2026-07-01", deliveryRaw: "July 1, 2026",
      purchaser: "Krishna Gupta", newlyPlaced: false, deliveryStatus: null, fullScope: "Featherlite office furniture: 305 linear workstations with pedestals, 364 medium back and 50 high back mesh chairs, meeting/conference tables (4 to 12 pax), 6 cabin tables, 20 prelam storages, cafe/booth/high tables and multipurpose rack" },
    { po: "FSL2026272135", rev: 8, vendor: "AR INTERIOR", head: "A", headSub: "A Interiors and blinds",
      scope: "Roller blinds, skirting and panelling", value: 2618469.6, taxable: 2219042.0, delivery: "2026-07-01", deliveryRaw: "July 1, 2026",
      purchaser: "Krishna Gupta", newlyPlaced: false, deliveryStatus: null, fullScope: "Interior finishing: 230 rmt roller blind pelmets, 800 rmt aluminium skirting, 700 rmt corner guards, 460 sqm laminate/ply panelling with and without frame, 250 sqm ply backing, 230 rmt laminate finished window sills" },
    { po: "FSL2026272161", rev: 4, vendor: "M.N.Electricals", head: "G", headSub: "G Fire detection and ELV",
      scope: "Fire alarm, PA, rodent, WLD, CCTV", value: 2451810.0, taxable: 2077805.0, delivery: "2026-07-07", deliveryRaw: "July 7, 2026",
      purchaser: "Rahul Singh", newlyPlaced: true, deliveryStatus: "7 Jul, follow up", fullScope: "Fire alarm (Honeywell Notifier UL) + PA system (Bosch) + rodent repellent + water leak detection + CCTV NVR 32ch + 25 dome cameras + switches" },
    { po: "FSL2026272165", rev: 5, vendor: "AYUSHRI ASSOCIATES PRIVATE LIMITED", head: "A", headSub: "A2 Interior works",
      scope: "Acoustic call booths, 2 plus 2", value: 1286200.0, taxable: 1090000.0, delivery: "2026-07-07", deliveryRaw: "July 7, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Acoustic call booths: 2 single seater call booths and 2 double seater call booths (AIPL make) plus transportation to site" },
    { po: "FSL2026272167", rev: 4, vendor: "WELSPUN GLOBAL BRANDS LIMITED", head: "B", headSub: "B1 Carpet flooring",
      scope: "Nylon carpet tiles, 1270 plus 225 sqm", value: 1881144.0, taxable: 1771575.0, delivery: "2026-08-11", deliveryRaw: "Aug. 11, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Supply and installation of 100% nylon tufted textured loop carpet tiles 500x500mm (Welspun, 1270 sqmt + 225 sqmt) including installation charges" },
    { po: "FSL2026272180", rev: 7, vendor: "Triangular Infosolutions Private Limited", head: "E", headSub: "E1 Passive networking",
      scope: "Passive networking, Cat6A", value: 5254233.4, taxable: 4452740.2, delivery: "2026-07-09", deliveryRaw: "July 9, 2026",
      purchaser: "Krishna Gupta", newlyPlaced: false, deliveryStatus: null, fullScope: "Passive networking: Cat6A UTP cable (154 boxes), 801 node cable laying, termination and fluke testing, OM4 fiber cable, panels and patch cords, 24U/42U racks with PDUs and cable organisers, CCTV/WiFi poles and installation services" },
    { po: "FSL2026272187", rev: 0, vendor: "ALDON STEEL PVT LTD", head: "B", headSub: "B3 Loose furniture",
      scope: "Compactor storage cabinets and fitting", value: 252756.0, taxable: 214200.0, delivery: "2026-07-09", deliveryRaw: "July 9, 2026",
      purchaser: "Rahul Singh", newlyPlaced: true, deliveryStatus: "9 Jul, overdue", fullScope: "Compactor cabinets SFF/DFM/SFM + fitting + transport (Aldon)" },
    { po: "FSL2026272193", rev: 0, vendor: "EUROCEIL SYSTEMS PRIVATE LIMITED", head: "A", headSub: "A2 Interior works",
      scope: "Stretch fabric ceiling, 377 sqft", value: 413720.0, taxable: 350610.0, delivery: "2026-07-10", deliveryRaw: "July 10, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Stretched fabric ceiling: supply and installation of Euroceil premium translucent PVC membrane (377 sqft) with EC Supreme bar LED and drivers (377 sqft) including sheet and LED installation charges" },
    { po: "FSL2026272194", rev: 0, vendor: "UNITED ACCESS FLOORS PRIVATE LIMITED", head: "A", headSub: "A2 Interior works",
      scope: "Raised access flooring", value: 137140.0, taxable: 116220.0, delivery: "2026-07-10", deliveryRaw: "July 10, 2026",
      purchaser: "Rahul Singh", newlyPlaced: false, deliveryStatus: null, fullScope: "Providing and fixing antistatic laminate raised access flooring, 300mm height, 600x600mm removable steel cementitious-filled panels (Unitile/AET), 30 sqm" },
    { po: "FSL2026272195", rev: 0, vendor: "WESTCHEM TECHNOLOGIES PRIVATE LIMITED", head: "A", headSub: "A2 Interior works",
      scope: "Epoxy flooring, anti static", value: 91173.0, taxable: 77265.0, delivery: "2026-07-10", deliveryRaw: "July 10, 2026",
      purchaser: "Rahul Singh", newlyPlaced: true, deliveryStatus: "10 Jul, overdue", fullScope: "Epoxy flooring: anti-static self-leveling in AHU/electrical/UPS/hub/battery/server rooms 30 sqm + colored self-leveling 15 sqm" },
    { po: "FSL2026272212", rev: 2, vendor: "Pacific Product & Solutions", head: "A", headSub: "A2 Interior works",
      scope: "Toilet cubicles, Stylam 12 mm, 16 nos", value: 396480.0, taxable: 336000.0, delivery: "2026-07-13", deliveryRaw: "July 13, 2026",
      purchaser: "Rahul Singh", newlyPlaced: true, deliveryStatus: "13 Jul, overdue", fullScope: "Toilet cubicles Stylam 12mm, 16 nos, restroom skylight model" },
  ]
};

root.TRACK_PO_SKF = PO;
if (typeof module !== "undefined") module.exports = PO;

})(typeof window !== "undefined" ? window : globalThis);
