// ===================================================================
// DnB-OS . platform/track/project/skf_absorb1.js . ABSORB BATCH 1
// GENERATED 16 Jul 2026 from four files Sourabh dropped in chat:
// WhatsApp chat export (iPhone), GFC layout DXF, site schedule xlsx,
// material tracker xlsx. xlsx were read offline (no browser reader yet),
// every fact carries its source and confidence. Do not edit by hand,
// regenerate from the data folder.
// ===================================================================

;(function (root) {

const ABSORB = {
  day: "2026-07-16",
  zones: ["Reception + Waiting Area","Board Room 20 Pax","Cabin 01","Cabin 02","Cabin 03","Cabin 04","Cabin 05","Cabin 06","Manager Cabin","Meeting Room 4 Pax","Visiting Meeting Room 4 Pax","Meeting Room 6 Pax","Meeting Room 8 Pax","Meeting Room 12 Pax","Workstation Area","Collab Breakout Area","Phone Booth Focus Pod","Cafeteria","Dry Pantry","Hub Room","Server Room","Battery Room","UPS & Electrical Room","LV Room","AHU Room 1","AHU Room 2","Compactor Room","Ladies Restroom","Gents Restroom","Male Wellness Room","Female Wellness Room","Storage","Elevator Lobby","Passage","Balcony","Refuge Area","Ramp"],
  files: [
 {
  "name": "_chat.txt",
  "size": 27378,
  "at": "2026-07-16",
  "verdict": {
   "type": "dpr_whatsapp",
   "confidence": "high",
   "label": "DPR (WhatsApp)",
   "why": "iPhone chat export, 179 messages, 122 photos, plus 123 jpg files alongside"
  }
 },
 {
  "name": "SKF_R1_GFC_FINAL LAYOUT.dxf",
  "size": 58888104,
  "at": "2026-07-16",
  "verdict": {
   "type": "cad_layout",
   "confidence": "high",
   "label": "CAD layout",
   "why": "GFC DXF landed locally, 37 zone names extracted for the twin base"
  }
 },
 {
  "name": "Ptoject Schedule & Milestone - SKF.xlsx",
  "size": 123214,
  "at": "2026-07-16",
  "verdict": {
   "type": "schedule_xlsx",
   "confidence": "medium",
   "label": "Site schedule (xlsx)",
   "why": "read offline: milestones, plan and actual columns, long lead list"
  }
 },
 {
  "name": "SKF_Material Tracker.xlsx",
  "size": 185005,
  "at": "2026-07-16",
  "verdict": {
   "type": "material_xlsx",
   "confidence": "medium",
   "label": "Material tracker (xlsx)",
   "why": "read offline: 37 long lead items, 52 procurement closure lines"
  }
 }
],
  queries: [
 {
  "about": "site schedule",
  "question": "The schedule xlsx carries planned and actual dates. The tracking baseline still comes from the Planning Engine export. Confirm the xlsx stays reference only.",
  "blocking": false
 },
 {
  "about": "material receipts",
  "question": "37 long lead items carry expected receipt dates but GRN folder 03.4 is still empty. Expectations are not proof. Start dropping GRNs.",
  "blocking": false
 },
 {
  "about": "photo zone pins",
  "question": "122 site photos came with the chat. They need zone pins once the Twin lights up. Approve auto pinning by caption and timestamp where possible.",
  "blocking": false
 }
],
  closes: [
 {
  "about": "CAD layout",
  "answer": "Landed 16 Jul as a local file (58.9 MB). 37 zone names extracted into the twin base. Full geometry work is the Twin step."
 },
 {
  "about": "DPR WhatsApp",
  "answer": "Full chat export landed 16 Jul: 179 messages, 122 photos, 4 Jul to 16 Jul. Routine confirmed as one export drop, not one zip per day."
 }
],
  facts: [
  {"kind":"context","source":"cad","day":"2026-07-16","text":"GFC layout SKF Pune, 7th floor, Tower 03 Mall of Millennium. Carpet area 26,484 sqft. GFC dated 23.06.2026.","confidence":"high","zone":null,"task":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-03","text":"Milestone: Project Initiation","start":"2026-06-03","finish":"2026-06-08","status":null,"confidence":"medium","zone":null,"task":"Project Initiation","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-08","text":"Milestone: Site Prep","start":"2026-06-08","finish":"2026-06-14","status":null,"confidence":"medium","zone":null,"task":"Site Prep","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-24","text":"Milestone: Civil Works","start":"2026-06-24","finish":"2026-07-21","status":null,"confidence":"medium","zone":null,"task":"Civil Works","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-24","text":"Milestone: Masonry","start":"2026-06-24","finish":"2026-07-03","status":null,"confidence":"medium","zone":null,"task":"Masonry","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-13","text":"Milestone: Flooring","start":"2026-07-13","finish":"2026-07-21","status":null,"confidence":"medium","zone":null,"task":"Flooring","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-27","text":"Milestone: Sprinkler","start":"2026-06-27","finish":"2026-07-21","status":null,"confidence":"medium","zone":null,"task":"Sprinkler","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-04","text":"Milestone: Low Side","start":"2026-07-04","finish":"2026-07-22","status":null,"confidence":"medium","zone":null,"task":"Low Side","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-05","text":"Milestone: High Side","start":"2026-07-05","finish":"2026-07-31","status":null,"confidence":"medium","zone":null,"task":"High Side","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-29","text":"Milestone: Drainage","start":"2026-06-29","finish":"2026-07-21","status":null,"confidence":"medium","zone":null,"task":"Drainage","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-18","text":"Milestone: Fittings & Fixtures","start":"2026-07-18","finish":"2026-07-26","status":null,"confidence":"medium","zone":null,"task":"Fittings & Fixtures","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-02","text":"Milestone: Containment","start":"2026-07-02","finish":"2026-08-06","status":null,"confidence":"medium","zone":null,"task":"Containment","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-21","text":"Milestone: High Side","start":"2026-07-21","finish":"2026-08-02","status":null,"confidence":"medium","zone":null,"task":"High Side","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-11","text":"Milestone: ELV Instalations","start":"2026-07-11","finish":"2026-07-29","status":null,"confidence":"medium","zone":null,"task":"ELV Instalations","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-11","text":"Milestone: FAS & PA","start":"2026-07-11","finish":"2026-07-29","status":null,"confidence":"medium","zone":null,"task":"FAS & PA","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-18","text":"Milestone: Access/CCTV","start":"2026-07-18","finish":"2026-07-29","status":null,"confidence":"medium","zone":null,"task":"Access/CCTV","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-24","text":"Milestone: Interiors & Finishes Works","start":"2026-06-24","finish":"2026-07-29","status":null,"confidence":"medium","zone":null,"task":"Interiors & Finishes Works","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-06-24","text":"Milestone: Carpentry","start":"2026-06-24","finish":"2026-07-19","status":null,"confidence":"medium","zone":null,"task":"Carpentry","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-11","text":"Milestone: Celing Works","start":"2026-07-11","finish":"2026-08-07","status":null,"confidence":"medium","zone":null,"task":"Celing Works","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-20","text":"Milestone: Flooring","start":"2026-07-20","finish":"2026-08-03","status":null,"confidence":"medium","zone":null,"task":"Flooring","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-29","text":"Milestone: Wall","start":"2026-07-29","finish":"2026-08-07","status":null,"confidence":"medium","zone":null,"task":"Wall","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-18","text":"Milestone: Modular Partition Glass","start":"2026-07-18","finish":"2026-07-29","status":null,"confidence":"medium","zone":null,"task":"Modular Partition Glass","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-28","text":"Milestone: Furniture","start":"2026-07-28","finish":"2026-08-09","status":null,"confidence":"medium","zone":null,"task":"Furniture","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-08-02","text":"Milestone: Networking","start":"2026-08-02","finish":"2026-08-12","status":null,"confidence":"medium","zone":null,"task":"Networking","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-07-28","text":"Milestone: Miscellaneous","start":"2026-07-28","finish":"2026-08-08","status":null,"confidence":"medium","zone":null,"task":"Miscellaneous","flag":null},
  {"kind":"milestone","source":"schedule","day":"2026-08-05","text":"Milestone: Final Snags & Handover","start":"2026-08-05","finish":"2026-08-14","status":null,"confidence":"medium","zone":null,"task":"Final Snags & Handover","flag":null},
  {"kind":"achieved","source":"schedule","day":"2026-06-16","text":"Site Marking & preperation works reported actual start 2026-06-07 finish 2026-06-16","task":"Site Marking & preperation works","category":"Site Prep","confidence":"medium","zone":null,"flag":"actual from the site schedule xlsx, no visual proof attached yet"},
  {"kind":"achieved","source":"schedule","day":"2026-06-12","text":"Temperory Power reported actual start 2026-06-11 finish 2026-06-12","task":"Temperory Power","category":null,"confidence":"medium","zone":null,"flag":"actual from the site schedule xlsx, no visual proof attached yet"},
  {"kind":"achieved","source":"schedule","day":"2026-06-16","text":"Blockwork , AAC Blocks & Plastering reported actual start 2026-06-16","task":"Blockwork , AAC Blocks & Plastering","category":"Civil Works","confidence":"medium","zone":null,"flag":"actual from the site schedule xlsx, no visual proof attached yet"},
  {"kind":"achieved","source":"schedule","day":"2026-06-16","text":"Workstation Linear Sharing/Non sharing - 1500mm X 750mm reported actual start 2026-06-16","task":"Workstation Linear Sharing/Non sharing - 1500mm X 750mm","category":"Furniture","confidence":"medium","zone":null,"flag":"actual from the site schedule xlsx, no visual proof attached yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-28","text":"Ambient Lights . Long Lead . Need to change Brand","task":"Ambient Lights","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-30","text":"Modular Furniture . Long Lead . Completed","task":"Modular Furniture","receiptExpected":"2026-07-28","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-30","text":"Carpets . Long Lead . Apprval pending from Design","task":"Carpets","receiptExpected":"2026-07-21","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-30","text":"Networking . Long Lead . 2026-02-07","task":"Networking","receiptExpected":"2026-07-21","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Call Booth . Long Lead . Quote Finalization","task":"Call Booth","receiptExpected":"2026-07-23","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-01","text":"Chairs - workstation . Long Lead . Done","task":"Chairs - workstation","receiptExpected":"2026-07-29","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-01","text":"Compactor . Long Lead . Quote Finalization","task":"Compactor","receiptExpected":"2026-07-18","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-01","text":"Fire Door . Long Lead . Need give MEA","task":"Fire Door","receiptExpected":"2026-07-22","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-01","text":"Toilet Cubicles . Long Lead . Quote Finalization","task":"Toilet Cubicles","receiptExpected":"2026-07-22","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-01","text":"Loose Furniture . Long Lead . Quote Finalization","task":"Loose Furniture","receiptExpected":"2026-07-22","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-29","text":"Turnkey 2 - Complete Carpentry Work . Long Lead . Quote Finalization","task":"Turnkey 2 - Complete Carpentry Work","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-29","text":"Fire Extinguisher with Stand . Long Lead . Done","task":"Fire Extinguisher with Stand","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-06-29","text":"Acoustic Panels and Acoustic Baffle/Cloud Ceiling . Long Lead . 5 Jul/Approval Pending from design","task":"Acoustic Panels and Acoustic Baffle/Cloud Ceiling","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-03","text":"UPS . Long Lead . Quote Finalization","task":"UPS","receiptExpected":"2026-07-31","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Stretch Lights . Short Lead . Quote Finalization","task":"Stretch Lights","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Sanitary Fixtures - Supply . Short Lead . Selection Pending from design","task":"Sanitary Fixtures - Supply","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Washroom Accesories . Short Lead . Selection Pending from design","task":"Washroom Accesories","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Blinds . Short Lead . Selection Pending from design","task":"Blinds","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"ACS/CCTV . Short Lead . Quote Finalization","task":"ACS/CCTV","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"WD/RR . Short Lead . Quote Finalization","task":"WD/RR","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-05","text":"Flutted Panels - Supply . Short Lead . QTY from Designer","task":"Flutted Panels - Supply","receiptExpected":"2026-07-20","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-08","text":"Glass Partition,Glass Doors,Lacquerd Glass,Mirror and Urnial Partiton . Short Lead . Quote Finalization","task":"Glass Partition,Glass Doors,Lacquerd Glass,Mirror and Urnial Partiton","receiptExpected":"2026-07-23","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-09","text":"Raised flooring . Short Lead . qty Operation","task":"Raised flooring","receiptExpected":"2026-07-24","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Decorative Lights . Short Lead","task":"Decorative Lights","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Fabrication Work . Short Lead","task":"Fabrication Work","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Fire Exit Signages - Prolite . Short Lead","task":"Fire Exit Signages - Prolite","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Epoxy Flooring . Short Lead","task":"Epoxy Flooring","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Artificial Planters . Short Lead . Selection","task":"Artificial Planters","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Chess Board with Table . Short Lead . Online Order","task":"Chess Board with Table","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-10","text":"Graphics,Sighnage and Films/Suncontrol . Short Lead","task":"Graphics,Sighnage and Films/Suncontrol","receiptExpected":"2026-07-25","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Dustbin - Supply . Short Lead","task":"Dustbin - Supply","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Entrance Mat . Short Lead","task":"Entrance Mat","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Hanging Frames . Short Lead","task":"Hanging Frames","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Mattress 7 Inch . Short Lead","task":"Mattress 7 Inch","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Metal Key Storage . Short Lead","task":"Metal Key Storage","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Skriting,Corner Guard and Profiles - Supply . Short Lead . Colour Finalization","task":"Skriting,Corner Guard and Profiles - Supply","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"material","source":"material_tracker","day":"2026-07-15","text":"Server Rack . Short Lead . In Networking Scope","task":"Server Rack","receiptExpected":"2026-07-26","confidence":"medium","zone":null,"flag":"receipt date is an expectation, no GRN yet"},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-10","text":"Table and Chair for Site Team . Immediate","task":"Table and Chair for Site Team","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-14","text":"Pest Control . Immediate","task":"Pest Control","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-15","text":"Electrical Work . Immediate","task":"Electrical Work","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Security Staff . Immediate","task":"Security Staff","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-19","text":"Turnkey - Civil,Gypsum,Paint and Initial Carpentry . Immediate","task":"Turnkey - Civil,Gypsum,Paint and Initial Carpentry","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-15","text":"FA/PA . Immediate","task":"FA/PA","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Fire Sprinkler . Immediate","task":"Fire Sprinkler","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Hvac . Immediate","task":"Hvac","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-09","text":"Tiles - Supply . Immediate","task":"Tiles - Supply","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-10","text":"Plumbing . Immediate","task":"Plumbing","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-10","text":"UPS . Immediate","task":"UPS","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-11","text":"Water Proofing . Immediate","task":"Water Proofing","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-12","text":"Ambient Lights . Long Lead Items","task":"Ambient Lights","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Carpets . Long Lead Items","task":"Carpets","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Modular Furniture . Long Lead Items","task":"Modular Furniture","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Networking . Long Lead Items","task":"Networking","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Call Booth . Long Lead Items","task":"Call Booth","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Chairs - workstation . Long Lead Items","task":"Chairs - workstation","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Compactor . Long Lead Items","task":"Compactor","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Fire Door . Long Lead Items","task":"Fire Door","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-21","text":"Toilet Cubicles . Long Lead Items","task":"Toilet Cubicles","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-22","text":"Loose Furniture . Long Lead Items","task":"Loose Furniture","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-16","text":"Turnkey 2 - Complete Carpentry Work . Long Lead Items","task":"Turnkey 2 - Complete Carpentry Work","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-17","text":"Fire Extinguisher with Stand . Long Lead Items","task":"Fire Extinguisher with Stand","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-17","text":"Acoustic Panels and Acoustic Baffle/Cloud Ceiling . Long Lead Items","task":"Acoustic Panels and Acoustic Baffle/Cloud Ceiling","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-17","text":"Stretch Lights . Long Lead Items","task":"Stretch Lights","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-18","text":"Sanitary Fixtures - Supply . Long Lead Items","task":"Sanitary Fixtures - Supply","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-18","text":"Washroom Accesories . Long Lead Items","task":"Washroom Accesories","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-18","text":"Blinds . Short lead Item","task":"Blinds","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-19","text":"ACS/CCTV . Short lead Item","task":"ACS/CCTV","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-19","text":"WD/RR . Short lead Item","task":"WD/RR","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-19","text":"Flutted Panels - Supply . Short lead Item","task":"Flutted Panels - Supply","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Glass Partition,Glass Doors,Lacquerd Glass,Mirror and Urnial Partiton . Short lead Item","task":"Glass Partition,Glass Doors,Lacquerd Glass,Mirror and Urnial Partiton","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Raised flooring . Short lead Item","task":"Raised flooring","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Housekeeping . Short lead Item","task":"Housekeeping","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Floor Proctection Sheets . Short lead Item","task":"Floor Proctection Sheets","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-20","text":"Decorative Lights . Short lead Item","task":"Decorative Lights","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-22","text":"Fabrication Work . Short lead Item","task":"Fabrication Work","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-22","text":"Fire Exit Signages - Prolite . Short lead Item","task":"Fire Exit Signages - Prolite","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-22","text":"Epoxy Flooring . Short lead Item","task":"Epoxy Flooring","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-22","text":"Artificial Planters . Short lead Item","task":"Artificial Planters","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-23","text":"Chess Board with Table . Short lead Item","task":"Chess Board with Table","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-23","text":"Deep cleaning . Short lead Item","task":"Deep cleaning","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-23","text":"Graphics,Sighnage and Films/Suncontrol . Short lead Item","task":"Graphics,Sighnage and Films/Suncontrol","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-23","text":"Dustbin  - Supply . Short lead Item","task":"Dustbin  - Supply","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-24","text":"Entrance Mat . Short lead Item","task":"Entrance Mat","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-24","text":"Hanging Frames . Short lead Item","task":"Hanging Frames","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-24","text":"Insulated Rubber Mats . Short lead Item","task":"Insulated Rubber Mats","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-25","text":"Mattress 7 Inch . Short lead Item","task":"Mattress 7 Inch","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-25","text":"Metal Key Storage . Short lead Item","task":"Metal Key Storage","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-25","text":"Skriting,Corner Guard and Profiles - Supply . Short lead Item","task":"Skriting,Corner Guard and Profiles - Supply","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"procurement","source":"material_tracker","day":"2026-06-25","text":"Slotted Angle Racks . Short lead Item","task":"Slotted Angle Racks","po":null,"vendor":null,"closed":null,"confidence":"low","zone":null},
  {"kind":"note","source":"dpr","day":"2026-03-30","person":"[INT] Login - SKF, Pune","text":"Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-03-30","person":"~ SD","text":"~ SD created this group","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-04","person":"[INT] Login - SKF, Pune","text":"Vikash Flipspaces added you","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-05","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Project SKF Mall of Millennium Tower-03* *Floor = 7th* *DATE : 05-07-2026* *FS Staff- 06* *PM  - 01* *SPM-01* *SPM- 01* [MEP] *SUP - 01* *EHS - 02* *TOTAL LABOURERS COUNT 16 Nos* 1..Electrical -5 2.Civil-05 3.Gypsum -04 4.House keeping - 07 5.FAS - 03 7.HVAC- 07 *Grand Total : 37* *Today Work Activities* *Civil & Interiors* 1. 2nd Layer lintel for hub room, Ups room and wash rooms near Cafeteria 2. Gypsum Partition, for payroll  Room, Board Room and 11 pax meeting room *Electricals* 1. Raceway Laying 2. ⁠Race way Cutting and Chipping 3. ⁠Conduit Installation in gypsum partition *FS* 1.Headers Joining 2.Main Header line Connecting *HVAC* 1. Duct Insulation 2. ⁠Supporting installation 3. ⁠Duct Shifting and Stacking","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-06","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Project SKF Mall of Millennium Tower-03* *Floor = 7th* *DATE : 06-07-2026* *FS Staff- 07* *PM  - 01* *SPM-01* *SPM- 01* [MEP] *SUP - 02* *EHS - 02* *TOTAL LABOURERS COUNT 16 Nos* 1..Electrical -5 2.Civil-05 3.Gypsum -04 4.House keeping - 07 5.FAS - 03 7.HVAC- 07 8 Painter-03 *Grand Total : 37* *Today Work Activities* *Civil & Interiors* 1. 2nd Layer lintel for hub room, Ups room and wash rooms near Cafeteria 2. Gypsum Partition, for payroll  Room, Board Room and 11 pax meeting room 3. ⁠Rock wool installation at payroll , 4 pax meeting room *Electricals* 1. Raceway Laying 2. ⁠Race way Cutting and Chipping *FS* 1.Headers Joining 2.Main Header line Connecting *HVAC* 1. Duct Insulation 2. ⁠Supporting installation 3. ⁠Duct Installation 4. ⁠Duct Fabrication *Plumbing* 1.Material Received and Shifting to site *paint* 1.Material Shifting","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-07","person":"Vikash Flipspaces","text":"@⁨Sourabh⁩ : Pls link site team attendance with DPRs from today","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-07","person":"Sourabh","text":"Noted","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* Project SKF Mall of Millennium Tower 3 Floor 7th *DATE : 07-07-2026* FS Staff-06 PM - 1 SPM - 1 SPM - 1 ( MEP) SUP - 2 EHS - 1 1.Electrical - 05 2.House Keeping -05 3.FAS - 03 4.HVAC - 07 5.Painter - 03 6. Civil- 05 *Grand Total =34* *Electricals* 1. Raceway Laying *HVAC* 1.Duct Insulation 2.Duct Fabrication *Civil* Lintal & block work in server room & electric room *Painting* 1. Putti work for Ceiling","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003009-PHOTO-2026-07-07-18-45-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003010-PHOTO-2026-07-07-18-45-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003011-PHOTO-2026-07-07-18-45-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003012-PHOTO-2026-07-07-18-45-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003013-PHOTO-2026-07-07-18-45-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003014-PHOTO-2026-07-07-18-45-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003015-PHOTO-2026-07-07-18-45-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003016-PHOTO-2026-07-07-18-45-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003017-PHOTO-2026-07-07-18-45-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003018-PHOTO-2026-07-07-18-45-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"<attached: 00003019-PHOTO-2026-07-07-18-57-21.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"Ducting work in progress","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-07","person":"Vishal SKF Pune SPM","text":"Lintal work on server room wall <attached: 00003021-PHOTO-2026-07-07-18-57-31.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Night Shift* *Project SKF Mall of Millennium* *Tower 3* *Floor 7th* *DATE : 07-07-2026* *FS Staff APM-01* EHS - 1 1.Electrical - 04 *Grand Total =05 *Electricals* 1.Junction Box Fixing in gypsum Partition 2. Conducting","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* Project SKF Mall of Millennium Tower 3 Floor 7th *DATE : 08-07-2026* FS Staff-05 SPM - 1 SUP - 2 EHS - 1 Designer-01 *Activities* 1.Painter - 02 2.Civil- 05 3.Gypsum Partition-06 1. Electrical-03 2. ⁠ *Grand Total = 20* *Electricals* 1. Conduiting in partition *Civil* 3rd Layer block work on Lintel for server room & electric room *Painting and Punning* 1. Putti work for Ceiling 2. Punning for AHU Room out side walls near Cafeteria *Gypsum Partition* 1. Rock wool installation at 12 pax meeting room,4 pax meeting room and Cabins opp to wellness room","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"3 rd layer of siporex block on server room & electric room <attached: 00003024-PHOTO-2026-07-08-21-28-39.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"Conduiting work <attached: 00003025-PHOTO-2026-07-08-21-28-40.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003026-PHOTO-2026-07-08-21-28-40.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003027-PHOTO-2026-07-08-21-28-42.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003028-PHOTO-2026-07-08-21-28-43.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003029-PHOTO-2026-07-08-21-28-44.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003030-PHOTO-2026-07-08-21-28-47.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003031-PHOTO-2026-07-08-21-28-48.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003032-PHOTO-2026-07-08-21-28-49.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003033-PHOTO-2026-07-08-21-28-50.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003034-PHOTO-2026-07-08-21-28-51.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003035-PHOTO-2026-07-08-21-28-51.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003036-PHOTO-2026-07-08-21-28-51.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003037-PHOTO-2026-07-08-21-28-52.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"Electric room one side wall work is done <attached: 00003038-PHOTO-2026-07-08-21-28-52.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"Putti work image omitted","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"<attached: 00003040-PHOTO-2026-07-08-21-28-53.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-08","person":"Vishal SKF Pune SPM","text":"image omitted","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-09","person":"Vishal SKF Pune SPM","text":"<attached: 00003053-PHOTO-2026-07-09-08-49-02.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-09","person":"Vishal SKF Pune SPM","text":"<attached: 00003054-PHOTO-2026-07-09-08-49-02.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-09","person":"Vishal SKF Pune SPM","text":"Work completed <attached: 00003055-PHOTO-2026-07-09-08-49-02.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-09","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Night Shift* *Project SKF Mall of Millennium* *Tower 3* *Floor 7th* *DATE : 08-07-2026* *FS Staff-01* EHS - 1 1.Electrical - 04 *Grand Total =05 *Electricals* 1.floor cutting is going on","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-09","person":"~ Musaddiqsk","text":"@⁨Vishal SKF Pune SPM⁩  what happening to the AV call ?","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-09","person":"Vishal SKF Pune SPM","text":"It is getting rescheduled Rupesh will share new meeting link","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* Project SKF Mall of Millennium Tower 3 Floor 7th *DATE : 09-07-2026* FS Staff-03 SUP - 2 EHS - 1 *Activities* 1.Painter - 03 2.Punning- 05 3.Gypsum Partition-06 *Grand Total = 17* *Painting and Punning* 1. Putti work for Ceiling 1. Punning for AHU Room out side walls near Cafeteria & Washrooms *Gypsum Partition* 1. Rock wool installation & board fixing at Reception area, Wellness male and female room *Night Shift* *DATE : 09-07-2026* *FS Staff-01* EHS - 1 1.Electrical - 03 *Grand Total =04 *Electricals* 1. Cabin ceiling conduct work is going on","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"AHU room near cafeteria <attached: 00003060-PHOTO-2026-07-10-08-57-02.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003061-PHOTO-2026-07-10-08-57-02.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003062-PHOTO-2026-07-10-08-57-03.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"Visiting room in Reception area <attached: 00003063-PHOTO-2026-07-10-08-57-03.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003064-PHOTO-2026-07-10-08-57-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003065-PHOTO-2026-07-10-08-57-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003066-PHOTO-2026-07-10-08-57-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"<attached: 00003067-PHOTO-2026-07-10-08-57-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-10","person":"Sourabh","text":"@⁨Vishal SKF Pune SPM⁩ @jotiba hope all issues are sorted with 360 camera? when can we start receiving the 360 deg feed.","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-10","person":"EV Strategy Desk","text":"You added EV Strategy Desk","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-10","person":"Vishal SKF Pune SPM","text":"Yes you shall start receiving updates by tomorrow afternoon Rishab will be sharing the login id by today eod","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-11","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* Project SKF Mall of Millennium Tower 3 Floor 7th *DATE : 10-07-2026* FS Staff-05 SPM - 2 SUP - 1 EHS - 1 APM-1 *Activities* 1.Painter - 04 2.Punning -02 3.Gypsum Partition-05 4. Electrical-04 5. ⁠House Keeping-03 6. Work Station Marking -4 *Grand Total = 27* *Electricals* 1. Conduiting in partition at Compactor Room, Cabins, Reception area 2 *Painting and Punning* 1. Putti work for Ceiling 2. Punning for Electrical room *Gypsum Partition* 1. Rock wool installation at 12 pax meeting room,4 pax meeting room and Cabins opp to wellness room board rooms and Cabins *Work Station* 1. Work Stations marking Shift: Night Shift Date: 10-07-2026 Manpower Deployment Description| Nos. FS Staff| 01 EHS| 01 Civi |06 Electrical| 10 Total Manpower| 17 Work Progress 1. Floor cutting work and MS conduit routing was carried out. 2. Material shifting activity was completed as per site requirements.","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-12","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Project SKF Mall of Millennium* *Tower 3 - Floor 7th* *DATE : 11-07-2026* *FS Staff-05* SPM - 1 SUP - 1 EHS - 1 PM-1 *Activities* 1.Painter - 05 2.Civil -09 3.Gypsum Partition-04 4.Electrical-04 5.⁠House Keeping-02 6.Fire Fighting-03 1. Hvac-02 *Grand Total = 34* *Electricals* 1. Ceiling Conduit Passage area and Work Station Area Floor Cutting and Chipping for Raceway *Painting and Punning* 1. Putti work for Ceiling *Gypsum Partition* 1. Rock wool installation at 12 pax meeting room,4 pax meeting room and Cabins opp to wellness room board rooms and Cabins *Fire Fighting* Main header  Connection *Civil* 1.Block Shifting B1 - 07th Floor 1. Block Work For Server Room and Electrical Room *HVAC* 1.Duct Fabrication Shift: Night Shift Date: 11-07-2026 Manpower Deployment Description| Nos. FS Staff| 02 EHS| 01 Sup|01 Electrical| 2 Total Manpower| 04 Work Progress 1. Floor cutting work and Revised raceway marking 2. Material shifting activity was completed as per site requirements.","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"*DAILY MANPOWER & PROGRESS REPORT* *Project SKF Mall of Millennium* *Tower 3 - Floor 7th* *DATE : 12-07-2026* *FS Staff-05* SPM - 1 SUP - 1 EHS - 1 PM-1 *Activities* 1.Painter - 05 2.Civil -03 3.Gypsum Partition-02 4.Electrical-04 5.⁠House Keeping-02 6.Fire Fighting-00 1. Hvac-02 *Grand Total = 22 *Electricals* 1. Ceiling Conduit Passage area and Work Station Area Floor Cutting and Chipping for Raceway *Painting and Punning* 1. Putti work for Ceiling *Gypsum Partition* 1. Rock wool installation at 12 pax meeting room,4 pax meeting room and Cabins opp to wellness room board rooms and Cabins *Civil* 1.Block Shifting B1 - 07th Floor 1. Block Work For Server Room and Electrical Room *HVAC* 1.Duct Fabrication Shift: Night Shift Date: 12-07-2026 Manpower Deployment Description| Nos. FS Staff| 02 EHS| 01 Sup|01 Electrical|04 Total Manpower| 06 Work Progress 1.Floor racway cutting in progress","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-13","person":"Vikash Flipspaces","text":"Who will send site pics ?","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003075-PHOTO-2026-07-13-08-46-52.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003076-PHOTO-2026-07-13-08-46-52.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003077-PHOTO-2026-07-13-08-46-52.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003078-PHOTO-2026-07-13-08-46-53.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003079-PHOTO-2026-07-13-08-46-53.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003080-PHOTO-2026-07-13-08-46-53.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003081-PHOTO-2026-07-13-08-46-53.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003082-PHOTO-2026-07-13-08-46-54.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003083-PHOTO-2026-07-13-08-46-54.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"Electrical team is working <attached: 00003084-PHOTO-2026-07-13-08-46-54.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"Block vehicle received <attached: 00003085-PHOTO-2026-07-13-08-46-55.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003086-PHOTO-2026-07-13-08-46-55.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003087-PHOTO-2026-07-13-08-46-55.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003088-PHOTO-2026-07-13-08-46-55.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003089-VIDEO-2026-07-13-08-46-56.mp4>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003090-PHOTO-2026-07-13-08-46-56.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003091-PHOTO-2026-07-13-08-46-56.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003092-PHOTO-2026-07-13-08-46-56.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"<attached: 00003093-PHOTO-2026-07-13-08-46-57.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-13","person":"Sourabh","text":"@⁨Vishal SKF Pune SPM⁩ have we started the 360 degrees images?","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-13","person":"Sourabh","text":"All sorted with rishabh?","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-13","person":"Vishal SKF Pune SPM","text":"Yes , Design team is updating the 3D in app Accordingly we're capturing the photos with same angles","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Daily Manpower Progress Report Project SKF Mall of Millennium Tower 3-Floor 7th Date : 13/07/26 FS Staff -05 SPM  - 01 PM    - 01 SUP  - 02 EHS  - 01 Activities Painter - 05 Civil - 09 Gypsum partition - 03 Electrician -04 Fire Fighting -02 HVAC -02 House keeping -02 Grand Total = 32 Painting Putti work for ceiling Civil Block loading unloading B1 to 7 th floor Gypsum Rockwool installation Reception, meeting room & wellness room Electric Raceway cutting & Lying ceiling conduit Fire Fighting Main heading connection HVAC Duct Shift: Night Shift Date: 13-07-2026 Manpower Deployment Description| Nos. FS Staff| 02 EHS| 01 Sup|01 Electrical|09 Total Manpower| 11 Work Progress 1. Floor cutting and conduct","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Board room <attached: 00003098-PHOTO-2026-07-14-11-13-03.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Cabin's, 8 pax meeting room & payroll cabin <attached: 00003099-PHOTO-2026-07-14-11-13-03.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Workstation area <attached: 00003100-PHOTO-2026-07-14-11-13-05.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Meeting room, phone Booth's & wellness rooms <attached: 00003101-PHOTO-2026-07-14-11-13-06.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Reception <attached: 00003102-PHOTO-2026-07-14-11-13-07.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Meeting room behind Reception <attached: 00003103-PHOTO-2026-07-14-11-13-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Collab area behind Reception <attached: 00003104-PHOTO-2026-07-14-11-13-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Workstation area <attached: 00003105-PHOTO-2026-07-14-11-13-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Meeting room <attached: 00003106-PHOTO-2026-07-14-11-13-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Server, battery & electric room <attached: 00003107-PHOTO-2026-07-14-11-13-13.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003108-PHOTO-2026-07-14-11-13-14.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Workstation area <attached: 00003109-PHOTO-2026-07-14-11-13-14.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Handwash, dishwash & washroom Near cafeteria <attached: 00003110-PHOTO-2026-07-14-11-13-15.jpg>","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Washrooms near cafeteria <attached: 00003111-PHOTO-2026-07-14-11-13-15.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Cabin's, meeting room & compactor room <attached: 00003112-PHOTO-2026-07-14-11-13-15.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003113-PHOTO-2026-07-14-11-13-16.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"Workstation area <attached: 00003114-PHOTO-2026-07-14-11-13-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003115-PHOTO-2026-07-14-11-13-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003116-PHOTO-2026-07-14-11-13-18.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003117-PHOTO-2026-07-14-11-13-19.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-14","person":"Vishal SKF Pune SPM","text":"<attached: 00003118-PHOTO-2026-07-14-11-13-21.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-14","person":"Vikash Flipspaces","text":"@⁨Shagun FS DM⁩ : Pls get this done asap","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-14","person":"Shagun FS DM","text":"Noted Vikash sir","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-14","person":"Shagun FS DM","text":"This is done.","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Daily Manpower Progress Report Project SKF Tower 3 7 th floor Date :- 14/07/2026 FS Staff - 05 SPM - 01 PM   - 01 SUP - 02 EHS - 01 Activities Painter - 05 Civil      - 09 Gypsum worker - 03 Electrician - 05 Fire Fighting - 05 HVAC            - 04 Carpenter - 07 House keeping - 02 Grand Total = 45 Painting work Putti work for ceiling Civil work Block shifting B1 to 7 th floo Plaster work in server room & electric room Gypsum work Lying gypsum board in Cabin, meeting room & Compactor room Electric work Line marking for conduit on ceiling & lying conduit in ceiling Fire Fighting work G. I. Pipe fabricating Line marking for FA cable HVAC work Insulation of duct & Duct making Carpentry work Panelling on coloumn Shift: Night Shift Date: 14-07-2026 Manpower Deployment Description| Nos. FS Staff| 02 EHS| 01 Sup|01 Electrical|10 Civil.  | 08 Ducting | 07 Total Manpower| 27 Work Progress Electrical work 1. Floor cutting and conduct Civil work 1. Reltan work is going on Ducting 1.hanging and box making","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Compactor room <attached: 00003123-PHOTO-2026-07-15-08-36-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003124-PHOTO-2026-07-15-08-36-04.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003125-PHOTO-2026-07-15-08-36-05.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003126-PHOTO-2026-07-15-08-36-05.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Carpenter <attached: 00003127-PHOTO-2026-07-15-08-36-05.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Duct Insulation work <attached: 00003128-PHOTO-2026-07-15-08-36-06.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Painting on fire pipe <attached: 00003129-PHOTO-2026-07-15-08-36-06.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003130-PHOTO-2026-07-15-08-36-07.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Wooden support in partition frame for door support <attached: 00003131-PHOTO-2026-07-15-08-36-07.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003132-PHOTO-2026-07-15-08-36-07.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"Workstation arae compactor room side <attached: 00003133-PHOTO-2026-07-15-08-36-07.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003134-PHOTO-2026-07-15-08-36-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003135-PHOTO-2026-07-15-08-36-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003136-PHOTO-2026-07-15-08-36-08.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003137-PHOTO-2026-07-15-08-36-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003138-PHOTO-2026-07-15-08-36-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003139-PHOTO-2026-07-15-08-36-09.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003140-PHOTO-2026-07-15-08-36-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003141-PHOTO-2026-07-15-08-36-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003142-PHOTO-2026-07-15-08-36-10.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003143-PHOTO-2026-07-15-08-36-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003144-PHOTO-2026-07-15-08-36-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003145-PHOTO-2026-07-15-08-36-11.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003146-PHOTO-2026-07-15-08-36-12.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003147-PHOTO-2026-07-15-08-36-12.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003148-PHOTO-2026-07-15-08-36-12.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003149-PHOTO-2026-07-15-08-36-13.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"<attached: 00003150-PHOTO-2026-07-15-08-36-13.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"It’s showing no data update in portal Pls check and update","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"~ Rahul Singh","text":"Kindly confirm on the qty of tiles. Is there any damage pc or anything grn needs to be done for the same.","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"Vishal SKF Pune SPM","text":"One box has received damage Team is inspecting all the boxes again","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"~ Rahul Singh","text":"Okay sirji","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"Vikash Flipspaces","text":"@⁨Krishna Gupta FS Purchase⁩ , @⁨Atish Ops Flip Bangalore⁩ : Labor count is far behind from expected","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"Atish Ops Flip Bangalore","text":"Yes Vikash. Today we are planning to deploy additional vendor for civil work. Also HVAC and electrical team will enhance labor from today/ tomorrow","confidence":"low","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-15","person":"Shagun FS DM","text":"@⁨~Rahul Singh⁩ @⁨Krishna Gupta FS Purchase⁩ <attached: 00003157-PHOTO-2026-07-15-15-42-38.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-15","person":"~ Rahul Singh","text":"ok mam","confidence":"low","zone":null,"task":null},
  {"kind":"claim","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"1 st level lintal is done of washroom Near cafeteria <attached: 00003159-PHOTO-2026-07-16-10-50-16.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Washroom block work second layer is start <attached: 00003160-PHOTO-2026-07-16-10-50-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Duct Insulation <attached: 00003161-PHOTO-2026-07-16-10-50-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003162-PHOTO-2026-07-16-10-50-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003163-PHOTO-2026-07-16-10-50-17.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003164-PHOTO-2026-07-16-10-50-18.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003165-PHOTO-2026-07-16-10-50-18.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003166-PHOTO-2026-07-16-10-50-18.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003167-PHOTO-2026-07-16-10-50-19.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003168-PHOTO-2026-07-16-10-50-19.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003169-PHOTO-2026-07-16-10-50-19.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003170-PHOTO-2026-07-16-10-50-20.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003171-PHOTO-2026-07-16-10-50-20.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003172-PHOTO-2026-07-16-10-50-20.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"<attached: 00003173-PHOTO-2026-07-16-10-50-20.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"evidence_ref","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Ducting material received <attached: 00003174-PHOTO-2026-07-16-10-50-21.jpg>","confidence":"medium","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-16","person":"Tarun FS Ops","text":"@⁨Vishal SKF Pune SPM⁩ - Please share the list as per our discussion yesterday","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Daily Manpower Project Report Project SKF Tower 3 7 th floor Date 15/07/2026 FS Staff - 05 SPM - 01 PM   - 01 SUP - 02 EHS - 01 Activities Painter - 05 Civil       - 09 Gypsum worker - 03 Electrician - 05 Fire Fighting - 04 HVAC    - 08 Carpenter - 07 House keeping - 02 Grand Total = 48 Painting work Putti work for ceiling Civil work 1)Plaster work in server room & electric room 2)Block work of wash room near cafeteria 3)Sand shifting B1 to       7th floor Gypsum work Lying gypsum board in cabin's, wellness room & meeting room Electric work Lying surface box & conduiting in partition Fire Fighting work G. I. Pipe hanging & pipe painting HVAC work Duct making Duct installation Duct hanging Carpentry work Ply panelling of column *Shift: Night Shift* Date: 15-07-2026 Manpower Deployment Description| Nos. FS Staff| 02 EHS| 01 Sup|01 Electrical|12 Civil.  | 09 Ducting | 10 Carpenter|07 Total Manpower| 40 Work Progress Electrical work 1. Floor cutting and conduct 2. Civil work 1.Reltan work is going on 3. Ducting 1.hanging and box making 4. Carpenter 1.beam panelling","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Sure sir, Sharing it by EOD","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-16","person":"Tarun FS Ops","text":"@⁨Vishal SKF Pune SPM⁩ By 2PM, please","confidence":"low","zone":null,"task":null},
  {"kind":"note","source":"dpr","day":"2026-07-16","person":"Vishal SKF Pune SPM","text":"Okay sir","confidence":"low","zone":null,"task":null}
  ]
};

function apply(ledger, zones) {
  if (ledger.state.files.some(f => f.name === "_chat.txt"))
    return { applied: false, why: "batch 1 already absorbed" };
  for (const z of ABSORB.zones) zones.add(z, { from: "cad" });
  if (zones.state.source === "none" || zones.state.source === "plan") zones.state.source = "cad";
  for (const f of ABSORB.files) ledger.addFile(f);
  for (const fa of ABSORB.facts) ledger.addFact(fa);
  for (const q of ABSORB.queries) ledger.addQuery(q);
  for (const c of ABSORB.closes) {
    const q = ledger.state.queries.find(x => x.status === "open" && x.about === c.about);
    if (q) ledger.answerQuery(q.id, c.answer);
  }
  return { applied: true, facts: ABSORB.facts.length, zones: ABSORB.zones.length, files: ABSORB.files.length };
}

root.TRACK_ABSORB1 = { ABSORB, apply };
if (typeof module !== "undefined") module.exports = root.TRACK_ABSORB1;

})(typeof window !== "undefined" ? window : globalThis);
