// ===================================================================
// DnB-OS . platform/track/project/skf_absorb2.js . ABSORB BATCH 2
// GENERATED 16 Jul 2026 by engines/tracking/data/skf/gen_absorb2.py
// from the full Drive pull: 30 POs, fit-out agreement, 2 client POs,
// BOQ R5 summary, GFC tracker, weekly tracker Wk4, START HERE doc,
// plus the locked baseline from the schedule xlsx (Sourabh 16 Jul:
// follow the excel for planning). Do not edit by hand, regenerate.
// ===================================================================

;(function (root) {

const ABSORB2 = {
  day: "2026-07-16",
  marker: "Flipspaces Fit out Agreement (Signed).pdf",
  files: [
 {
  "name": "FSL2026272008.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272011.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272014.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272024.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272027.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272058.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272062.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272067.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272068.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272072.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272074.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272076.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272077.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272078.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272102.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272121.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272122.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272123.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272128.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272129.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272135.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272161.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272165.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272167.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272180.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272187.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272193.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272194.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272195.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "FSL2026272212.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "po",
   "confidence": "high",
   "label": "Purchase order",
   "why": "pulled from Drive 03.1, canonical extract saved locally"
  }
 },
 {
  "name": "Flipspaces Fit out Agreement (Signed).pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "contract",
   "confidence": "high",
   "label": "Fit-out agreement",
   "why": "pulled from Drive 01, extract saved locally"
  }
 },
 {
  "name": "Client PO Order 4300632629.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "client_po",
   "confidence": "high",
   "label": "Client PO",
   "why": "pulled from Drive 01"
  }
 },
 {
  "name": "Client PO Order 4300632630.pdf",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "client_po",
   "confidence": "high",
   "label": "Client PO",
   "why": "pulled from Drive 01"
  }
 },
 {
  "name": "BOQ R5 FINAL SUMMARY.csv",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "boq",
   "confidence": "high",
   "label": "BOQ summary",
   "why": "pulled from Drive 01, full summary table absorbed"
  }
 },
 {
  "name": "GFC TRACKER (Google Sheet)",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "tracker",
   "confidence": "high",
   "label": "Drawing register",
   "why": "pulled from Drive 10, 58 drawings"
  }
 },
 {
  "name": "SKF Weekly Task Tracker Wk4 (Google Sheet)",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "tracker",
   "confidence": "medium",
   "label": "Weekly tracker",
   "why": "pulled from Drive 10, 25 tasks, 10 days stale"
  }
 },
 {
  "name": "START HERE (Google Doc)",
  "size": null,
  "at": "2026-07-16",
  "verdict": {
   "type": "readme",
   "confidence": "high",
   "label": "SSOT guide",
   "why": "pulled from Drive 00"
  }
 }
],
  facts: [
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Mobilization Period . planned 2026-06-03 to 2026-06-04",
  "task": "Mobilization Period",
  "scope": null,
  "main": null,
  "start": "2026-06-03",
  "finish": "2026-06-04",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Site Prep . Preperations . Site Marking & preperation works . planned 2026-06-08 to 2026-06-14",
  "task": "Site Marking & preperation works",
  "scope": "Site Prep",
  "main": "Preperations",
  "start": "2026-06-08",
  "finish": "2026-06-14",
  "actualStart": "2026-06-07",
  "actualFinish": "2026-06-16",
  "status": "Completed",
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Temperory Power . planned 2026-06-10 to 2026-06-12",
  "task": "Temperory Power",
  "scope": null,
  "main": null,
  "start": "2026-06-10",
  "finish": "2026-06-12",
  "actualStart": "2026-06-11",
  "actualFinish": "2026-06-12",
  "status": "Completed",
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Civil Works . Masonry . Blockwork , AAC Blocks & Plastering . planned 2026-06-24 to 2026-07-03",
  "task": "Blockwork , AAC Blocks & Plastering",
  "scope": "Civil Works",
  "main": "Masonry",
  "start": "2026-06-24",
  "finish": "2026-07-03",
  "actualStart": "2026-06-16",
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Waterproofing (For Floor + Walls 600 mm High) . planned 2026-07-11 to 2026-07-15",
  "task": "Waterproofing (For Floor + Walls 600 mm High)",
  "scope": null,
  "main": null,
  "start": "2026-07-11",
  "finish": "2026-07-15",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Anti-termite treatment and Pest control . planned 2026-06-16 to 2026-06-18",
  "task": "Anti-termite treatment and Pest control",
  "scope": null,
  "main": null,
  "start": "2026-06-16",
  "finish": "2026-06-18",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Self Leveling & Associated works . planned 2026-07-03 to 2026-07-08",
  "task": "Self Leveling & Associated works",
  "scope": null,
  "main": null,
  "start": "2026-07-03",
  "finish": "2026-07-08",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Flooring . Vitrified tile works . planned 2026-07-13 to 2026-07-20",
  "task": "Vitrified tile works",
  "scope": null,
  "main": "Flooring",
  "start": "2026-07-13",
  "finish": "2026-07-20",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Milestone: POP on Flooring (Protection) . planned 2026-07-20 to 2026-07-21",
  "task": "Milestone: POP on Flooring (Protection)",
  "scope": null,
  "main": null,
  "start": "2026-07-20",
  "finish": "2026-07-21",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Fire Fighting Works (FPS) . Sprinkler . C' Class Sprinkler Piping (Grooved) . planned 2026-06-27 to 2026-07-15",
  "task": "C' Class Sprinkler Piping (Grooved)",
  "scope": "Fire Fighting Works (FPS)",
  "main": "Sprinkler",
  "start": "2026-06-27",
  "finish": "2026-07-15",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Alarm Valve Assembly & Flow Switch installation . planned 2026-06-29 to 2026-07-18",
  "task": "Alarm Valve Assembly & Flow Switch installation",
  "scope": null,
  "main": null,
  "start": "2026-06-29",
  "finish": "2026-07-18",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Pendent/Upright Sprinklers & Flexible Drops . planned 2026-07-02 to 2026-07-20",
  "task": "Pendent/Upright Sprinklers & Flexible Drops",
  "scope": null,
  "main": null,
  "start": "2026-07-02",
  "finish": "2026-07-20",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Testing and Commissioning . planned 2026-07-18 to 2026-07-21",
  "task": "Testing and Commissioning",
  "scope": null,
  "main": null,
  "start": "2026-07-18",
  "finish": "2026-07-21",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: HVAC Works . Low Side . G.I. Sheet Ducting Fabrication & Installation . planned 2026-07-04 to 2026-07-22",
  "task": "G.I. Sheet Ducting Fabrication & Installation",
  "scope": "HVAC Works",
  "main": "Low Side",
  "start": "2026-07-04",
  "finish": "2026-07-22",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Milestone: Duct Light Testing (Pre-Insulation) . planned 2026-07-16 to 2026-07-18",
  "task": "Milestone: Duct Light Testing (Pre-Insulation)",
  "scope": null,
  "main": null,
  "start": "2026-07-16",
  "finish": "2026-07-18",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Thermal & Acoustic Insulation (Armasound/Nitrile) . planned 2026-07-18 to 2026-07-27",
  "task": "Thermal & Acoustic Insulation (Armasound/Nitrile)",
  "scope": null,
  "main": null,
  "start": "2026-07-18",
  "finish": "2026-07-27",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Grilles, Diffusers, Fire Dampers Attenuators  & Actuators . planned 2026-07-21 to 2026-07-30",
  "task": "Grilles, Diffusers, Fire Dampers Attenuators  & Actuators",
  "scope": null,
  "main": null,
  "start": "2026-07-21",
  "finish": "2026-07-30",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Battery Roon Ventilation . planned 2026-07-18 to 2026-07-22",
  "task": "Battery Roon Ventilation",
  "scope": null,
  "main": null,
  "start": "2026-07-18",
  "finish": "2026-07-22",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: High Side . Refrigerent Piping & cable Trays . planned 2026-07-05 to 2026-07-16",
  "task": "Refrigerent Piping & cable Trays",
  "scope": null,
  "main": "High Side",
  "start": "2026-07-05",
  "finish": "2026-07-16",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Indoor Units Instalations . planned 2026-07-21 to 2026-07-28",
  "task": "Indoor Units Instalations",
  "scope": null,
  "main": null,
  "start": "2026-07-21",
  "finish": "2026-07-28",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: VRV Equioments and ODUs . planned 2026-07-16 to 2026-07-21",
  "task": "VRV Equioments and ODUs",
  "scope": null,
  "main": null,
  "start": "2026-07-16",
  "finish": "2026-07-21",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Testing and Commissioning . planned 2026-07-28 to 2026-07-31",
  "task": "Testing and Commissioning",
  "scope": null,
  "main": null,
  "start": "2026-07-28",
  "finish": "2026-07-31",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Plumbing Works . Drainage . uPVC SWR Soil/Waste pipes (In-filling/Chasing) . planned 2026-06-29 to 2026-07-06",
  "task": "uPVC SWR Soil/Waste pipes (In-filling/Chasing)",
  "scope": "Plumbing Works",
  "main": "Drainage",
  "start": "2026-06-29",
  "finish": "2026-07-06",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Internal Water Supply Piping . planned 2026-07-04 to 2026-07-11",
  "task": "Internal Water Supply Piping",
  "scope": null,
  "main": null,
  "start": "2026-07-04",
  "finish": "2026-07-11",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Grease Traps, Multi Traps & Floor Grating . planned 2026-07-10 to 2026-07-12",
  "task": "Grease Traps, Multi Traps & Floor Grating",
  "scope": null,
  "main": null,
  "start": "2026-07-10",
  "finish": "2026-07-12",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Wall & Ceiling finishes . planned 2026-07-12 to 2026-07-21",
  "task": "Wall & Ceiling finishes",
  "scope": null,
  "main": null,
  "start": "2026-07-12",
  "finish": "2026-07-21",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Fittings & Fixtures . Toilet ubical Instalation . planned 2026-07-18 to 2026-07-23",
  "task": "Toilet ubical Instalation",
  "scope": null,
  "main": "Fittings & Fixtures",
  "start": "2026-07-18",
  "finish": "2026-07-23",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Sanitary Fixtures & Fittings - Second Fix . planned 2026-07-21 to 2026-07-26",
  "task": "Sanitary Fixtures & Fittings - Second Fix",
  "scope": null,
  "main": null,
  "start": "2026-07-21",
  "finish": "2026-07-26",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Electrical Works . Containment . GI Cable Trays, Trunking & MS Support Fix . planned 2026-07-02 to 2026-07-23",
  "task": "GI Cable Trays, Trunking & MS Support Fix",
  "scope": "Electrical Works",
  "main": "Containment",
  "start": "2026-07-02",
  "finish": "2026-07-23",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: GI Conduiting & Switch/Point Back-boxes . planned 2026-07-09 to 2026-07-30",
  "task": "GI Conduiting & Switch/Point Back-boxes",
  "scope": null,
  "main": null,
  "start": "2026-07-09",
  "finish": "2026-07-30",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Point wiring Circuts mains and DB's . planned 2026-07-16 to 2026-08-06",
  "task": "Point wiring Circuts mains and DB's",
  "scope": null,
  "main": null,
  "start": "2026-07-16",
  "finish": "2026-08-06",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: High Side . LT Panel Cabeling . planned 2026-07-21 to 2026-08-01",
  "task": "LT Panel Cabeling",
  "scope": null,
  "main": "High Side",
  "start": "2026-07-21",
  "finish": "2026-08-01",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Panel Instalation - Testing & Commissioning . planned 2026-07-30 to 2026-08-02",
  "task": "Panel Instalation - Testing & Commissioning",
  "scope": null,
  "main": null,
  "start": "2026-07-30",
  "finish": "2026-08-02",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: ELV Instalations . FAS & PA . Red/Black Armored Cabling for FAS/PA/CCTV . planned 2026-07-11 to 2026-07-26",
  "task": "Red/Black Armored Cabling for FAS/PA/CCTV",
  "scope": "ELV Instalations",
  "main": "FAS & PA",
  "start": "2026-07-11",
  "finish": "2026-07-26",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Detectors, Hooters, & PAVA Rack Commissioning . planned 2026-07-20 to 2026-07-29",
  "task": "Detectors, Hooters, & PAVA Rack Commissioning",
  "scope": null,
  "main": null,
  "start": "2026-07-20",
  "finish": "2026-07-29",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Access/CCTV . EM Locks (Fail Safe), Biometric Readers & CCTV . planned 2026-07-18 to 2026-07-27",
  "task": "EM Locks (Fail Safe), Biometric Readers & CCTV",
  "scope": null,
  "main": "Access/CCTV",
  "start": "2026-07-18",
  "finish": "2026-07-27",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Emergency Exit Signage (Flush & Surface Mount) . planned 2026-07-22 to 2026-07-31",
  "task": "Emergency Exit Signage (Flush & Surface Mount)",
  "scope": null,
  "main": null,
  "start": "2026-07-22",
  "finish": "2026-07-31",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Rodent Repellent System . planned 2026-07-22 to 2026-07-29",
  "task": "Rodent Repellent System",
  "scope": null,
  "main": null,
  "start": "2026-07-22",
  "finish": "2026-07-29",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Water Leak Detection system . planned 2026-07-22 to 2026-07-29",
  "task": "Water Leak Detection system",
  "scope": null,
  "main": null,
  "start": "2026-07-22",
  "finish": "2026-07-29",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Interiors & Finishes Works . Carpentry . 100mm Gypsum Board Full Height Partition . planned 2026-06-24 to 2026-07-09",
  "task": "100mm Gypsum Board Full Height Partition",
  "scope": "Interiors & Finishes Works",
  "main": "Carpentry",
  "start": "2026-06-24",
  "finish": "2026-07-09",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Gypsum Column Cladding with Ply paneling . planned 2026-06-29 to 2026-07-14",
  "task": "Gypsum Column Cladding with Ply paneling",
  "scope": null,
  "main": null,
  "start": "2026-06-29",
  "finish": "2026-07-14",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Ply backing - Decorative Cladding . planned 2026-07-06 to 2026-07-17",
  "task": "Ply backing - Decorative Cladding",
  "scope": null,
  "main": null,
  "start": "2026-07-06",
  "finish": "2026-07-17",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Seating Areas, Reception, Window Sills booth seating and Other Mill works . planned 2026-07-09 to 2026-07-20",
  "task": "Seating Areas, Reception, Window Sills booth seating and Other Mill works",
  "scope": null,
  "main": null,
  "start": "2026-07-09",
  "finish": "2026-07-20",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Wooden raised floor & Epoxy . planned 2026-07-17 to 2026-07-19",
  "task": "Wooden raised floor & Epoxy",
  "scope": null,
  "main": null,
  "start": "2026-07-17",
  "finish": "2026-07-19",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Celing Works . Painting / Gyp-roc bondit  for True Ceiling . planned 2026-07-11 to 2026-07-18",
  "task": "Painting / Gyp-roc bondit  for True Ceiling",
  "scope": null,
  "main": "Celing Works",
  "start": "2026-07-11",
  "finish": "2026-07-18",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Ceiling works for Meeting rooms, Board Rooms . planned 2026-07-27 to 2026-08-07",
  "task": "Ceiling works for Meeting rooms, Board Rooms",
  "scope": null,
  "main": null,
  "start": "2026-07-27",
  "finish": "2026-08-07",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Ceiling works - Acoustics & Desinger (Collab Area + Cafetaria) . planned 2026-07-27 to 2026-08-07",
  "task": "Ceiling works - Acoustics & Desinger (Collab Area + Cafetaria)",
  "scope": null,
  "main": null,
  "start": "2026-07-27",
  "finish": "2026-08-07",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Flooring . Carpet flooring Type 1 . planned 2026-07-20 to 2026-08-03",
  "task": "Carpet flooring Type 1",
  "scope": null,
  "main": "Flooring",
  "start": "2026-07-20",
  "finish": "2026-08-03",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Carpet flooring Type 2 . planned 2026-07-23 to 2026-08-03",
  "task": "Carpet flooring Type 2",
  "scope": null,
  "main": null,
  "start": "2026-07-23",
  "finish": "2026-08-03",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Wall . Acrylic Emulsion Paint (Wall / Partitions / Column) . planned 2026-07-29 to 2026-08-05",
  "task": "Acrylic Emulsion Paint (Wall / Partitions / Column)",
  "scope": null,
  "main": "Wall",
  "start": "2026-07-29",
  "finish": "2026-08-05",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: 50mm HT Aluminium Wall Skirting & Corner Guard . planned 2026-07-31 to 2026-08-07",
  "task": "50mm HT Aluminium Wall Skirting & Corner Guard",
  "scope": null,
  "main": null,
  "start": "2026-07-31",
  "finish": "2026-08-07",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Modular Partition Glass . Glass Partitions Frames, Doors & Fitting . planned 2026-07-18 to 2026-07-29",
  "task": "Glass Partitions Frames, Doors & Fitting",
  "scope": null,
  "main": "Modular Partition Glass",
  "start": "2026-07-18",
  "finish": "2026-07-29",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Furniture . Modular . Workstation Linear Sharing/Non sharing - 1500mm X 750mm . planned 2026-07-28 to 2026-08-09",
  "task": "Workstation Linear Sharing/Non sharing - 1500mm X 750mm",
  "scope": "Furniture",
  "main": "Modular",
  "start": "2026-07-28",
  "finish": "2026-08-09",
  "actualStart": "2026-06-16",
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Tables - Meeting, Cabin, Booths, Conference room . planned 2026-07-25 to 2026-08-05",
  "task": "Tables - Meeting, Cabin, Booths, Conference room",
  "scope": null,
  "main": null,
  "start": "2026-07-25",
  "finish": "2026-08-05",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Cafeteria Tables (6-Seater/4-Seater Corian Top) . planned 2026-07-25 to 2026-08-05",
  "task": "Cafeteria Tables (6-Seater/4-Seater Corian Top)",
  "scope": null,
  "main": null,
  "start": "2026-07-25",
  "finish": "2026-08-05",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Planterboxes, storage units, Bookshelf . planned 2026-07-25 to 2026-08-05",
  "task": "Planterboxes, storage units, Bookshelf",
  "scope": null,
  "main": null,
  "start": "2026-07-25",
  "finish": "2026-08-05",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Networking . Cable Laying termination and Testing . planned 2026-08-02 to 2026-08-12",
  "task": "Cable Laying termination and Testing",
  "scope": "Networking",
  "main": null,
  "start": "2026-08-02",
  "finish": "2026-08-12",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Miscellaneous . Blinds . Supply & Installation of Motorized Blinds . planned 2026-07-28 to 2026-08-04",
  "task": "Supply & Installation of Motorized Blinds",
  "scope": "Miscellaneous",
  "main": "Blinds",
  "start": "2026-07-28",
  "finish": "2026-08-04",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Signages . Door & Directions Signages . planned 2026-07-30 to 2026-08-06",
  "task": "Door & Directions Signages",
  "scope": null,
  "main": "Signages",
  "start": "2026-07-30",
  "finish": "2026-08-06",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Graphics . Graphics - Wall, Wall paper & glass films . planned 2026-08-01 to 2026-08-08",
  "task": "Graphics - Wall, Wall paper & glass films",
  "scope": null,
  "main": "Graphics",
  "start": "2026-08-01",
  "finish": "2026-08-08",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Integrated Fire Trip & Evacuation Testing . planned 2026-08-09 to 2026-08-12",
  "task": "Integrated Fire Trip & Evacuation Testing",
  "scope": null,
  "main": null,
  "start": "2026-08-09",
  "finish": "2026-08-12",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Deep Cleaning & Snags Rectification . planned 2026-08-05 to 2026-08-14",
  "task": "Deep Cleaning & Snags Rectification",
  "scope": null,
  "main": null,
  "start": "2026-08-05",
  "finish": "2026-08-14",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "baseline",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Baseline: Final Handover & Snag Rectification . planned 2026-08-13 to 2026-08-18",
  "task": "Final Handover & Snag Rectification",
  "scope": null,
  "main": null,
  "start": "2026-08-13",
  "finish": "2026-08-18",
  "actualStart": null,
  "actualFinish": null,
  "status": null,
  "planVersion": "xlsx-v1",
  "confidence": "locked",
  "zone": null,
  "flag": null
 },
 {
  "kind": "context",
  "source": "plan",
  "day": "2026-07-16",
  "text": "Original schedule (sheet part 1): 77 rows, 2026-05-23 to 2026-08-20. Superseded by the current plan sheet (part 2) which is the locked baseline xlsx-v1 per Sourabh 16 Jul.",
  "confidence": "high",
  "zone": null,
  "task": null
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272011 rev 3 on PCI Pest Control Pvt Ltd for Pest Control: Pest control and anti-termite treatment for 22000 sqft (PCI, 2 service rounds, 10 year warranty on stamp paper)",
  "po": "FSL2026272011",
  "rev": 3,
  "vendor": "PCI Pest Control Pvt Ltd",
  "category": "Pest Control",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-10",
  "value": 64900.0,
  "terms": "Advance payment 50%, Payment after work completion 50%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272014 rev 6 on HINDUSTAN ASSOCIATES for Tiles: Tiles Kajaria 1200x600 matt, 4495 sqft",
  "po": "FSL2026272014",
  "rev": 6,
  "vendor": "HINDUSTAN ASSOCIATES",
  "category": "Tiles",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-11",
  "value": 443208.0,
  "terms": "Advance Payment 100%",
  "purchaser": "Krishna Gupta",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272024 rev 3 on M.N.Electricals for Fire Sprinkler: Fire sprinkler and drencher system: GI 'C' class piping 25-150 NB (~782 mtrs) plus 210 mtrs drencher header, ~325 sprinklers (concealed/pendant/upright), flexible and hard drops, butterfly/gate/ball/NRV valves, flow switches, deluge valve set, drencher nozzles, pressure testing and commissioning",
  "po": "FSL2026272024",
  "rev": 3,
  "vendor": "M.N.Electricals",
  "category": "Fire Sprinkler",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-16",
  "value": 1817757.0,
  "terms": "85% basic payment after submission of invoice within 15 days, 10% after complete documentation/handover and snag-free site within 30 days, 5% retention for 1 year",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272027 rev 3 on NATIONAL INFRA SOLUTIONS for Civil: Civil works package: cement plastering (~429 sqm), POP punning (400 sqm), gypsum plaster (475 sqm), 150mm AAC block walls (272 sqm), and vitrified tile flooring with epoxy grouting (800 sqm)",
  "po": "FSL2026272027",
  "rev": 3,
  "vendor": "NATIONAL INFRA SOLUTIONS",
  "category": "Civil",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-16",
  "value": 1872944.0,
  "terms": "85% basic payment after submission of invoice within 15 days, 10% after complete documentation/handover and snag-free site within 30 days, 5% retention for 1 year",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272058 rev 2 on Nikhil Balu Khamkar for Logistics: Material shifting charges, 1 transportation trip (no tax)",
  "po": "FSL2026272058",
  "rev": 2,
  "vendor": "Nikhil Balu Khamkar",
  "category": "Logistics",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-21",
  "value": 35000.0,
  "terms": "Imprest Payment 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272062 rev 3 on METRO AIR CONDITIONER for HVAC: Complete HVAC package (SITC as per attached BoQ, lumpsum lines): HVAC low side works, VAV units, and VRF air-conditioning system incl. outdoor units, piping, BMS-compatible controls and commissioning",
  "po": "FSL2026272062",
  "rev": 3,
  "vendor": "METRO AIR CONDITIONER",
  "category": "HVAC",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-22",
  "value": 11209561.0,
  "terms": "85% basic payment after submission of invoice within 15 days, 10% after site handover with complete documentation and snag-free site within 30 days, 5% retention for 12 months",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272067 rev 3 on S.S. Furniture & Interior for Site Imprest: Site imprest furniture: 7 plastic chairs and 5 plastic tables",
  "po": "FSL2026272067",
  "rev": 3,
  "vendor": "S.S. Furniture & Interior",
  "category": "Site Imprest",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-22",
  "value": 12242.5,
  "terms": "Imprest Payment 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272068 rev 5 on Arselex Engineering Private Limited for Electrical: Complete electrical work SITC per annexure BOQ, line-item billing",
  "po": "FSL2026272068",
  "rev": 5,
  "vendor": "Arselex Engineering Private Limited",
  "category": "Electrical",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-22",
  "value": 11800000.0,
  "terms": "Invoice 85%, handover 10%, retention 5%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272072 rev 8 on POWER ZONE for Light Fixtures: Philips light fixtures: 145 hanging cylindrical 15W lights, 296 downlights 15W, 190 linear 5ft lights, 12 panel lights 2x2 30W (all 4000K white)",
  "po": "FSL2026272072",
  "rev": 8,
  "vendor": "POWER ZONE",
  "category": "Light Fixtures",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-23",
  "value": 1216238.0,
  "terms": "Advance Payment 50%, Payment before Material Delivery 50%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272074 rev 1 on CHETTAK INTEGRATED SECURITY PRIVATE LIMITED for Security: Security guard deployment at site: 2 guards (1 day, 1 night) for 2 months at 25000 per person per month, plus 5% maintenance charges",
  "po": "FSL2026272074",
  "rev": 1,
  "vendor": "CHETTAK INTEGRATED SECURITY PRIVATE LIMITED",
  "category": "Security",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-23",
  "value": 129800.0,
  "terms": "Payment after 7 Days post Invoice Submission 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error. Also: no Revision line printed on the PDF, revision taken from the Drive filename suffix _1"
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272076 rev 0 on BHARATH FIRE PROTECTORS for Fire Doors: Supply and installation of metal fire doors 1000x2100mm single leaf with D handle (Shakti Horman, 3 nos) plus transport/loading/unloading to site (1 trip)",
  "po": "FSL2026272076",
  "rev": 0,
  "vendor": "BHARATH FIRE PROTECTORS",
  "category": "Fire Doors",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-23",
  "value": 93998.0,
  "terms": "Advance payment with GST 50%, payment before dispatch with GST 50%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272078 rev 0 on SAFEX FIRE SERVICES LTD for Fire Extinguishers: Safex fire extinguishers: 4.5kg CO2 (5 nos), 6kg ABC stored pressure (19 nos), ceiling mounted clean agent HFC 15kg (1 no) and 10kg (6 nos), floor stands (24 nos)",
  "po": "FSL2026272078",
  "rev": 0,
  "vendor": "SAFEX FIRE SERVICES LTD",
  "category": "Fire Extinguishers",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-23",
  "value": 317302.0,
  "terms": "50% payment before delivery, 50% payment after delivery",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272102 rev 2 on SD ENTERPRISES for Labour: Mathadi labour charges as per attached annexure (lump sum)",
  "po": "FSL2026272102",
  "rev": 2,
  "vendor": "SD ENTERPRISES",
  "category": "Labour",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-26",
  "value": 1298000.0,
  "terms": "Advance Payment 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272121 rev 2 on SUSTAINABLE CLEANING SOLUTIONS for Housekeeping: Housekeeping service at site: 2 persons for 30 days (10:00 AM to 6:00 PM), Rs 1800 per day",
  "po": "FSL2026272121",
  "rev": 2,
  "vendor": "SUSTAINABLE CLEANING SOLUTIONS",
  "category": "Housekeeping",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-30",
  "value": 63720.0,
  "terms": "Payment after completion delivery 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272122 rev 2 on Jyoti Enterprises for Painting: Painting works: acrylic emulsion paint on true ceiling/bulkheads (2100 sqm) and premium low-VOC acrylic emulsion paint with putty and primer on walls/partitions/columns (2200 sqm)",
  "po": "FSL2026272122",
  "rev": 2,
  "vendor": "Jyoti Enterprises",
  "category": "Painting",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-06-30",
  "value": 964060.0,
  "terms": "85% payment as per RA bill, 10% after work completion, 5% after DLP 12 month period",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272123 rev 2 on Impact Enterprises for HSE Consumables: Site safety and fire fighting consumables: Karam helmets (7), 4kg ABC fire extinguishers (5), fire bucket stands (3) and buckets (6), roto cones (20), chain link (100 rmt), hand gloves (60), safety goggles (15), safety jackets (5), APS shoes (1)",
  "po": "FSL2026272123",
  "rev": 2,
  "vendor": "Impact Enterprises",
  "category": "HSE Consumables",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-01",
  "value": 29827.3,
  "terms": "Imprest payment 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272128 rev 6 on Triangular Infosolutions Private Limited for UPS: UPS package: 80 KVA, 20 KVA and 6 KVA IGBT modular UPS (N+1), VRLA SMF battery sets with racks, copper DC/AC cabling with glands and lugs, battery room ventilation (pre-filter, GI duct)",
  "po": "FSL2026272128",
  "rev": 6,
  "vendor": "Triangular Infosolutions Private Limited",
  "category": "UPS",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-01",
  "value": 2124000.0,
  "terms": "Advance Payment 50%, Payment after completion of Work 45%, Retention of 12 Months 5%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error. Also: printed grand total 2124000.00 does not equal taxable 1800000.00 plus printed GST lines, kept the printed grand total"
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272129 rev 11 on Featherlite Office Systems (P) Limited for Furniture: Featherlite office furniture: 305 linear workstations with pedestals, 364 medium back and 50 high back mesh chairs, meeting/conference tables (4 to 12 pax), 6 cabin tables, 20 prelam storages, cafe/booth/high tables and multipurpose rack",
  "po": "FSL2026272129",
  "rev": 11,
  "vendor": "Featherlite Office Systems (P) Limited",
  "category": "Furniture",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-01",
  "value": 9148057.4,
  "terms": "Payment Advance With GST 50%, 30 Days PDC 1 Day Before Delivery against Performa Invoice 45%, 45 Days PDC After Delivery against Performa Invoice 5%",
  "purchaser": "Krishna Gupta",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272135 rev 8 on AR INTERIOR for Interior Finishing: Interior finishing: 230 rmt roller blind pelmets, 800 rmt aluminium skirting, 700 rmt corner guards, 460 sqm laminate/ply panelling with and without frame, 250 sqm ply backing, 230 rmt laminate finished window sills",
  "po": "FSL2026272135",
  "rev": 8,
  "vendor": "AR INTERIOR",
  "category": "Interior Finishing",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-01",
  "value": 2618469.6,
  "terms": "Basic Payment after submission of Invoice within 15 Days 85%, Basic Payment After site Handover with complete documentation and snagfree site within 30 Days 10%, Retention for 12 Months 5%",
  "purchaser": "Krishna Gupta",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272165 rev 5 on AYUSHRI ASSOCIATES PRIVATE LIMITED for Acoustic Booths: Acoustic call booths: 2 single seater call booths and 2 double seater call booths (AIPL make) plus transportation to site",
  "po": "FSL2026272165",
  "rev": 5,
  "vendor": "AYUSHRI ASSOCIATES PRIVATE LIMITED",
  "category": "Acoustic Booths",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-07",
  "value": 1286200.0,
  "terms": "Advance Payment 50%, Payment before Dispatch 40%, Payment after Delivery 10%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272167 rev 4 on WELSPUN GLOBAL BRANDS LIMITED for Carpet: Supply and installation of 100% nylon tufted textured loop carpet tiles 500x500mm (Welspun, 1270 sqmt + 225 sqmt) including installation charges",
  "po": "FSL2026272167",
  "rev": 4,
  "vendor": "WELSPUN GLOBAL BRANDS LIMITED",
  "category": "Carpet",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-08-11",
  "value": 1881144.0,
  "terms": "Advance payment 90%, payment after installation 10%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272180 rev 7 on Triangular Infosolutions Private Limited for Networking: Passive networking: Cat6A UTP cable (154 boxes), 801 node cable laying, termination and fluke testing, OM4 fiber cable, panels and patch cords, 24U/42U racks with PDUs and cable organisers, CCTV/WiFi poles and installation services",
  "po": "FSL2026272180",
  "rev": 7,
  "vendor": "Triangular Infosolutions Private Limited",
  "category": "Networking",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-09",
  "value": 5254233.4,
  "terms": "Payment before Delivery 40%, Payment after Delivery 40%, Payment after Invoice Generation 20%",
  "purchaser": "Krishna Gupta",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272187 rev 0 on ALDON STEEL PVT LTD for Compactors: Compactor cabinets SFF/DFM/SFM + fitting + transport (Aldon)",
  "po": "FSL2026272187",
  "rev": 0,
  "vendor": "ALDON STEEL PVT LTD",
  "category": "Compactors",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-09",
  "value": 252756.0,
  "terms": "Payment before Delivery 50% + 50%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272193 rev 0 on EUROCEIL SYSTEMS PRIVATE LIMITED for Stretch Ceiling: Stretched fabric ceiling: supply and installation of Euroceil premium translucent PVC membrane (377 sqft) with EC Supreme bar LED and drivers (377 sqft) including sheet and LED installation charges",
  "po": "FSL2026272193",
  "rev": 0,
  "vendor": "EUROCEIL SYSTEMS PRIVATE LIMITED",
  "category": "Stretch Ceiling",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-10",
  "value": 413720.0,
  "terms": "50% advance after shop drawing approval, 40% payment before delivery, 10% payment after installation",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272194 rev 0 on UNITED ACCESS FLOORS PRIVATE LIMITED for Raised Flooring: Providing and fixing antistatic laminate raised access flooring, 300mm height, 600x600mm removable steel cementitious-filled panels (Unitile/AET), 30 sqm",
  "po": "FSL2026272194",
  "rev": 0,
  "vendor": "UNITED ACCESS FLOORS PRIVATE LIMITED",
  "category": "Raised Flooring",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-10",
  "value": 137140.0,
  "terms": "Advance payment 100%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272195 rev 0 on WESTCHEM TECHNOLOGIES PRIVATE LIMITED for Epoxy Flooring: Epoxy flooring: anti-static self-leveling in AHU/electrical/UPS/hub/battery/server rooms 30 sqm + colored self-leveling 15 sqm",
  "po": "FSL2026272195",
  "rev": 0,
  "vendor": "WESTCHEM TECHNOLOGIES PRIVATE LIMITED",
  "category": "Epoxy Flooring",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-10",
  "value": 91173.0,
  "terms": "Advance 50%, after completion 50%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "commitment",
  "source": "po",
  "day": "2026-07-16",
  "text": "PO FSL2026272212 rev 2 on Pacific Product & Solutions for Toilet Cubicles: Toilet cubicles Stylam 12mm, 16 nos, restroom skylight model",
  "po": "FSL2026272212",
  "rev": 2,
  "vendor": "Pacific Product & Solutions",
  "category": "Toilet Cubicles",
  "orderDate": "2026-07-14",
  "deliveryDate": "2026-07-13",
  "value": 396480.0,
  "terms": "Advance 50%, before dispatch 30%, after installation 20%",
  "purchaser": "Rahul Singh",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
 },
 {
  "kind": "contract",
  "source": "contract",
  "day": "2026-07-16",
  "text": "Fit-out agreement: SKF India (Industrial) Ltd and Flipspaces Technology Labs Pvt Ltd. Value 8,21,00,400 incl tax. Signed 05 Jun 2026, e-signed 10 Jun. Commencement 08 Jun 2026, completion 75 days (about 22 Aug); SSOT handover 15 Aug, internal 10 Aug. Item rate re-measurable. No mobilisation advance. RA milestones: RA2 day 20 at 20 pct, RA3 day 40 at 25 pct, RA4 day 55 at 25 pct, RA5 day 70 at 25 pct, RA6 day 75 at 5 pct vs DLP BG. 7 day payment cycle. PBG 5 pct. DLP 12 months. LD 1 pct per week cap 5 pct. Builder deposit 13,24,200. Site: Units 801/802 Phoenix Millennium Tower 3 Wakad, 26,484 sqft. PM Atish Parganiha.",
  "value": 82100400,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "clause 29.1 conflictingly states LD 0 pct while the LD schedule says 1 pct per week cap 5 pct, query raised"
 },
 {
  "kind": "commitment",
  "source": "client_po",
  "day": "2026-07-16",
  "text": "Client PO 4300632629 dated 26 Jun 2026: GCC Office Equipment per BOQ, 3,15,64,507. 7 days net, progressive RA per contract clause 6.",
  "po": "4300632629",
  "value": 31564507,
  "orderDate": "2026-06-26",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "commitment",
  "source": "client_po",
  "day": "2026-07-16",
  "text": "Client PO 4300632630 dated 26 Jun 2026: GCC Interior Work, 5,05,35,893. 7 days net, progressive RA per contract clause 6.",
  "po": "4300632630",
  "value": 50535893,
  "orderDate": "2026-06-26",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "the two client POs sum to 8,21,00,400 which exactly matches the agreement value, cross check passes"
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A ARCHITECTURAL WORKS: CIVIL AND INTERIORS: client amount broken formula, derived approx 21,824,503, BCS 16,128,074",
  "code": "A",
  "head": "ARCHITECTURAL WORKS: CIVIL AND INTERIORS",
  "value": null,
  "bcs": 16128074.0,
  "confidence": "medium",
  "zone": null,
  "task": null,
  "flag": "client amount cell exported as #ERROR, derived value is approximate, confirm from the master BOQ"
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A1 CIVIL WORKS: client amount broken formula, derived approx 1,781,747, BCS 1,282,858",
  "code": "A1",
  "head": "CIVIL WORKS",
  "value": null,
  "bcs": 1282858.0,
  "confidence": "medium",
  "zone": null,
  "task": null,
  "flag": "client amount cell exported as #ERROR, derived value is approximate, confirm from the master BOQ"
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A2 INTERIOR WORKS: client amount 15,573,856, BCS 11,621,460",
  "code": "A2",
  "head": "INTERIOR WORKS",
  "value": 15573856.0,
  "bcs": 11621460.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A3 MODULAR GLASS PARTITIONS AND DOORS: client amount 2,458,250, BCS 1,769,940",
  "code": "A3",
  "head": "MODULAR GLASS PARTITIONS AND DOORS",
  "value": 2458250.0,
  "bcs": 1769940.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A4 SIGNAGES: client amount 158,100, BCS 113,832",
  "code": "A4",
  "head": "SIGNAGES",
  "value": 158100.0,
  "bcs": 113832.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A5 GRAPHICS AND FILMS: client amount 704,550, BCS 513,424",
  "code": "A5",
  "head": "GRAPHICS AND FILMS",
  "value": 704550.0,
  "bcs": 513424.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A6 BLINDS: client amount 906,000, BCS 652,320",
  "code": "A6",
  "head": "BLINDS",
  "value": 906000.0,
  "bcs": 652320.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 A7 PLANTERS: client amount 242,000, BCS 174,240",
  "code": "A7",
  "head": "PLANTERS",
  "value": 242000.0,
  "bcs": 174240.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 B FURNITURE AND FURNISHING: client amount 14,791,410, BCS 10,649,815",
  "code": "B",
  "head": "FURNITURE AND FURNISHING",
  "value": 14791410.0,
  "bcs": 10649815.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 B1 CARPET FLOORING: client amount 3,419,125, BCS 2,461,770",
  "code": "B1",
  "head": "CARPET FLOORING",
  "value": 3419125.0,
  "bcs": 2461770.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 B2 MODULAR FURNITURE: client amount 5,326,045, BCS 3,834,752",
  "code": "B2",
  "head": "MODULAR FURNITURE",
  "value": 5326045.0,
  "bcs": 3834752.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 B3 LOOSE FURNITURE & CHAIRS: client amount 6,046,240, BCS 4,353,293",
  "code": "B3",
  "head": "LOOSE FURNITURE & CHAIRS",
  "value": 6046240.0,
  "bcs": 4353293.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 C ELECTRICAL WORKS: client amount 18,714,717, BCS 13,474,596",
  "code": "C",
  "head": "ELECTRICAL WORKS",
  "value": 18714717.0,
  "bcs": 13474596.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 C1 ELECTRICAL WORKS: client amount 13,398,707, BCS 9,647,069",
  "code": "C1",
  "head": "ELECTRICAL WORKS",
  "value": 13398707.0,
  "bcs": 9647069.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 C2 LIGHT FIXTURES: client amount 2,007,400, BCS 1,445,328",
  "code": "C2",
  "head": "LIGHT FIXTURES",
  "value": 2007400.0,
  "bcs": 1445328.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 C3 UPS: client amount 3,308,610, BCS 2,382,199",
  "code": "C3",
  "head": "UPS",
  "value": 3308610.0,
  "bcs": 2382199.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 D HVAC: client amount 13,239,899, BCS 9,532,727",
  "code": "D",
  "head": "HVAC",
  "value": 13239899.0,
  "bcs": 9532727.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 D1 HVAC LOW SIDE: client amount 8,332,095, BCS 5,999,108",
  "code": "D1",
  "head": "HVAC LOW SIDE",
  "value": 8332095.0,
  "bcs": 5999108.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 D2 HVAC VAV: client amount 2,224,872, BCS 1,601,908",
  "code": "D2",
  "head": "HVAC VAV",
  "value": 2224872.0,
  "bcs": 1601908.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 D3 HVAC VRF: client amount 2,682,932, BCS 1,931,711",
  "code": "D3",
  "head": "HVAC VRF",
  "value": 2682932.0,
  "bcs": 1931711.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 E DATA NETWORK: client amount 5,885,280, BCS 4,237,402",
  "code": "E",
  "head": "DATA NETWORK",
  "value": 5885280.0,
  "bcs": 4237402.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 E1 PASSIVE NETWORKING: client amount 5,885,280, BCS 4,237,402",
  "code": "E1",
  "head": "PASSIVE NETWORKING",
  "value": 5885280.0,
  "bcs": 4237402.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 F PHE WORKS: client amount 464,360, BCS 334,339",
  "code": "F",
  "head": "PHE WORKS",
  "value": 464360.0,
  "bcs": 334339.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 F1 PLUMBING WORKS: client amount 464,360, BCS 334,339",
  "code": "F1",
  "head": "PLUMBING WORKS",
  "value": 464360.0,
  "bcs": 334339.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G FLSS WORKS: client amount 7,180,231, BCS 5,181,286",
  "code": "G",
  "head": "FLSS WORKS",
  "value": 7180231.0,
  "bcs": 5181286.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G1 FIRE SPRINKLERS: client amount 2,404,511, BCS 1,742,768",
  "code": "G1",
  "head": "FIRE SPRINKLERS",
  "value": 2404511.0,
  "bcs": 1742768.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G2 FIRE DETECTION SYSTEM: client amount 1,527,150, BCS 1,099,548",
  "code": "G2",
  "head": "FIRE DETECTION SYSTEM",
  "value": 1527150.0,
  "bcs": 1099548.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G3 PUBLIC ADDRESS SYSTEM: client amount 832,000, BCS 599,040",
  "code": "G3",
  "head": "PUBLIC ADDRESS SYSTEM",
  "value": 832000.0,
  "bcs": 599040.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G4 FIRE EXTINGUISHERS: client amount 408,600, BCS 294,192",
  "code": "G4",
  "head": "FIRE EXTINGUISHERS",
  "value": 408600.0,
  "bcs": 294192.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G5 RODENT REPELLENT SYSTEM: client amount 83,850, BCS 60,372",
  "code": "G5",
  "head": "RODENT REPELLENT SYSTEM",
  "value": 83850.0,
  "bcs": 60372.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G6 WATER LEAK DETECTION SYSTEM: client amount 135,018, BCS 97,213",
  "code": "G6",
  "head": "WATER LEAK DETECTION SYSTEM",
  "value": 135018.0,
  "bcs": 97213.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G7 FIRE EXIT SIGNAGES: client amount 134,300, BCS 96,696",
  "code": "G7",
  "head": "FIRE EXIT SIGNAGES",
  "value": 134300.0,
  "bcs": 96696.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G8 ACCESS CONTROL SYSTEM: client amount 736,850, BCS 530,532",
  "code": "G8",
  "head": "ACCESS CONTROL SYSTEM",
  "value": 736850.0,
  "bcs": 530532.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G9 CCTV SURVEILLANCE SYSTEM: client amount 308,500, BCS 222,120",
  "code": "G9",
  "head": "CCTV SURVEILLANCE SYSTEM",
  "value": 308500.0,
  "bcs": 222120.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 G10 GAS BASED SUPPRESSION SYSTEM (GSS): client amount 609,452, BCS 438,805",
  "code": "G10",
  "head": "GAS BASED SUPPRESSION SYSTEM (GSS)",
  "value": 609452.0,
  "bcs": 438805.0,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "boq",
  "source": "boq",
  "day": "2026-07-16",
  "text": "BOQ R5 FINAL grand total 8,21,00,400 for 26,484 sqft. Matches the agreement value and the two client POs combined.",
  "code": "TOTAL",
  "value": 82100400,
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": null
 },
 {
  "kind": "register",
  "source": "gfc_tracker",
  "day": "2026-07-16",
  "text": "GFC tracker: 58 drawings (9 GFC, 9 TD, 17 elevational TD, 23 MEP). Internal status: 22 completed, 5 in progress, 4 under revision R1, 27 not started including all 23 MEP. Zero SKF side approvals started. Toilet works are developer scope, 45,00,941, separate.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "27 of 58 drawings not started and no client approval loop has begun, this gates ceiling and MEP work"
 },
 {
  "kind": "register",
  "source": "weekly_tracker",
  "day": "2026-07-16",
  "text": "Weekly task tracker Wk4 (dues 30 Jun to 6 Jul): 25 tasks, 17 not started, 6 in progress, 2 blocked. Top risks: furniture PO 1.8 Cr order-by date passed, GFC C-100/C-101 blocked gating ceiling, CAR insurance unbound, RA1 not confirmed, 0.72 Cr MEP BCS exposure.",
  "confidence": "medium",
  "zone": null,
  "task": null,
  "flag": "tracker is 10 days stale on absorb day, confirm a Wk5/Wk6 sheet exists"
 },
 {
  "kind": "context",
  "source": "readme",
  "day": "2026-07-16",
  "text": "START HERE doc: Drive SSOT guide, 12 folder structure feeding the Command Center. Handover 15 Aug 2026. BCS 5.95 Cr, GM 27.5 pct.",
  "confidence": "high",
  "zone": null,
  "task": null
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 01 RCP. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 02 FAPA. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 03 Sprinkler Part 1. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 04 Sprinkler Part 2. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 05 HVAC. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 06 Fire Extinguisher. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 07 Power. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 08 Raw Power. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 09 UPS Power. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 10 Data. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 11 Lighting. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 12 Raceway. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 13 Cable Tray. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 14 WLD. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 15 Rodent Repellent. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 16 Access Control. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 17 CCTV. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 18 Critical Room. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "GFC MEP layout PDF in Drive 02.2: SKF 19 SLD. Not pulled, 0.6 to 5.5 MB each, sits in Drive only.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "in Drive only, not synced locally, pull on demand"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "Master workbook in Drive: R5 BOQ.xlsx (28.5 MB). Too big for the MCP sync limit, recorded, summary CSV absorbed instead.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "too big for MCP sync, in Drive only"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "Master workbook in Drive: R4 BOQ_BCS.xlsx (28.3 MB). Too big for the MCP sync limit, recorded, summary CSV absorbed instead.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "too big for MCP sync, in Drive only"
 },
 {
  "kind": "register",
  "source": "drive",
  "day": "2026-07-16",
  "text": "Master workbook in Drive: Sampling.xlsx (44 MB). Too big for the MCP sync limit, recorded, summary CSV absorbed instead.",
  "confidence": "high",
  "zone": null,
  "task": null,
  "flag": "too big for MCP sync, in Drive only"
 }
],
  supersedes: [
 {
  "po": "FSL2026272008",
  "fact": {
   "kind": "commitment",
   "source": "po",
   "day": "2026-07-16",
   "text": "PO FSL2026272008 rev 8 on RAZA ENTERPRISES for Gypsum & Ceilings: Interior gypsum works: 735 sqm full height gypsum partitions with Rockwool insulation, 550 sqm plain gypsum ceiling, acoustic wooden grid, fire rated and designer laminate ceilings, column cladding, ply backing and ceiling trap doors",
   "po": "FSL2026272008",
   "rev": 8,
   "vendor": "RAZA ENTERPRISES",
   "category": "Gypsum & Ceilings",
   "orderDate": "2026-07-14",
   "deliveryDate": "2026-06-30",
   "value": 3969890.0,
   "terms": "Basic Payment After Submission of Invoice Within 15 Days 85%, Basic Payment After site Handover with complete documentation and snagfree site within 30 Days 10%, Retention for 12 Months 5%",
   "purchaser": "Rahul Singh",
   "confidence": "high",
   "zone": null,
   "task": null,
   "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
  }
 },
 {
  "po": "FSL2026272077",
  "fact": {
   "kind": "commitment",
   "source": "po",
   "day": "2026-07-16",
   "text": "PO FSL2026272077 rev 0 on A.R Khan for Plumbing: Complete internal plumbing work for toilets: concealed/exposed water supply and waste piping plus supply and fixing of sanitary fixtures for 16 toilets, 8 urinals, 13 wash basins, 2 bathrooms, all pantry sinks with RO and geyser points, incl. testing and commissioning (lumpsum 1 LMSM)",
   "po": "FSL2026272077",
   "rev": 0,
   "vendor": "A.R Khan",
   "category": "Plumbing",
   "orderDate": "2026-07-14",
   "deliveryDate": "2026-06-23",
   "value": 600000.0,
   "terms": "Advance 20%, after completion of 100% piping 30%, after completion of 100% sanitary installation 35%, after all work completion 10%, retention of 12 months 5%",
   "purchaser": "Rahul Singh",
   "confidence": "high",
   "zone": null,
   "task": null,
   "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
  }
 },
 {
  "po": "FSL2026272161",
  "fact": {
   "kind": "commitment",
   "source": "po",
   "day": "2026-07-16",
   "text": "PO FSL2026272161 rev 4 on M.N.Electricals for ELV & Fire Alarm: Fire alarm (Honeywell Notifier UL) + PA system (Bosch) + rodent repellent + water leak detection + CCTV NVR 32ch + 25 dome cameras + switches",
   "po": "FSL2026272161",
   "rev": 4,
   "vendor": "M.N.Electricals",
   "category": "ELV & Fire Alarm",
   "orderDate": "2026-07-14",
   "deliveryDate": "2026-07-07",
   "value": 2451810.0,
   "terms": "RA bill 85%, completion 10%, retention 5%",
   "purchaser": "Rahul Singh",
   "confidence": "high",
   "zone": null,
   "task": null,
   "flag": "Order Date on the PDF is the Vizdom revision stamp (14 Jul 2026 on all 30 POs), not the original order date. Delivery dates before it are expected, not an error."
  }
 }
],
  queries: [
 {
  "about": "schedule header rows",
  "question": "9 rows in the plan sheet carry no task name and no dates (a header row and 8 scope legend rows like Meeting Rooms/Demolition). They were skipped as structure, not tasks. Confirm.",
  "blocking": false
 },
 {
  "about": "PO FSL2026272128 total",
  "question": "UPS PO printed grand total 21,24,000.00 does not equal taxable 18,00,000.00 plus the printed GST lines. The printed grand total was kept. Confirm which is right.",
  "blocking": false
 },
 {
  "about": "agreement LD clause",
  "question": "The LD schedule says 1 pct per week capped at 5 pct but clause 29.1 says LD 0 pct. Which governs?",
  "blocking": false
 },
 {
  "about": "BOQ broken cells",
  "question": "BOQ summary cells for A (Architectural total) and A1 (Civil) exported as #ERROR. Approx values were derived from BCS and margin. Confirm from the master R5 BOQ.",
  "blocking": false
 },
 {
  "about": "weekly tracker freshness",
  "question": "Latest weekly tracker in Drive is Wk4 (dues to 6 Jul), 10 days stale. Where do Wk5 and Wk6 live?",
  "blocking": false
 }
],
  closes: [
 {
  "about": "baseline plan",
  "answer": "Resolved by Sourabh 16 Jul: follow the excel for planning. Baseline locked from the schedule xlsx current plan sheet, 63 tasks, planVersion xlsx-v1. The Planning Engine export is no longer awaited."
 },
 {
  "about": "site schedule",
  "answer": "The xlsx is no longer reference only. It IS the baseline per Sourabh 16 Jul, locked as xlsx-v1."
 },
 {
  "about": "remaining POs",
  "answer": "Approved and done. All 30 POs pulled from Drive 03.1 on 16 Jul, canonical extracts saved, 30 commitment facts in the ledger. Committed vendor value 61,993,631."
 },
 {
  "about": "PO total FSL2026272161",
  "answer": "Read from rev 4 full text: 24,51,810.00 on M.N.Electricals, scope is fire alarm, PA, rodent, WLD and CCTV. Old null value fact superseded."
 },
 {
  "about": "PO FSL2026272077 dates",
  "answer": "Systemic, not a one off: Vizdom stamps Order Date with the latest revision date, all 30 POs say 14 Jul 2026. Delivery dates stand as printed. Every PO fact carries this flag."
 }
]
};

function apply(ledger, zones) {
  if (ledger.state.files.some(f => f.name === ABSORB2.marker))
    return { applied: false, why: "batch 2 already absorbed" };
  for (const f of ABSORB2.files) ledger.addFile(f);
  for (const fa of ABSORB2.facts) ledger.addFact(fa);
  let superseded = 0;
  for (const s of ABSORB2.supersedes) {
    const old = ledger.state.facts.find(f => f.po === s.po && !f.supersededBy && f.source === "po");
    if (old) { ledger.supersede(old.id, s.fact); superseded++; }
    else { ledger.addFact(s.fact); }
  }
  for (const q of ABSORB2.queries) ledger.addQuery(q);
  for (const c of ABSORB2.closes) {
    const q = ledger.state.queries.find(x => x.status === "open" && x.about === c.about);
    if (q) ledger.answerQuery(q.id, c.answer);
  }
  return { applied: true, facts: ABSORB2.facts.length, superseded,
           files: ABSORB2.files.length, queries: ABSORB2.queries.length, closes: ABSORB2.closes.length };
}

root.TRACK_ABSORB2 = { ABSORB2, apply };
if (typeof module !== "undefined" && module.exports) module.exports = root.TRACK_ABSORB2;

})(typeof window !== "undefined" ? window : globalThis);
